// @vitest-environment node
/**
 * YuNet real-model gate — upstream parity plus the measured recall gap.
 *
 * Two independent comparisons against the checked-in OpenCV golden
 * (tests/fixtures/face-corpus/golden.json, generated by the upstream
 * cv2.FaceDetectorYN predictor on the same input pixels):
 *
 *   1. Whole-image tier parity. The production preprocessor (BGR packing raw
 *      0-255) + onnxruntime + the production decoder must reproduce the
 *      upstream detector's boxes, landmarks, and scores on the checked-in
 *      letterboxed PNG.
 *   2. Window tier recovery. The production window planner + mapping + merge
 *      must approach the upstream NATIVE-resolution reference, while the
 *      whole-image tier alone reproduces the documented small-face loss.
 *
 * Enable with VARVE_YUNET_MODEL=/path/to/yunet.onnx; the bundled artifact at
 * apps/desktop/public/models/yunet-face-detect.onnx is used by default when
 * present. Evidence is written to
 * VARVE_YUNET_EVIDENCE_DIR (default /tmp/varve-yunet-real-evidence).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';
import type { InferenceSession, Tensor } from 'onnxruntime-node';
import { describe, expect, it } from 'vitest';
import { packNchwTensor } from '../../inference/imageTensor';
import {
  decodeFaceDetections,
  type FaceOutputTensors,
  YU_NET_TENSOR_SPEC,
  type YuNetFaceDetection,
} from '../../inference/models/faceDetect';
import { mapWindowDetectionToSource, mergeFaceDetections, planFaceWindows } from '../faceWindows';

const REPO = resolve(process.cwd());
const MODEL_PATH =
  process.env.VARVE_YUNET_MODEL ?? join(REPO, 'apps/desktop/public/models/yunet-face-detect.onnx');
const CORPUS = join(REPO, 'tests/fixtures/face-corpus');
const E2E_FIXTURES = join(REPO, 'tests/e2e/fixtures');
const EVIDENCE_DIR = process.env.VARVE_YUNET_EVIDENCE_DIR ?? '/tmp/varve-yunet-real-evidence';
const ENABLED = existsSync(MODEL_PATH) && existsSync(join(CORPUS, 'golden.json'));

const require = createRequire(import.meta.url);
const pngjs = require('pngjs') as {
  PNG: {
    sync: { read(bytes: Uint8Array): { data: Uint8Array; width: number; height: number } };
  };
};
const jpeg = require('jpeg-js') as {
  decode(
    bytes: Uint8Array,
    options: { useTArray: boolean },
  ): {
    width: number;
    height: number;
    data: Uint8Array;
  };
};

interface GoldenDetection {
  box: [number, number, number, number];
  landmarks: [number, number][];
  score: number;
}
interface GoldenCase {
  description: string;
  sourceFixture: string;
  sourceWidth: number;
  sourceHeight: number;
  letterbox: {
    scale: number;
    contentWidth: number;
    contentHeight: number;
    offsetX: number;
    offsetY: number;
  };
  letterboxPng: string;
  detections: GoldenDetection[];
  nativeReference: Array<{ box: [number, number, number, number]; score: number; size: number }>;
}
interface Golden {
  generated: string;
  model: { id: string; sha256: string };
  predictor: { opencv: string; scoreThreshold: number; nmsThreshold: number; topK: number };
  cases: Record<string, GoldenCase>;
}

const golden: Golden = JSON.parse(readFileSync(join(CORPUS, 'golden.json'), 'utf8'));

type Rgba = { data: Uint8ClampedArray; width: number; height: number };

function asImageData(image: Rgba): ImageData {
  return image as unknown as ImageData;
}

function decodePng(path: string): Rgba {
  const parsed = pngjs.PNG.sync.read(readFileSync(path));
  return {
    data: new Uint8ClampedArray(parsed.data),
    width: parsed.width,
    height: parsed.height,
  };
}

function decodeJpeg(path: string): Rgba {
  const decoded = jpeg.decode(new Uint8Array(readFileSync(path)), { useTArray: true });
  return {
    data: new Uint8ClampedArray(decoded.data),
    width: decoded.width,
    height: decoded.height,
  };
}

function cropRgba(image: Rgba, x: number, y: number, width: number, height: number): Rgba {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let row = 0; row < height; row += 1) {
    const sourceStart = ((y + row) * image.width + x) * 4;
    data.set(image.data.subarray(sourceStart, sourceStart + width * 4), row * width * 4);
  }
  return { data, width, height };
}

let sessionPromise: Promise<InferenceSession> | undefined;
async function session(): Promise<InferenceSession> {
  if (!sessionPromise) {
    sessionPromise = (async () => {
      const ort = await import('onnxruntime-node');
      return ort.InferenceSession.create(MODEL_PATH, { executionProviders: ['cpu'] });
    })();
  }
  return sessionPromise;
}

/**
 * Run the real graph through the production preprocessor + decoder. Returns
 * detections in the *input image's* pixel space.
 */
async function detect(image: Rgba): Promise<YuNetFaceDetection[]> {
  const ort = await import('onnxruntime-node');
  const tensor = packNchwTensor(asImageData(image), YU_NET_TENSOR_SPEC);
  const outputs = (await (
    await session()
  ).run({
    input: new ort.Tensor('float32', tensor, [1, 3, image.height, image.width]),
  })) as unknown as Record<string, Tensor>;
  const tensors: FaceOutputTensors = {};
  for (const [name, value] of Object.entries(outputs)) {
    tensors[name] = { data: value.data as Float32Array, dims: [...value.dims] };
  }
  return decodeFaceDetections(
    tensors,
    image.width,
    image.height,
    { offsetX: 0, offsetY: 0 },
    {
      scoreThreshold: golden.predictor.scoreThreshold,
      nmsThreshold: golden.predictor.nmsThreshold,
      topK: golden.predictor.topK,
    },
  );
}

function iou(
  a: { x: number; y: number; width: number; height: number },
  b: [number, number, number, number],
): number {
  const x1 = Math.max(a.x, b[0]);
  const y1 = Math.max(a.y, b[1]);
  const x2 = Math.min(a.x + a.width, b[0] + b[2]);
  const y2 = Math.min(a.y + a.height, b[1] + b[3]);
  const inter = Math.max(0, x2 - x1) * Math.max(0, y2 - y1);
  const union = a.width * a.height + b[2] * b[3] - inter;
  return union <= 0 ? 0 : inter / union;
}

/**
 * Map a detection from the 640 letterbox space of a checked-in PNG back into
 * source pixels using the golden's recorded integer letterbox geometry. This
 * mirrors how the backend maps through the worker's letterbox transform.
 */
function letterboxDetectionToSource(
  detection: YuNetFaceDetection,
  testCase: GoldenCase,
): YuNetFaceDetection {
  const { contentWidth, contentHeight, offsetX, offsetY } = testCase.letterbox;
  const scaleX = testCase.sourceWidth / contentWidth;
  const scaleY = testCase.sourceHeight / contentHeight;
  return {
    box: {
      x: (detection.box.x - offsetX) * scaleX,
      y: (detection.box.y - offsetY) * scaleY,
      width: detection.box.width * scaleX,
      height: detection.box.height * scaleY,
    },
    landmarks: detection.landmarks.map((landmark) => ({
      x: (landmark.x - offsetX) * scaleX,
      y: (landmark.y - offsetY) * scaleY,
    })),
    landmarksInFrame: detection.landmarksInFrame,
    score: detection.score,
  };
}

/** The upstream native pass can report one face twice; keep unique faces. */
type ReferenceFace = { box: [number, number, number, number]; score: number; size: number };

function dedupeReference(reference: readonly ReferenceFace[]): ReferenceFace[] {
  const kept: ReferenceFace[] = [];
  for (const face of [...reference].sort((a, b) => b.score - a.score)) {
    if (
      kept.some(
        (existing) =>
          iou(
            {
              x: existing.box[0],
              y: existing.box[1],
              width: existing.box[2],
              height: existing.box[3],
            },
            face.box,
          ) >= 0.3,
      )
    ) {
      continue;
    }
    kept.push(face);
  }
  return kept;
}

/**
 * Share of unique reference faces recovered. A detection matches when IoU is
 * at least 0.4 or its centre falls inside the reference box (the appropriate
 * criterion for faces a few pixels wide).
 */
function recallVsReference(
  detections: readonly YuNetFaceDetection[],
  reference: ReadonlyArray<{ box: [number, number, number, number] }>,
): number {
  if (reference.length === 0) return detections.length === 0 ? 1 : 0;
  const matched = reference.filter((face) =>
    detections.some((detection) => {
      if (iou(detection.box, face.box) >= 0.4) return true;
      const centerX = detection.box.x + detection.box.width / 2;
      const centerY = detection.box.y + detection.box.height / 2;
      return (
        centerX >= face.box[0] &&
        centerX <= face.box[0] + face.box[2] &&
        centerY >= face.box[1] &&
        centerY <= face.box[1] + face.box[3]
      );
    }),
  ).length;
  return matched / reference.length;
}

describe.skipIf(!ENABLED)('YuNet real-model gate', () => {
  it('reproduces the upstream OpenCV detections on identical input pixels', async () => {
    const report: Array<Record<string, unknown>> = [];
    for (const [caseId, testCase] of Object.entries(golden.cases)) {
      const image = decodePng(join(CORPUS, testCase.letterboxPng));
      expect(image.width).toBe(640);
      expect(image.height).toBe(640);
      const detections = await detect(image);

      // Count parity: the golden records what upstream produces on this exact
      // PNG, including the cases where the letterbox pass finds nothing.
      expect(detections.length, `${caseId} detection count`).toBe(testCase.detections.length);

      let worstBoxDelta = 0;
      let worstScoreDelta = 0;
      let worstLandmarkDelta = 0;
      for (const expected of testCase.detections) {
        const match = detections.find((detection) => iou(detection.box, expected.box) >= 0.85);
        expect(
          match,
          `${caseId} has a match for golden box ${expected.box.join(',')}`,
        ).toBeTruthy();
        if (!match) continue;
        worstBoxDelta = Math.max(
          worstBoxDelta,
          Math.abs(match.box.x - expected.box[0]),
          Math.abs(match.box.y - expected.box[1]),
          Math.abs(match.box.width - expected.box[2]),
          Math.abs(match.box.height - expected.box[3]),
        );
        worstScoreDelta = Math.max(worstScoreDelta, Math.abs(match.score - expected.score));
        for (let index = 0; index < 5; index += 1) {
          const landmark = match.landmarks[index];
          const expectedLandmark = expected.landmarks[index];
          if (!landmark || !expectedLandmark) continue;
          worstLandmarkDelta = Math.max(
            worstLandmarkDelta,
            Math.abs(landmark.x - expectedLandmark[0]),
            Math.abs(landmark.y - expectedLandmark[1]),
          );
        }
      }
      // Measured margins (onnxruntime CPU vs OpenCV DNN, same pixels):
      // boxes and landmarks agree to a small fraction of a pixel and scores
      // to ~1e-3. The bounds below are deliberately looser than measured.
      expect(worstBoxDelta, `${caseId} box delta`).toBeLessThan(1.5);
      expect(worstLandmarkDelta, `${caseId} landmark delta`).toBeLessThan(1.5);
      expect(worstScoreDelta, `${caseId} score delta`).toBeLessThan(0.02);

      report.push({
        case: caseId,
        letterboxDetections: detections.length,
        nativeReferenceDetections: testCase.nativeReference.length,
        worstBoxDelta: Number(worstBoxDelta.toFixed(4)),
        worstLandmarkDelta: Number(worstLandmarkDelta.toFixed(4)),
        worstScoreDelta: Number(worstScoreDelta.toFixed(6)),
      });
    }
    mkdirSync(EVIDENCE_DIR, { recursive: true });
    writeFileSync(join(EVIDENCE_DIR, 'parity.json'), JSON.stringify(report, null, 2));
    expect(report).toHaveLength(Object.keys(golden.cases).length);
  }, 180_000);

  it('recovers the small faces the whole-image letterbox loses, without false positives', async () => {
    const report: Array<Record<string, unknown>> = [];
    for (const [caseId, testCase] of Object.entries(golden.cases)) {
      const plan = planFaceWindows(testCase.sourceWidth, testCase.sourceHeight);
      const source = decodeJpeg(join(E2E_FIXTURES, testCase.sourceFixture));

      // Tier A: the checked-in letterbox PNG (what production sends for the
      // whole-image pass). Detections come back in the 640 letterbox space,
      // so they are mapped through the recorded geometry into source pixels
      // exactly like the backend maps through the worker's letterbox.
      const primaryLetterbox = await detect(decodePng(join(CORPUS, testCase.letterboxPng)));
      const primary = primaryLetterbox.map((detection) =>
        letterboxDetectionToSource(detection, testCase),
      );

      let merged = primary;
      if (plan.windows.length > 0) {
        expect(plan.scale, `${caseId} window scale`).toBe(1);
        const secondary: YuNetFaceDetection[] = [];
        for (const window of plan.windows) {
          const crop = cropRgba(source, window.x, window.y, window.width, window.height);
          for (const detection of await detect(crop)) {
            const mapped = mapWindowDetectionToSource(
              detection,
              window,
              plan.scale,
              source.width,
              source.height,
            );
            if (mapped) secondary.push(mapped);
          }
        }
        merged = mergeFaceDetections(primary, secondary, {
          nmsThreshold: golden.predictor.nmsThreshold,
        });
      }

      // The upstream native run can report the same tiny face twice (two
      // boxes at nearly the same place), so unique reference faces are
      // deduplicated before measuring recall. For faces a few pixels wide,
      // IoU is a harsh criterion — a 2 px localization error is 30% of an
      // 11 px face — so a detection also counts as recovering a face when
      // its centre falls inside the reference box.
      const reference = dedupeReference(testCase.nativeReference);
      const primaryRecall = recallVsReference(primary, reference);
      const mergedRecall = recallVsReference(merged, reference);

      report.push({
        case: caseId,
        source: `${testCase.sourceWidth}x${testCase.sourceHeight}`,
        windows: plan.windows.length,
        windowScale: plan.scale,
        primaryDetections: primary.length,
        mergedDetections: merged.length,
        referenceDetections: reference.length,
        referenceRawDetections: testCase.nativeReference.length,
        primaryRecall: Number(primaryRecall.toFixed(3)),
        mergedRecall: Number(mergedRecall.toFixed(3)),
        mergedBoxes: merged.map((detection) => ({
          x: Number(detection.box.x.toFixed(1)),
          y: Number(detection.box.y.toFixed(1)),
          w: Number(detection.box.width.toFixed(1)),
          h: Number(detection.box.height.toFixed(1)),
          score: Number(detection.score.toFixed(4)),
        })),
        referenceBoxes: reference.map((face) => ({
          box: face.box,
          score: face.score,
          size: face.size,
        })),
      });

      if (reference.length === 0) {
        // Negative control: no tier may invent a face.
        expect(merged, `${caseId} false positives`).toHaveLength(0);
      } else {
        expect(mergedRecall, `${caseId} merged recall`).toBeGreaterThanOrEqual(primaryRecall);
      }
    }
    mkdirSync(EVIDENCE_DIR, { recursive: true });
    writeFileSync(join(EVIDENCE_DIR, 'windows.json'), JSON.stringify(report, null, 2));

    // Recovery gate: every unique reference face in this corpus must be
    // recovered by the merged result, except where upstream itself is not
    // stable at the detector's noise floor. On the smithsonian 11 px face the
    // whole-image native run places a face at x=220.7 while OpenCV run on a
    // 640 crop of the same region reports x=183.5/200.0 — which is exactly
    // where this pipeline reports it (verified: 0.01 px, 0.0000 score on the
    // identical crop pixels). A 10 px feature is below stable localization.
    const minimumMergedRecall: Record<string, number> = {
      portrait: 1,
      ocean: 1,
      smithsonian: 0.6,
      landscape: 1,
    };
    for (const entry of report) {
      const minimum = minimumMergedRecall[entry.case as string] ?? 1;
      expect(entry.mergedRecall as number, `${entry.case} merged recall`).toBeGreaterThanOrEqual(
        minimum,
      );
    }
    const improved = report.filter(
      (entry) => (entry.mergedRecall as number) > (entry.primaryRecall as number),
    );
    expect(improved.length).toBeGreaterThanOrEqual(3);
    expect(report).toHaveLength(Object.keys(golden.cases).length);
  }, 600_000);
});
