import {
  type Adjustment,
  defaultStudioTreatmentControlValues,
  EFFECT_STUDIO_CATEGORIES,
  EFFECT_SURFACE_GUIDANCE,
  type EffectDefinition,
  type EffectStudioCategoryId,
  getEffectDefinition,
  getEffectStudioTreatment,
  resolveStudioTreatmentEffects,
  type StudioTreatment,
  searchEffectStudioDefinitions,
  searchEffectStudioTreatments,
  studioTreatmentControls,
} from '@varve/engine';
import {
  appendEffectLook,
  canHaveSmartFilters,
  createEffectLook,
  cryptoId,
  type EffectLook,
  makeSmartFilter,
  type SceneNode,
} from '@varve/scene';
import { SOLID_CHROME_ICONS, SolidIcon } from '@varve/ui';
import { type ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useEditor } from '../../../context';
import { EffectStudioComparison } from '../../EffectStudio/EffectStudioComparison';
import { DisclosureSection } from '../controls/DisclosureSection';
import { RangeValueControl } from '../controls/RangeValueControl';
import './effectStudio.css';

const FAVORITES_KEY = 'varve:effect-studio:favorites';
const RECENTS_KEY = 'varve:effect-studio:recents';
const MAX_LIBRARY_IDS = 32;

/** Preserve prior raw-effect saves when the Studio becomes treatment-first. */
const LEGACY_TREATMENT_BY_PRIMITIVE: Readonly<Record<string, string>> = {
  bloom: 'studio-chromatic-bloom',
  caustics: 'studio-refracted-light',
  colorHalftone: 'studio-screen-print',
  crt: 'studio-neon-phosphor',
  dither: 'studio-pencil-poster',
  duotone: 'studio-inked-paper',
  lensFlare: 'studio-aperture-star',
  lightLeak: 'studio-light-leak',
  lightShafts: 'studio-cinema-shafts',
  paletteSnap: 'studio-palette-cut',
  rgbSplit: 'studio-glass-shift',
  tritone: 'studio-pigment-wash',
  vhs: 'studio-analog-signal',
};

interface StudioPreview {
  nodeId: string;
  treatmentId: string;
  instanceId: string;
  effectIds: string[];
  values: Record<string, number>;
  name: string;
}

interface TreatmentTuning {
  treatmentId: string;
  values: Record<string, number>;
  /** Present when the user is editing an already-applied recipe. */
  instanceId?: string;
  customized?: boolean;
}

interface AppliedStudioTreatment {
  /** Treatment and instance together are the durable group identity. */
  key: string;
  treatment: StudioTreatment;
  instanceId: string;
  effectIds: string[];
  /** The actual ordered Object Filter entries generated by this recipe. */
  effects: AppliedStudioEffect[];
  values: Record<string, number>;
  customized: boolean;
  firstIndex: number;
}

interface AppliedStudioEffect {
  id: string;
  kind: Adjustment['kind'];
  effectIndex: number;
  visible: boolean;
}

interface RecipeStep {
  effectIndex: number;
  kind: Adjustment['kind'];
  controlledValues: Array<{
    label: string;
    parameter: string;
    value: unknown;
  }>;
}

function studioTreatmentInstanceKey(treatmentId: string, instanceId: string): string {
  // Instance IDs are generated uniquely in normal operation, but documents and
  // Looks are imported data. Keep the treatment id in the group key so a
  // malformed or legacy collision cannot merge two visible applied treatments.
  return `${treatmentId}\u0000${instanceId}`;
}

interface TreatmentGroup {
  id: string;
  label: string;
  description: string;
  treatments: StudioTreatment[];
}

function readIds(key: string): string[] {
  if (typeof window === 'undefined') return [];
  try {
    const value: unknown = JSON.parse(window.localStorage.getItem(key) ?? '[]');
    return Array.isArray(value)
      ? value.filter((id): id is string => typeof id === 'string').slice(0, MAX_LIBRARY_IDS)
      : [];
  } catch {
    return [];
  }
}

function writeIds(key: string, ids: readonly string[]): void {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(key, JSON.stringify(ids.slice(0, MAX_LIBRARY_IDS)));
  } catch {
    // Browser storage can be disabled or full; the current session still works.
  }
}

function readTreatmentIds(key: string): string[] {
  const ids = readIds(key);
  const migrated = [...new Set(ids.map((id) => LEGACY_TREATMENT_BY_PRIMITIVE[id] ?? id))];
  if (migrated.length !== ids.length || migrated.some((id, index) => id !== ids[index])) {
    writeIds(key, migrated);
  }
  return migrated;
}

function remember(id: string, current: readonly string[]): string[] {
  return [id, ...current.filter((entry) => entry !== id)].slice(0, MAX_LIBRARY_IDS);
}

function treatmentControlValues(
  treatment: StudioTreatment,
  values: Readonly<Record<string, number>> = {},
): Record<string, number> {
  const defaults = defaultStudioTreatmentControlValues(treatment);
  return Object.fromEntries(
    Object.entries(defaults).map(([id, defaultValue]) => {
      const candidate = values[id];
      return [
        id,
        typeof candidate === 'number' && Number.isFinite(candidate) ? candidate : defaultValue,
      ];
    }),
  );
}

function studioTreatmentFilters(
  treatment: StudioTreatment,
  values: Readonly<Record<string, number>>,
  instanceId: string,
  effectIds?: readonly string[],
): Adjustment[] {
  const controls = treatmentControlValues(treatment, values);
  return resolveStudioTreatmentEffects(treatment, controls).map((effect, effectIndex) =>
    makeSmartFilter(effectIds?.[effectIndex] ?? cryptoId(), effect.kind, {
      ...effect.overrides,
      visible: true,
      studioTreatment: {
        treatmentId: treatment.id,
        instanceId,
        effectIndex,
        controls,
      },
    }),
  );
}

function appendStudioTreatment(
  node: SceneNode,
  treatment: StudioTreatment,
  values: Readonly<Record<string, number>> = {},
  instanceId = cryptoId(),
): SceneNode {
  return {
    ...node,
    smartFiltersEnabled: true,
    smartFilters: [
      ...(node.smartFilters ?? []),
      ...studioTreatmentFilters(treatment, values, instanceId),
    ],
  };
}

function appliedStudioTreatments(filters: readonly Adjustment[]): AppliedStudioTreatment[] {
  const instances = new Map<string, AppliedStudioTreatment>();
  for (const [index, filter] of filters.entries()) {
    const metadata = filter.studioTreatment;
    if (!metadata) continue;
    const treatment = getEffectStudioTreatment(metadata.treatmentId);
    if (!treatment) continue;
    const key = studioTreatmentInstanceKey(metadata.treatmentId, metadata.instanceId);
    const existing = instances.get(key);
    if (existing) {
      existing.effectIds.push(filter.id);
      existing.effects.push({
        id: filter.id,
        kind: filter.kind,
        effectIndex: metadata.effectIndex,
        visible: filter.visible !== false,
      });
      existing.customized ||= metadata.customized === true;
      continue;
    }
    instances.set(key, {
      key,
      treatment,
      instanceId: metadata.instanceId,
      effectIds: [filter.id],
      effects: [
        {
          id: filter.id,
          kind: filter.kind,
          effectIndex: metadata.effectIndex,
          visible: filter.visible !== false,
        },
      ],
      values: treatmentControlValues(treatment, metadata.controls),
      customized: metadata.customized === true,
      firstIndex: index,
    });
  }
  return [...instances.values()]
    .map((instance) => ({
      ...instance,
      effects: [...instance.effects].sort((left, right) => left.effectIndex - right.effectIndex),
    }))
    .sort((left, right) => left.firstIndex - right.firstIndex);
}

function effectDisplayName(kind: Adjustment['kind']): string {
  return getEffectDefinition(kind)?.displayName ?? kind.replace(/([A-Z])/g, ' $1');
}

function parameterDisplayName(parameter: string): string {
  return parameter
    .replace(/([A-Z])/g, ' $1')
    .replace(/[-_]/g, ' ')
    .replace(/^./, (letter) => letter.toUpperCase());
}

function formatRecipeValue(value: unknown): string {
  if (typeof value === 'number') {
    return Number.isInteger(value)
      ? String(value)
      : value.toFixed(2).replace(/0+$/, '').replace(/\.$/, '');
  }
  if (typeof value === 'boolean') return value ? 'On' : 'Off';
  if (Array.isArray(value)) return value.join(', ');
  return value === undefined ? 'Default' : String(value);
}

function treatmentRecipeSteps(
  treatment: StudioTreatment,
  values: Readonly<Record<string, number>>,
): RecipeStep[] {
  const effects = resolveStudioTreatmentEffects(
    treatment,
    treatmentControlValues(treatment, values),
  );
  const controls = studioTreatmentControls(treatment);
  return effects.map((effect, effectIndex) => {
    const overrides = effect.overrides as Record<string, unknown> | undefined;
    return {
      effectIndex,
      kind: effect.kind,
      controlledValues: controls.flatMap((control) =>
        control.targets
          .filter((target) => target.effectIndex === effectIndex)
          .map((target) => ({
            label: control.label,
            parameter: parameterDisplayName(target.parameter),
            value: overrides?.[target.parameter],
          })),
      ),
    };
  });
}

function updateStudioTreatmentInstance(
  node: SceneNode,
  treatment: StudioTreatment,
  instanceId: string,
  values: Readonly<Record<string, number>>,
): SceneNode {
  const controls = treatmentControlValues(treatment, values);
  const effects = resolveStudioTreatmentEffects(treatment, controls);
  let updated = false;
  const smartFilters = (node.smartFilters ?? []).map((filter) => {
    const metadata = filter.studioTreatment;
    if (
      !metadata ||
      metadata.treatmentId !== treatment.id ||
      metadata.instanceId !== instanceId ||
      !effects[metadata.effectIndex]
    ) {
      return filter;
    }
    updated = true;
    const effect = effects[metadata.effectIndex]!;
    return {
      ...filter,
      ...effect.overrides,
      studioTreatment: {
        ...metadata,
        controls,
      },
    } as Adjustment;
  });
  // A deliberate tuning action means "show this treatment". This also heals
  // a stack left bypassed by a prior bypass action or a document reload.
  return updated ? { ...node, smartFiltersEnabled: true, smartFilters } : node;
}

function replaceStudioTreatmentInstance(
  node: SceneNode,
  instance: AppliedStudioTreatment,
  values: Readonly<Record<string, number>>,
): SceneNode {
  const filters = node.smartFilters ?? [];
  const firstIndex = filters.findIndex(
    (filter) =>
      filter.studioTreatment?.treatmentId === instance.treatment.id &&
      filter.studioTreatment.instanceId === instance.instanceId,
  );
  if (firstIndex < 0) return node;
  const isMember = (filter: Adjustment) =>
    filter.studioTreatment?.treatmentId === instance.treatment.id &&
    filter.studioTreatment.instanceId === instance.instanceId;
  const insertionIndex = filters.slice(0, firstIndex).filter((filter) => !isMember(filter)).length;
  const withoutInstance = filters.filter((filter) => !isMember(filter));
  return {
    ...node,
    smartFiltersEnabled: true,
    smartFilters: [
      ...withoutInstance.slice(0, insertionIndex),
      ...studioTreatmentFilters(instance.treatment, values, instance.instanceId),
      ...withoutInstance.slice(insertionIndex),
    ],
  };
}

function removeStudioTreatmentInstance(
  node: SceneNode,
  instance: AppliedStudioTreatment,
): SceneNode {
  return {
    ...node,
    smartFilters: (node.smartFilters ?? []).filter(
      (filter) =>
        filter.studioTreatment?.treatmentId !== instance.treatment.id ||
        filter.studioTreatment.instanceId !== instance.instanceId,
    ),
  };
}

function belongsToTreatmentInstance(filter: Adjustment, instance: AppliedStudioTreatment): boolean {
  const metadata = filter.studioTreatment;
  return (
    metadata?.treatmentId === instance.treatment.id && metadata.instanceId === instance.instanceId
  );
}

/** The contiguous run represented by one named treatment, if it remains a coherent recipe. */
function treatmentBlockBounds(
  filters: readonly Adjustment[],
  instance: AppliedStudioTreatment,
): { start: number; end: number } | undefined {
  const start = filters.findIndex((filter) => belongsToTreatmentInstance(filter, instance));
  if (start < 0) return undefined;
  let end = start;
  while (end + 1 < filters.length && belongsToTreatmentInstance(filters[end + 1]!, instance)) {
    end += 1;
  }
  const memberCount = filters.filter((filter) =>
    belongsToTreatmentInstance(filter, instance),
  ).length;
  return end - start + 1 === memberCount ? { start, end } : undefined;
}

/** A raw filter is a one-entry block; named recipe members travel as one block. */
function stackBlockBounds(
  filters: readonly Adjustment[],
  index: number,
): { start: number; end: number } {
  const filter = filters[index];
  const metadata = filter?.studioTreatment;
  if (!filter || !metadata) return { start: index, end: index };
  const belongsToSameBlock = (candidate: Adjustment | undefined) =>
    candidate?.studioTreatment?.treatmentId === metadata.treatmentId &&
    candidate.studioTreatment.instanceId === metadata.instanceId;
  let start = index;
  let end = index;
  while (start > 0 && belongsToSameBlock(filters[start - 1])) start -= 1;
  while (end + 1 < filters.length && belongsToSameBlock(filters[end + 1])) end += 1;
  return { start, end };
}

function moveTreatmentBlock(
  filters: readonly Adjustment[],
  instance: AppliedStudioTreatment,
  direction: -1 | 1,
): Adjustment[] | undefined {
  const target = treatmentBlockBounds(filters, instance);
  if (!target) return undefined;
  if (direction < 0) {
    if (target.start === 0) return undefined;
    const previous = stackBlockBounds(filters, target.start - 1);
    return [
      ...filters.slice(0, previous.start),
      ...filters.slice(target.start, target.end + 1),
      ...filters.slice(previous.start, target.start),
      ...filters.slice(target.end + 1),
    ];
  }
  if (target.end === filters.length - 1) return undefined;
  const next = stackBlockBounds(filters, target.end + 1);
  return [
    ...filters.slice(0, target.start),
    ...filters.slice(next.start, next.end + 1),
    ...filters.slice(target.start, target.end + 1),
    ...filters.slice(next.end + 1),
  ];
}

/** Editing a raw member changes a curated recipe's meaning, so retain that provenance. */
function markTreatmentCustomized(filters: readonly Adjustment[], filterId: string): Adjustment[] {
  const metadata = filters.find((filter) => filter.id === filterId)?.studioTreatment;
  if (!metadata) return [...filters];
  return filters.map((filter) => {
    const member = filter.studioTreatment;
    if (member?.treatmentId !== metadata.treatmentId || member.instanceId !== metadata.instanceId) {
      return filter;
    }
    return {
      ...filter,
      studioTreatment: { ...member, customized: true },
    } as Adjustment;
  });
}

function treatmentGroupsFor(
  treatments: StudioTreatment[],
  query: string,
  category: EffectStudioCategoryId | undefined,
  favoritesOnly: boolean,
): TreatmentGroup[] {
  if (category) {
    const selectedCategory = EFFECT_STUDIO_CATEGORIES.find((entry) => entry.id === category);
    return selectedCategory && treatments.length > 0
      ? [
          {
            id: selectedCategory.id,
            label: selectedCategory.label,
            description: selectedCategory.description,
            treatments,
          },
        ]
      : [];
  }

  if (query || favoritesOnly) {
    return treatments.length > 0
      ? [
          {
            id: favoritesOnly ? 'saved' : 'results',
            label: favoritesOnly ? 'Saved treatments' : 'Search results',
            description: favoritesOnly
              ? 'Treatments saved on this device.'
              : 'Treatment recipes matching your search.',
            treatments,
          },
        ]
      : [];
  }

  return EFFECT_STUDIO_CATEGORIES.map((entry) => ({
    id: entry.id,
    label: entry.label,
    description: entry.description,
    treatments: treatments.filter((treatment) => treatment.categoryId === entry.id),
  })).filter((group) => group.treatments.length > 0);
}

export interface EffectStudioSectionProps {
  nodes: import('@varve/scene').SceneNode[];
  /** Dialog presentation already supplies the Studio title, so it needs no disclosure chrome. */
  presentation?: 'inspector' | 'dialog';
}

function EffectStudioSurface({
  children,
  presentation,
}: {
  children: ReactNode;
  presentation: EffectStudioSectionProps['presentation'];
}) {
  if (presentation === 'dialog') return <>{children}</>;
  return (
    <DisclosureSection title="Effect Studio" id="effect-studio" defaultExpanded>
      {children}
    </DisclosureSection>
  );
}

/**
 * Effect Studio is the creative discovery route for named, editable stacks.
 * Object Filters stays authoritative for entry ordering and parameter editing;
 * Image Tuning and Adjustment Filters keep their correction-specific jobs.
 */
export function EffectStudioSection({
  nodes,
  presentation = 'inspector',
}: EffectStudioSectionProps) {
  const {
    state,
    updateNode,
    updateDoc,
    beginTransaction,
    commitTransaction,
    abortTransaction,
    addSmartFilterToSelected,
    updateNodes,
    announce,
  } = useEditor();
  const node = nodes.length === 1 ? nodes[0] : undefined;
  const compatible = nodes.length > 0 && nodes.every(canHaveSmartFilters);
  const nodeId = node?.id;
  const filters = node?.smartFilters ?? [];
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState<EffectStudioCategoryId | undefined>();
  const [favorites, setFavorites] = useState<string[]>(() => readTreatmentIds(FAVORITES_KEY));
  const [recents, setRecents] = useState<string[]>(() => readTreatmentIds(RECENTS_KEY));
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [preview, setPreview] = useState<StudioPreview | null>(null);
  const previewRef = useRef<StudioPreview | null>(null);
  const [lookName, setLookName] = useState('My Look');
  const [tuning, setTuning] = useState<TreatmentTuning | null>(null);
  const tuningTransactionRef = useRef(false);

  const treatments = useMemo(() => {
    const listed = searchEffectStudioTreatments(query, category);
    if (!favoritesOnly) return listed;
    return listed.filter((treatment) => favorites.includes(treatment.id));
  }, [category, favorites, favoritesOnly, query]);
  const primitiveDefinitions = useMemo(
    () => searchEffectStudioDefinitions('', category),
    [category],
  );
  const groups = useMemo(
    () => treatmentGroupsFor(treatments, query, category, favoritesOnly),
    [category, favoritesOnly, query, treatments],
  );
  const appliedTreatments = useMemo(() => appliedStudioTreatments(filters), [filters]);
  const tuningTreatment = tuning ? getEffectStudioTreatment(tuning.treatmentId) : undefined;

  const updateRecents = useCallback((id: string) => {
    setRecents((current) => {
      const next = remember(id, current);
      writeIds(RECENTS_KEY, next);
      return next;
    });
  }, []);

  const toggleFavorite = useCallback((id: string) => {
    setFavorites((current) => {
      const next = current.includes(id)
        ? current.filter((entry) => entry !== id)
        : [id, ...current];
      writeIds(FAVORITES_KEY, next);
      return next;
    });
  }, []);

  const cancelPreview = useCallback(
    (message = 'Preview cancelled') => {
      if (!previewRef.current) return;
      abortTransaction();
      previewRef.current = null;
      setPreview(null);
      announce(message);
    },
    [abortTransaction, announce],
  );

  const previewTreatment = useCallback(
    (treatment: StudioTreatment, values: Readonly<Record<string, number>> = {}) => {
      if (!nodeId) return;
      const current = previewRef.current;
      if (current && current.nodeId !== nodeId) return;
      const controls = treatmentControlValues(treatment, values);
      const effectIds =
        current?.treatmentId === treatment.id
          ? current.effectIds
          : treatment.effects.map(() => cryptoId());
      const instanceId = current?.treatmentId === treatment.id ? current.instanceId : cryptoId();
      if (!current) beginTransaction('preview');
      updateNode(nodeId, (owner) => {
        const withoutPreview = (owner.smartFilters ?? []).filter(
          (effect) => !current?.effectIds.includes(effect.id),
        );
        return {
          ...owner,
          smartFiltersEnabled: true,
          smartFilters: [
            ...withoutPreview,
            ...studioTreatmentFilters(treatment, controls, instanceId, effectIds),
          ],
        };
      });
      const next: StudioPreview = {
        nodeId,
        treatmentId: treatment.id,
        instanceId,
        effectIds,
        values: controls,
        name: treatment.name,
      };
      previewRef.current = next;
      setPreview(next);
      updateRecents(treatment.id);
      announce(`${treatment.name} previewed`);
    },
    [announce, beginTransaction, nodeId, updateNode, updateRecents],
  );

  const commitPreview = useCallback(() => {
    const current = previewRef.current;
    if (!current) return;
    commitTransaction();
    previewRef.current = null;
    setPreview(null);
    setTuning((active) =>
      active?.treatmentId === current.treatmentId
        ? { ...active, instanceId: current.instanceId, values: current.values, customized: false }
        : active,
    );
    announce(`${current.name} applied`);
  }, [announce, commitTransaction]);

  const applyTreatment = useCallback(
    (treatment: StudioTreatment, values: Readonly<Record<string, number>> = {}) => {
      const controls = treatmentControlValues(treatment, values);
      if (previewRef.current) {
        if (previewRef.current.treatmentId === treatment.id) {
          commitPreview();
        } else {
          previewTreatment(treatment, controls);
        }
        return;
      }
      const singleInstanceId = nodes.length === 1 ? cryptoId() : undefined;
      updateNodes(
        nodes.map((selectedNode) => ({
          id: selectedNode.id,
          update: (current) =>
            appendStudioTreatment(current, treatment, controls, singleInstanceId ?? cryptoId()),
        })),
      );
      if (singleInstanceId) {
        setTuning((active) =>
          active?.treatmentId === treatment.id
            ? { ...active, instanceId: singleInstanceId, values: controls, customized: false }
            : active,
        );
      }
      updateRecents(treatment.id);
      announce(`Applied treatment ${treatment.name}`);
    },
    [announce, commitPreview, nodes, previewTreatment, updateNodes, updateRecents],
  );

  const openTreatmentTuning = useCallback(
    (treatment: StudioTreatment) => {
      if (previewRef.current && previewRef.current.treatmentId !== treatment.id) {
        cancelPreview('Preview cancelled');
      }
      const values = treatmentControlValues(treatment);
      setTuning({ treatmentId: treatment.id, values });
    },
    [cancelPreview],
  );

  const openAppliedTreatmentTuning = useCallback(
    (instance: AppliedStudioTreatment) => {
      if (previewRef.current) cancelPreview('Preview cancelled');
      setTuning({
        treatmentId: instance.treatment.id,
        instanceId: instance.instanceId,
        values: instance.values,
        customized: instance.customized,
      });
    },
    [cancelPreview],
  );

  const beginTuningTransaction = useCallback(() => {
    if (!tuning?.instanceId || tuningTransactionRef.current) return;
    tuningTransactionRef.current = true;
    beginTransaction();
  }, [beginTransaction, tuning?.instanceId]);

  const finishTuningTransaction = useCallback(() => {
    if (!tuningTransactionRef.current) return;
    tuningTransactionRef.current = false;
    commitTransaction();
  }, [commitTransaction]);

  const setTreatmentControl = useCallback(
    (controlId: string, candidate: number) => {
      if (!tuning || !tuningTreatment) return;
      const control = studioTreatmentControls(tuningTreatment).find(
        (entry) => entry.id === controlId,
      );
      if (!control) return;
      const value = Math.min(control.max, Math.max(control.min, candidate));
      const values = { ...tuning.values, [controlId]: value };
      setTuning({ ...tuning, values });
      if (tuning.instanceId && nodeId) {
        updateNode(nodeId, (owner) =>
          updateStudioTreatmentInstance(owner, tuningTreatment, tuning.instanceId!, values),
        );
      } else if (previewRef.current?.treatmentId === tuningTreatment.id) {
        previewTreatment(tuningTreatment, values);
      }
    },
    [nodeId, previewTreatment, tuning, tuningTreatment, updateNode],
  );

  const resetTreatmentControls = useCallback(() => {
    if (!tuning || !tuningTreatment) return;
    const values = treatmentControlValues(tuningTreatment);
    setTuning({ ...tuning, values });
    if (tuning.instanceId && nodeId) {
      updateNode(nodeId, (owner) =>
        updateStudioTreatmentInstance(owner, tuningTreatment, tuning.instanceId!, values),
      );
    } else if (previewRef.current?.treatmentId === tuningTreatment.id) {
      previewTreatment(tuningTreatment, values);
    }
  }, [nodeId, previewTreatment, tuning, tuningTreatment, updateNode]);

  const closeTreatmentTuning = useCallback(() => {
    if (!tuning) return;
    if (!tuning.instanceId && previewRef.current?.treatmentId === tuning.treatmentId) {
      cancelPreview('Preview cancelled');
    }
    setTuning(null);
  }, [cancelPreview, tuning]);

  const restoreAppliedTreatment = useCallback(() => {
    if (!nodeId || !tuning?.instanceId || !tuningTreatment) return;
    const instance = appliedTreatments.find(
      (entry) =>
        entry.treatment.id === tuningTreatment.id && entry.instanceId === tuning.instanceId,
    );
    if (!instance) return;
    updateNode(nodeId, (owner) => replaceStudioTreatmentInstance(owner, instance, tuning.values));
    setTuning({ ...tuning, customized: false });
    announce(`Restored ${tuningTreatment.name} recipe`);
  }, [announce, appliedTreatments, nodeId, tuning, tuningTreatment, updateNode]);

  const removeAppliedTreatment = useCallback(
    (instance: AppliedStudioTreatment) => {
      if (!nodeId) return;
      updateNode(nodeId, (owner) => removeStudioTreatmentInstance(owner, instance));
      setTuning((active) =>
        active?.treatmentId === instance.treatment.id && active.instanceId === instance.instanceId
          ? null
          : active,
      );
      announce(`Removed ${instance.treatment.name} treatment`);
    },
    [announce, nodeId, updateNode],
  );

  const moveAppliedTreatment = useCallback(
    (instance: AppliedStudioTreatment, direction: -1 | 1) => {
      if (!nodeId || !moveTreatmentBlock(filters, instance, direction)) return;
      updateNode(nodeId, (owner) => {
        const reordered = moveTreatmentBlock(owner.smartFilters ?? [], instance, direction);
        return reordered ? { ...owner, smartFilters: reordered } : owner;
      });
      announce(`Moved ${instance.treatment.name} ${direction < 0 ? 'up' : 'down'} in the stack`);
    },
    [announce, filters, nodeId, updateNode],
  );

  const moveStackEffect = useCallback(
    (filter: Adjustment, direction: -1 | 1) => {
      if (!nodeId) return;
      const index = filters.findIndex((entry) => entry.id === filter.id);
      const nextIndex = index + direction;
      if (index < 0 || nextIndex < 0 || nextIndex >= filters.length) return;
      updateNode(nodeId, (owner) => {
        const stack = markTreatmentCustomized(owner.smartFilters ?? [], filter.id);
        const sourceIndex = stack.findIndex((entry) => entry.id === filter.id);
        const [moved] = sourceIndex < 0 ? [] : stack.splice(sourceIndex, 1);
        if (!moved) return owner;
        stack.splice(nextIndex, 0, moved);
        return { ...owner, smartFilters: stack };
      });
      announce(
        `Moved ${effectDisplayName(filter.kind)} ${direction < 0 ? 'up' : 'down'} in the filter stack`,
      );
    },
    [announce, filters, nodeId, updateNode],
  );

  const addPrimitive = useCallback(
    (definition: EffectDefinition) => {
      if (previewRef.current) cancelPreview('Preview cancelled');
      addSmartFilterToSelected(definition.id, undefined);
      announce(`${definition.displayName} added to Object Filters`);
    },
    [addSmartFilterToSelected, announce, cancelPreview],
  );

  const saveLook = useCallback(() => {
    if (filters.length === 0) return;
    const look = createEffectLook(cryptoId(), lookName, filters);
    updateDoc((document) => ({
      ...document,
      effectLooks: [...(document.effectLooks ?? []), look],
    }));
    announce(`Saved Look ${look.name}`);
  }, [announce, filters, lookName, updateDoc]);

  const applyLook = useCallback(
    (look: EffectLook) => {
      if (!nodeId) return;
      updateNode(nodeId, (owner) => ({
        ...owner,
        smartFilters: appendEffectLook(owner.smartFilters ?? [], look, cryptoId),
      }));
      announce(`Applied Look ${look.name}`);
    },
    [announce, nodeId, updateNode],
  );

  const deleteLook = useCallback(
    (lookId: string) => {
      updateDoc((document) => ({
        ...document,
        effectLooks: (document.effectLooks ?? []).filter((look) => look.id !== lookId),
      }));
      announce('Look deleted');
    },
    [announce, updateDoc],
  );

  useEffect(() => {
    if (preview && preview.nodeId !== nodeId) cancelPreview('Preview cancelled: target changed');
    if (
      tuning?.instanceId &&
      !appliedTreatments.some(
        (instance) =>
          instance.treatment.id === tuning.treatmentId && instance.instanceId === tuning.instanceId,
      )
    ) {
      setTuning(null);
    }
  }, [appliedTreatments, cancelPreview, nodeId, preview, tuning?.instanceId]);

  useEffect(
    () => () => {
      if (tuningTransactionRef.current) {
        tuningTransactionRef.current = false;
        commitTransaction();
      }
      if (previewRef.current) abortTransaction();
    },
    [abortTransaction, commitTransaction],
  );

  if (!compatible) return null;

  const recentTreatments = recents
    .map((id) => getEffectStudioTreatment(id))
    .filter((treatment): treatment is StudioTreatment => treatment !== undefined)
    .slice(0, 4);
  const looks = state.document.effectLooks ?? [];
  const targetLabel =
    nodes.length === 1 ? (node?.name ?? 'selected object') : `${nodes.length} objects`;
  const previewing = preview !== null;
  const canPreview = nodeId !== undefined;
  const stackEnabled = node?.smartFiltersEnabled !== false;
  const targetGuidance = EFFECT_SURFACE_GUIDANCE['effect-studio'];
  const selectedRecipeSteps =
    tuning && tuningTreatment ? treatmentRecipeSteps(tuningTreatment, tuning.values) : [];

  return (
    <EffectStudioSurface presentation={presentation}>
      <div className="effect-studio" data-effect-studio>
        <div className="effect-studio__intro">
          <div>
            <h3>Curated editable treatments</h3>
            <p>
              Browse a creative family, preview the actual result, then tune the named treatment on{' '}
              {targetLabel}. Object Filters is reserved for advanced recipe internals.
            </p>
            <details className="effect-studio__target-guidance">
              <summary>How this works on raster and vector objects</summary>
              <p>
                <strong>Raster:</strong> {targetGuidance.rasterBehavior}
              </p>
              <p>
                <strong>Vector:</strong> {targetGuidance.vectorBehavior}
              </p>
            </details>
          </div>
        </div>

        <div className="effect-studio__workspace">
          <EffectStudioComparison
            document={state.document}
            node={node}
            hasEffects={filters.length > 0}
          />
          <aside className="effect-studio__inspector" aria-label="Effect stack and settings">
            <section className="effect-studio__applied" aria-label="Applied effect stack">
              <div className="effect-studio__applied-header">
                <div>
                  <h3>Applied effect stack</h3>
                  <p>
                    Named treatments are the primary stack. Their derived Object Filters stay
                    available for deeper editing.
                  </p>
                </div>
                <small className={stackEnabled ? 'is-live' : 'is-bypassed'}>
                  {stackEnabled ? 'Live' : 'Original shown'}
                </small>
              </div>
              {filters.length > 0 ? (
                <>
                  {appliedTreatments.length > 0 && (
                    <ol className="effect-studio__treatment-stack" aria-label="Applied treatments">
                      {appliedTreatments.map((instance) => {
                        const bounds = treatmentBlockBounds(filters, instance);
                        const canMoveUp = bounds !== undefined && bounds.start > 0;
                        const canMoveDown = bounds !== undefined && bounds.end < filters.length - 1;
                        const reorderHint = bounds
                          ? 'Move the complete curated recipe without changing its meaning.'
                          : 'This recipe has interleaved advanced edits. Reorder its individual filters below.';
                        return (
                          <li
                            className={`effect-studio__recipe-entry${
                              tuning?.treatmentId === instance.treatment.id &&
                              tuning.instanceId === instance.instanceId
                                ? ' is-selected'
                                : ''
                            }`}
                            key={instance.key}
                          >
                            <span className="effect-studio__stack-order" aria-hidden="true">
                              {bounds ? bounds.start + 1 : '–'}
                            </span>
                            <span className="effect-studio__applied-summary">
                              <strong className="effect-studio__applied-name">
                                {instance.treatment.name}
                              </strong>
                              <small className="effect-studio__applied-description">
                                {instance.customized
                                  ? 'Customized in advanced editing'
                                  : `${instance.effects.length} derived effect${
                                      instance.effects.length === 1 ? '' : 's'
                                    } · curated recipe`}
                              </small>
                            </span>
                            <span className="effect-studio__reorder-actions" title={reorderHint}>
                              <button
                                type="button"
                                disabled={!canMoveUp}
                                onClick={() => moveAppliedTreatment(instance, -1)}
                                aria-label={`Move ${instance.treatment.name} up`}
                              >
                                <SolidIcon name={SOLID_CHROME_ICONS.chevronUp} size="0.65em" />
                              </button>
                              <button
                                type="button"
                                disabled={!canMoveDown}
                                onClick={() => moveAppliedTreatment(instance, 1)}
                                aria-label={`Move ${instance.treatment.name} down`}
                              >
                                <SolidIcon name={SOLID_CHROME_ICONS.chevronDown} size="0.65em" />
                              </button>
                            </span>
                            <button
                              type="button"
                              onClick={() => openAppliedTreatmentTuning(instance)}
                              aria-label={`Tune ${instance.treatment.name}`}
                            >
                              Tune
                            </button>
                            <button
                              type="button"
                              onClick={() => removeAppliedTreatment(instance)}
                              aria-label={`Remove ${instance.treatment.name} treatment`}
                            >
                              Remove
                            </button>
                          </li>
                        );
                      })}
                    </ol>
                  )}
                  {filters.some((filter) => !filter.studioTreatment) && (
                    <p className="effect-studio__stack-note">
                      {filters.filter((filter) => !filter.studioTreatment).length} individual Object
                      Filter
                      {filters.filter((filter) => !filter.studioTreatment).length === 1 ? '' : 's'}{' '}
                      also applied. Open Advanced filter order to edit them.
                    </p>
                  )}
                  <details className="effect-studio__stack-internals">
                    <summary>
                      Advanced filter order · {filters.length} Object Filter
                      {filters.length === 1 ? '' : 's'}
                    </summary>
                    <p>
                      Move an individual derived filter only when you want to customize its named
                      recipe. That recipe remains tracked and can be restored from its settings.
                    </p>
                    <ol
                      className="effect-studio__stack-entries"
                      aria-label="Individual Object Filter order"
                    >
                      {filters.map((filter, index) => {
                        const treatment = filter.studioTreatment
                          ? getEffectStudioTreatment(filter.studioTreatment.treatmentId)
                          : undefined;
                        return (
                          <li key={filter.id}>
                            <span className="effect-studio__stack-order" aria-hidden="true">
                              {index + 1}
                            </span>
                            <span className="effect-studio__stack-summary">
                              <strong>{effectDisplayName(filter.kind)}</strong>
                              <small>
                                {treatment
                                  ? `${treatment.name} · derived step ${(filter.studioTreatment?.effectIndex ?? 0) + 1}`
                                  : 'Individual Object Filter'}
                              </small>
                            </span>
                            <span className="effect-studio__reorder-actions">
                              <button
                                type="button"
                                disabled={index === 0}
                                onClick={() => moveStackEffect(filter, -1)}
                                aria-label={`Move ${effectDisplayName(filter.kind)} up`}
                                title="Move this individual filter and customize its named recipe."
                              >
                                <SolidIcon name={SOLID_CHROME_ICONS.chevronUp} size="0.65em" />
                              </button>
                              <button
                                type="button"
                                disabled={index === filters.length - 1}
                                onClick={() => moveStackEffect(filter, 1)}
                                aria-label={`Move ${effectDisplayName(filter.kind)} down`}
                                title="Move this individual filter and customize its named recipe."
                              >
                                <SolidIcon name={SOLID_CHROME_ICONS.chevronDown} size="0.65em" />
                              </button>
                            </span>
                            {filter.visible === false && <small className="is-muted">Hidden</small>}
                          </li>
                        );
                      })}
                    </ol>
                  </details>
                </>
              ) : (
                <p className="effect-studio__empty">
                  No Object Filters yet. Preview or apply a treatment to start an editable stack.
                </p>
              )}
            </section>

            {tuning && tuningTreatment ? (
              <section
                className="effect-studio__tuning"
                aria-label={`${tuningTreatment.name} settings`}
              >
                <div className="effect-studio__tuning-header">
                  <div>
                    <h3>{tuningTreatment.name} settings</h3>
                    <p>
                      {tuning.instanceId
                        ? 'Tune the curated values directly. The generated Object Filters stay ordered and editable.'
                        : 'Set the intended values here, then preview the real result or add the recipe to the stack.'}
                    </p>
                  </div>
                  <button
                    type="button"
                    onClick={closeTreatmentTuning}
                    aria-label="Close treatment settings"
                  >
                    Close
                  </button>
                </div>
                {tuning.customized && (
                  <p className="effect-studio__customized" role="status">
                    This recipe has advanced edits. Its current appearance is preserved; restoring
                    it will replace just this treatment with its coherent recipe again.
                  </p>
                )}
                <div className="effect-studio__tuning-controls">
                  {studioTreatmentControls(tuningTreatment).map((control) => {
                    const value = tuning.values[control.id] ?? control.defaultValue;
                    return (
                      <div key={control.id}>
                        <span className="effect-studio__control-label">
                          <strong>{control.label}</strong>
                        </span>
                        <RangeValueControl
                          label={`${tuningTreatment.name} ${control.label}`}
                          min={control.min}
                          max={control.max}
                          step={control.step}
                          value={value}
                          unit={control.unit}
                          onRangePointerDown={beginTuningTransaction}
                          onRangePointerUp={finishTuningTransaction}
                          onRangePointerCancel={finishTuningTransaction}
                          onRangeKeyDown={beginTuningTransaction}
                          onRangeKeyUp={finishTuningTransaction}
                          onChange={(next) => setTreatmentControl(control.id, next)}
                        />
                        <small>{control.description}</small>
                      </div>
                    );
                  })}
                </div>
                {tuningTreatment.fixedSettings && tuningTreatment.fixedSettings.length > 0 && (
                  <section
                    className="effect-studio__fixed-settings"
                    aria-label={`${tuningTreatment.name} recipe configuration`}
                  >
                    <h4>Recipe configuration</h4>
                    <dl>
                      {tuningTreatment.fixedSettings.map((setting) => (
                        <div key={setting.label}>
                          <dt>{setting.label}</dt>
                          <dd>{setting.value}</dd>
                        </div>
                      ))}
                    </dl>
                    <p>
                      Change these categorical settings in Advanced filter order. That preserves the
                      result and marks this named recipe as customized.
                    </p>
                  </section>
                )}
                <details className="effect-studio__recipe-details" open>
                  <summary>
                    Derived Object Filters · {selectedRecipeSteps.length} step
                    {selectedRecipeSteps.length === 1 ? '' : 's'}
                  </summary>
                  <ol>
                    {selectedRecipeSteps.map((step) => (
                      <li key={`${step.effectIndex}-${step.kind}`}>
                        <strong>{effectDisplayName(step.kind)}</strong>
                        {step.controlledValues.length > 0 ? (
                          <ul>
                            {step.controlledValues.map((value) => (
                              <li key={`${value.label}-${value.parameter}`}>
                                {value.label} to {value.parameter}: {formatRecipeValue(value.value)}
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <small>Uses the recipe default values.</small>
                        )}
                      </li>
                    ))}
                  </ol>
                </details>
                <div className="effect-studio__tuning-actions">
                  {!tuning.instanceId && (
                    <button
                      type="button"
                      onClick={() => previewTreatment(tuningTreatment, tuning.values)}
                      disabled={!canPreview || preview?.treatmentId === tuningTreatment.id}
                    >
                      {preview?.treatmentId === tuningTreatment.id ? 'Previewing' : 'Preview'}
                    </button>
                  )}
                  {!tuning.instanceId && (
                    <button
                      type="button"
                      className="effect-studio__add"
                      onClick={() => applyTreatment(tuningTreatment, tuning.values)}
                    >
                      {preview?.treatmentId === tuningTreatment.id
                        ? 'Keep treatment'
                        : 'Add to stack'}
                    </button>
                  )}
                  {tuning.instanceId && (
                    <button type="button" onClick={resetTreatmentControls}>
                      Reset controls
                    </button>
                  )}
                  {tuning.instanceId && tuning.customized && (
                    <button
                      type="button"
                      className="effect-studio__add"
                      onClick={restoreAppliedTreatment}
                    >
                      Restore recipe
                    </button>
                  )}
                </div>
              </section>
            ) : (
              <p className="effect-studio__settings-empty">
                Select <strong>Adjust</strong> on a treatment to expose its curated controls and
                direct numeric values.
              </p>
            )}

            {previewing && (
              <div className="effect-studio__preview-status" role="status" aria-live="polite">
                <span>
                  Previewing <strong>{preview.name}</strong>. The comparison above is generated from
                  the same live Object Filter stack.
                </span>
                <button type="button" onClick={() => cancelPreview()}>
                  Cancel preview
                </button>
              </div>
            )}
          </aside>

          <div className="effect-studio__browser">
            <label className="effect-studio__search-label">
              <span className="sr-only">Search treatments</span>
              <input
                type="search"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search treatments"
                aria-label="Search treatments"
              />
            </label>

            <div
              className="effect-studio__filters"
              role="toolbar"
              aria-label="Treatment gallery filters"
            >
              <button
                type="button"
                className={!category && !favoritesOnly ? 'is-selected' : ''}
                aria-pressed={!category && !favoritesOnly}
                onClick={() => {
                  setCategory(undefined);
                  setFavoritesOnly(false);
                }}
              >
                All
              </button>
              <button
                type="button"
                className={favoritesOnly ? 'is-selected' : ''}
                aria-pressed={favoritesOnly}
                onClick={() => {
                  setFavoritesOnly(true);
                  setCategory(undefined);
                }}
              >
                Saved
              </button>
              {EFFECT_STUDIO_CATEGORIES.map((entry) => (
                <button
                  type="button"
                  key={entry.id}
                  className={category === entry.id ? 'is-selected' : ''}
                  aria-pressed={category === entry.id}
                  onClick={() => {
                    setCategory(entry.id);
                    setFavoritesOnly(false);
                  }}
                >
                  {entry.label}
                </button>
              ))}
            </div>

            {recentTreatments.length > 0 && !query && !category && !favoritesOnly && (
              <fieldset className="effect-studio__recent">
                <legend>Recent treatments</legend>
                {recentTreatments.map((treatment) => (
                  <button
                    type="button"
                    key={treatment.id}
                    onClick={() => previewTreatment(treatment)}
                    disabled={!canPreview || preview?.treatmentId === treatment.id}
                    aria-label={`Preview ${treatment.name}`}
                  >
                    {treatment.name}
                  </button>
                ))}
              </fieldset>
            )}

            <section className="effect-studio__gallery" aria-label="Treatment Gallery">
              {groups.map((group) => (
                <section className="effect-studio__treatment-group" key={group.id}>
                  <div className="effect-studio__treatment-group-header">
                    <h4>{group.label}</h4>
                    <p>{group.description}</p>
                  </div>
                  <ul className="effect-studio__treatment-grid">
                    {group.treatments.map((treatment) => {
                      const isFavorite = favorites.includes(treatment.id);
                      const isPreview = preview?.treatmentId === treatment.id;
                      return (
                        <li className={isPreview ? 'is-previewing' : ''} key={treatment.id}>
                          <div
                            className="effect-studio__treatment-art"
                            data-treatment-art={treatment.art}
                            data-treatment-category={treatment.categoryId}
                            aria-hidden="true"
                          />
                          <div className="effect-studio__treatment-copy">
                            <strong>{treatment.name}</strong>
                            <span>{treatment.description}</span>
                            <small>
                              {treatment.effects.length} editable effect
                              {treatment.effects.length === 1 ? '' : 's'} · raster + vector
                            </small>
                          </div>
                          <div className="effect-studio__card-actions">
                            <button
                              type="button"
                              onClick={() => openTreatmentTuning(treatment)}
                              aria-label={`Adjust ${treatment.name} recipe`}
                            >
                              Adjust
                            </button>
                            <button
                              type="button"
                              onClick={() => {
                                openTreatmentTuning(treatment);
                                previewTreatment(treatment);
                              }}
                              disabled={!canPreview || isPreview}
                              aria-label={`Preview ${treatment.name}`}
                            >
                              {isPreview ? 'Previewing' : 'Preview'}
                            </button>
                            <button
                              type="button"
                              className="effect-studio__add"
                              onClick={() => applyTreatment(treatment)}
                              aria-label={`Apply ${treatment.name}`}
                            >
                              {isPreview ? 'Keep' : 'Apply'}
                            </button>
                            <button
                              type="button"
                              className="effect-studio__favorite"
                              aria-pressed={isFavorite}
                              aria-label={
                                isFavorite
                                  ? `Remove ${treatment.name} from saved treatments`
                                  : `Save ${treatment.name}`
                              }
                              onClick={() => toggleFavorite(treatment.id)}
                            >
                              {isFavorite ? 'Saved' : 'Save'}
                            </button>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </section>
              ))}
            </section>
            {treatments.length === 0 && (
              <p className="effect-studio__empty" role="status">
                No treatments match this search. Try a category or clear the query.
              </p>
            )}
          </div>
        </div>

        <details className="effect-studio__primitives">
          <summary>Individual creative effects</summary>
          <p>
            These are raw building blocks, not a second treatment gallery. Tune an applied named
            treatment above to retain its intent. Add one here only when you know the operator you
            need; Object Filters then exposes its parameters, order, mask, and blend. Raw changes to
            a curated treatment are marked Customized rather than silently relabelled. Use Image
            Tuning for photo correction and Adjustment Filters for a scoped backdrop correction.
          </p>
          <ul aria-label="Individual creative effects">
            {primitiveDefinitions.map((definition) => (
              <li key={definition.id}>
                <span>{definition.displayName}</span>
                <button
                  type="button"
                  onClick={() => addPrimitive(definition)}
                  aria-label={`Add ${definition.displayName} primitive to stack`}
                >
                  Add
                </button>
              </li>
            ))}
          </ul>
        </details>

        <div className="effect-studio__looks">
          <div className="effect-studio__looks-header">
            <div>
              <h3>Looks</h3>
              <p>Save an ordered recipe without flattening the artwork.</p>
            </div>
            <button type="button" onClick={saveLook} disabled={filters.length === 0}>
              Save current stack
            </button>
          </div>
          <label>
            <span>Look name</span>
            <input value={lookName} onChange={(event) => setLookName(event.target.value)} />
          </label>
          {looks.length > 0 ? (
            <ul aria-label="Saved Looks">
              {looks.map((look) => (
                <li key={look.id}>
                  <span>
                    <strong>{look.name}</strong>
                    <small>
                      {look.effects.length} effect{look.effects.length === 1 ? '' : 's'}
                    </small>
                  </span>
                  <button
                    type="button"
                    onClick={() => applyLook(look)}
                    aria-label={`Apply Look ${look.name}`}
                  >
                    Apply
                  </button>
                  <button
                    type="button"
                    onClick={() => deleteLook(look.id)}
                    aria-label={`Delete Look ${look.name}`}
                  >
                    Delete
                  </button>
                </li>
              ))}
            </ul>
          ) : (
            <p className="effect-studio__empty">No Looks saved in this document.</p>
          )}
        </div>

        <p className="effect-studio__stack-note">
          Effect Studio owns named treatment settings and applied-recipe management. Its recipes are
          still ordered editable Object Filter entries, so stacking never flattens raster source or
          converts vector geometry. Image Tuning is for image-local photographic work, while
          Adjustment Filters correct a scoped backdrop.
        </p>
      </div>
    </EffectStudioSurface>
  );
}
