/**
 * Photoshop `.grd` parser tests using generated clean-room fixtures.
 *
 * Fixture provenance: all fixtures are generated by `testFixtures.ts`, a
 * clean-room writer that mirrors the documented `.grd` layouts (Adobe PSD
 * spec descriptor format + the classic fixed-layout "Gradient Set" docs).
 * No proprietary Adobe presets are shipped.
 */
import { describe, expect, it } from 'vitest';
import { GrdError } from './descriptor';
import { detectGrdFamily, parsePhotoshopGrd } from './photoshopGrd';
import { buildLegacyGrd, buildModernGrd, type FixtureGradientSpec } from './testFixtures';

const twoStop: FixtureGradientSpec = {
  name: 'Black to White',
  colorStops: [
    { position: 0, color: [0, 0, 0, 255] },
    { position: 1, color: [255, 255, 255, 255] },
  ],
};

describe('detectGrdFamily', () => {
  it('detects descriptor and legacy signatures', () => {
    expect(detectGrdFamily(buildModernGrd([twoStop]))).toBe('descriptor');
    expect(detectGrdFamily(buildLegacyGrd([twoStop]))).toBe('legacy');
    expect(detectGrdFamily(new Uint8Array([1, 2, 3]))).toBeNull();
  });
});

describe('parsePhotoshopGrd (descriptor format)', () => {
  it('parses a simple two-stop gradient', () => {
    const { gradients, warnings } = parsePhotoshopGrd(buildModernGrd([twoStop]));
    expect(gradients).toHaveLength(1);
    expect(gradients[0]!.name).toBe('Black to White');
    expect(gradients[0]!.colorStops).toHaveLength(2);
    expect(gradients[0]!.colorStops[0]!.color).toEqual([0, 0, 0, 255]);
    expect(gradients[0]!.colorStops[1]!.color).toEqual([255, 255, 255, 255]);
    expect(gradients[0]!.colorStops[0]!.position).toBeCloseTo(0, 5);
    expect(gradients[0]!.colorStops[1]!.position).toBeCloseTo(1, 5);
    expect(gradients[0]!.sourceVersion).toBe('descriptor');
    expect(warnings).toEqual([]);
  });

  it('parses multiple gradients in one file', () => {
    const file = buildModernGrd([
      twoStop,
      {
        name: 'Sunset',
        colorStops: [
          { position: 0, color: [255, 0, 0, 255] },
          { position: 1, color: [0, 0, 255, 255] },
        ],
      },
      {
        name: 'Green ramp',
        colorStops: [
          { position: 0, color: [0, 255, 0, 255] },
          { position: 0.5, color: [0, 128, 0, 255] },
          { position: 1, color: [0, 60, 0, 255] },
        ],
      },
    ]);
    const { gradients } = parsePhotoshopGrd(file);
    expect(gradients).toHaveLength(3);
    expect(gradients.map((g) => g.name)).toEqual(['Black to White', 'Sunset', 'Green ramp']);
    expect(gradients[2]!.colorStops).toHaveLength(3);
  });

  it('parses opacity stops and midpoints', () => {
    const file = buildModernGrd([
      {
        name: 'Fade',
        colorStops: [
          { position: 0, color: [0, 0, 0, 255], midpoint: 0.25 },
          { position: 1, color: [255, 255, 255, 255] },
        ],
        opacityStops: [
          { position: 0, opacity: 0 },
          { position: 0.5, opacity: 0.5, midpoint: 0.75 },
          { position: 1, opacity: 1 },
        ],
      },
    ]);
    const { gradients } = parsePhotoshopGrd(file);
    const g = gradients[0]!;
    expect(g.colorStops[0]!.midpoint).toBeCloseTo(0.25, 3);
    expect(g.opacityStops).toHaveLength(3);
    expect(g.opacityStops[0]!.opacity).toBeCloseTo(0, 3);
    expect(g.opacityStops[1]!.opacity).toBeCloseTo(0.5, 3);
    expect(g.opacityStops[1]!.midpoint).toBeCloseTo(0.75, 3);
    expect(g.opacityStops[2]!.opacity).toBeCloseTo(1, 3);
  });

  it('parses multiple color models (RGBC/HSBC/CMYC/Grsc)', () => {
    const file = buildModernGrd([
      {
        name: 'Mixed',
        colorStops: [
          { position: 0, color: [255, 0, 0, 255], colorModel: 'RGBC' },
          {
            position: 0.33,
            color: [255, 128, 0, 255],
            colorModel: 'HSBC',
            raw: { h: 30, s: 100, v: 100 },
          },
          {
            position: 0.66,
            color: [0, 0, 255, 255],
            colorModel: 'CMYC',
            raw: { c: 100, m: 100, y: 0, k: 0 },
          },
          { position: 1, color: [128, 128, 128, 255], colorModel: 'Grsc', raw: { gray: 50 } },
        ],
      },
    ]);
    const { gradients } = parsePhotoshopGrd(file);
    const stops = gradients[0]!.colorStops;
    expect(stops).toHaveLength(4);
    expect(stops[0]!.colorModel).toBe('RGBC');
    expect(stops[1]!.colorModel).toBe('HSBC');
    // HSBC: h=30/360, s=1, v=1 → orange
    expect(stops[1]!.color[0]).toBeGreaterThan(200);
    expect(stops[1]!.color[1]).toBeGreaterThan(60);
    expect(stops[1]!.color[1]).toBeLessThan(200);
    expect(stops[2]!.colorModel).toBe('CMYC');
    expect(stops[3]!.colorModel).toBe('Grsc');
  });

  it('parses smoothness', () => {
    const file = buildModernGrd([{ ...twoStop, name: 'Smooth', smoothness: 0.5 }]);
    const { gradients } = parsePhotoshopGrd(file);
    expect(gradients[0]!.smoothness).toBeCloseTo(0.5, 3);
  });

  it('marks noise gradients read-only with a warning', () => {
    const file = buildModernGrd([{ ...twoStop, name: 'Noise', isNoise: true }]);
    const { gradients, warnings } = parsePhotoshopGrd(file);
    expect(gradients[0]!.isNoise).toBe(true);
    expect(warnings.some((w) => w.toLowerCase().includes('noise'))).toBe(true);
  });

  it('handles unicode and duplicate names', () => {
    const file = buildModernGrd([
      { name: 'Café 名称', colorStops: twoStop.colorStops },
      { name: 'Café 名称', colorStops: twoStop.colorStops },
      { name: '', colorStops: twoStop.colorStops },
    ]);
    const { gradients } = parsePhotoshopGrd(file);
    expect(gradients[0]!.name).toBe('Café 名称');
    expect(gradients[1]!.name).toBe('Café 名称');
    expect(gradients[2]!.name).toBe('');
  });

  it('rejects empty files', () => {
    expect(() => parsePhotoshopGrd(new Uint8Array(0))).toThrow(GrdError);
  });

  it('rejects non-grd signatures', () => {
    expect(() => parsePhotoshopGrd(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]))).toThrow(
      expect.objectContaining({ code: 'invalid-signature' }),
    );
  });

  it('throws truncated for cut-off files', () => {
    const full = buildModernGrd([twoStop]);
    const cut = full.slice(0, Math.floor(full.length / 2));
    expect(() => parsePhotoshopGrd(cut)).toThrow(expect.objectContaining({ code: 'truncated' }));
  });
});

describe('parsePhotoshopGrd (legacy format)', () => {
  it('parses a simple legacy two-stop gradient', () => {
    const { gradients } = parsePhotoshopGrd(buildLegacyGrd([twoStop], 1));
    expect(gradients).toHaveLength(1);
    expect(gradients[0]!.name).toBe('Black to White');
    expect(gradients[0]!.colorStops[0]!.color[0]).toBeCloseTo(0, 0);
    expect(gradients[0]!.colorStops[1]!.color[0]).toBeCloseTo(255, 0);
    expect(gradients[0]!.sourceVersion).toBe('legacy');
  });

  it('parses legacy version 2 with smoothness', () => {
    const { gradients } = parsePhotoshopGrd(buildLegacyGrd([{ ...twoStop, smoothness: 0.5 }], 2));
    expect(gradients[0]!.smoothness).toBeCloseTo(0.5, 2);
  });
});

describe('adversarial inputs', () => {
  it('never hangs or crashes on garbage', () => {
    const cases = [
      new Uint8Array(16),
      new Uint8Array(Array.from({ length: 128 }, (_, i) => (i * 7) % 256)),
      buildModernGrd([twoStop]).slice(0, 8),
      new Uint8Array([0x38, 0x42, 0x47, 0x52, 0xff, 0xff, 0xff, 0xff]),
    ];
    for (const c of cases) {
      expect(() => parsePhotoshopGrd(c)).not.toThrow(RangeError);
      expect(() => parsePhotoshopGrd(c)).not.toThrow(TypeError);
    }
  });
});
