# These are supported funding model platforms

github: K-Arthur
# ko_fi: # your Ko-fi username, if you add one later
# buy_me_a_coffee: # your Buy Me a Coffee username, if you add one later
# open_collective: # your Open Collective slug, if you add one later
# custom: ["https://example.com/donate"]
