export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'color-no-hex': true,
    'color-named': null,
    'alpha-value-notation': null,
    'lightness-notation': null,
    'hue-degree-notation': null,
    'value-keyword-case': null,
    'comment-empty-line-before': null,
    'declaration-empty-line-before': null,
    'rule-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'declaration-block-no-duplicate-custom-properties': null,
    'length-zero-no-unit': null,
    'selector-class-pattern': [
      '^[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*(__[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*)?(--[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*)?$',
      {
        resolveNestedSelectors: true,
        message: 'Expected BEM-style class naming',
        severity: 'warning',
      },
    ],
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'no-descending-specificity': null,
    'custom-property-empty-line-before': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'no-duplicate-selectors': null,
    'media-feature-range-notation': null,
    'declaration-block-no-redundant-longhand-properties': null,
  },
  ignoreFiles: [
    'node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/.worktrees/**',
    'apps/desktop/public/**',
    'apps/website/dist/**',
    'packages/engine/src/__goldens__/**',
    'packages/ui/src/components/StartupLoader.css',
  ],
};
