import type { MenuBuildHelpers, MenuBuildState, MenuItem } from './types';

export function buildArrangeMenu(
  _state: MenuBuildState,
  helpers: MenuBuildHelpers,
): MenuItem[] {
  return [
    {
      label: 'Bring to Front',
      shortcut: helpers.fmt('bringFront'),
      ariaKeyshortcut: helpers.ks('bringFront'),
      action: 'bringFront',
      disabled: helpers.dis('bringFront'),
    },
    {
      label: 'Bring Forward',
      shortcut: helpers.fmt('bringForward'),
      ariaKeyshortcut: helpers.ks('bringForward'),
      action: 'bringForward',
      disabled: helpers.dis('bringForward'),
    },
    {
      label: 'Send Backward',
      shortcut: helpers.fmt('sendBackward'),
      ariaKeyshortcut: helpers.ks('sendBackward'),
      action: 'sendBackward',
      disabled: helpers.dis('sendBackward'),
    },
    {
      label: 'Send to Back',
      shortcut: helpers.fmt('sendBack'),
      ariaKeyshortcut: helpers.ks('sendBack'),
      action: 'sendBack',
      disabled: helpers.dis('sendBack'),
    },
    { label: '---' },
    {
      label: 'Align',
      disabled: helpers.dis('alignLeft'),
      items: [
        {
          label: 'Align Left',
          shortcut: helpers.fmt('alignLeft'),
          ariaKeyshortcut: helpers.ks('alignLeft'),
          action: 'alignLeft',
          disabled: helpers.dis('alignLeft'),
        },
        {
          label: 'Align Horizontal Center',
          shortcut: helpers.fmt('alignCenterH'),
          ariaKeyshortcut: helpers.ks('alignCenterH'),
          action: 'alignCenterH',
          disabled: helpers.dis('alignCenterH'),
        },
        {
          label: 'Align Right',
          shortcut: helpers.fmt('alignRight'),
          ariaKeyshortcut: helpers.ks('alignRight'),
          action: 'alignRight',
          disabled: helpers.dis('alignRight'),
        },
        { label: '---' },
        {
          label: 'Align Top',
          shortcut: helpers.fmt('alignTop'),
          ariaKeyshortcut: helpers.ks('alignTop'),
          action: 'alignTop',
          disabled: helpers.dis('alignTop'),
        },
        {
          label: 'Align Vertical Center',
          shortcut: helpers.fmt('alignCenterV'),
          ariaKeyshortcut: helpers.ks('alignCenterV'),
          action: 'alignCenterV',
          disabled: helpers.dis('alignCenterV'),
        },
        {
          label: 'Align Bottom',
          shortcut: helpers.fmt('alignBottom'),
          ariaKeyshortcut: helpers.ks('alignBottom'),
          action: 'alignBottom',
          disabled: helpers.dis('alignBottom'),
        },
        { label: '---' },
        {
          label: 'Distribute Horizontally',
          shortcut: helpers.fmt('distributeHorizontal'),
          ariaKeyshortcut: helpers.ks('distributeHorizontal'),
          action: 'distributeHorizontal',
          disabled: helpers.dis('distributeHorizontal'),
        },
        {
          label: 'Distribute Vertically',
          shortcut: helpers.fmt('distributeVertical'),
          ariaKeyshortcut: helpers.ks('distributeVertical'),
          action: 'distributeVertical',
          disabled: helpers.dis('distributeVertical'),
        },
        { label: '---' },
        {
          label: 'Tidy Up',
          action: 'tidySelected',
          disabled: helpers.dis('tidySelected'),
        },
      ],
    },
    {
      label: 'Harmonize Spacing',
      shortcut: helpers.fmt('harmonizeSpacing'),
      ariaKeyshortcut: helpers.ks('harmonizeSpacing'),
      action: 'harmonizeSpacing',
      disabled: helpers.dis('harmonizeSpacing'),
    },
    { label: '---' },
    {
      label: 'Nudge Left',
      shortcut: helpers.fmt('nudgeLeft'),
      ariaKeyshortcut: helpers.ks('nudgeLeft'),
      action: 'nudgeLeft',
      disabled: helpers.dis('nudgeLeft'),
    },
    {
      label: 'Nudge Right',
      shortcut: helpers.fmt('nudgeRight'),
      ariaKeyshortcut: helpers.ks('nudgeRight'),
      action: 'nudgeRight',
      disabled: helpers.dis('nudgeRight'),
    },
    {
      label: 'Nudge Up',
      shortcut: helpers.fmt('nudgeUp'),
      ariaKeyshortcut: helpers.ks('nudgeUp'),
      action: 'nudgeUp',
      disabled: helpers.dis('nudgeUp'),
    },
    {
      label: 'Nudge Down',
      shortcut: helpers.fmt('nudgeDown'),
      ariaKeyshortcut: helpers.ks('nudgeDown'),
      action: 'nudgeDown',
      disabled: helpers.dis('nudgeDown'),
    },
  ];
}
