import type { MenuBuildHelpers, MenuBuildState, MenuItem } from './types';

export function buildObjectMenu(_state: MenuBuildState, helpers: MenuBuildHelpers): MenuItem[] {
  return [
    {
      label: 'Group',
      shortcut: helpers.fmt('group'),
      ariaKeyshortcut: helpers.ks('group'),
      action: 'group',
      disabled: helpers.dis('group'),
    },
    {
      label: 'Ungroup',
      shortcut: helpers.fmt('ungroup'),
      ariaKeyshortcut: helpers.ks('ungroup'),
      action: 'ungroup',
      disabled: helpers.dis('ungroup'),
    },
    { label: '---' },
    {
      label: 'Flip Horizontal',
      shortcut: helpers.fmt('flipH'),
      ariaKeyshortcut: helpers.ks('flipH'),
      action: 'flipH',
      disabled: helpers.dis('bringFront'),
    },
    {
      label: 'Flip Vertical',
      shortcut: helpers.fmt('flipV'),
      ariaKeyshortcut: helpers.ks('flipV'),
      action: 'flipV',
      disabled: helpers.dis('bringFront'),
    },
    { label: '---' },
    {
      label: 'New Adjustment Layer',
      shortcut: helpers.fmt('newAdjustmentLayer'),
      ariaKeyshortcut: helpers.ks('newAdjustmentLayer'),
      action: 'newAdjustmentLayer',
    },
    {
      label: 'Create Clipping Mask',
      shortcut: helpers.fmt('createClippingMask'),
      ariaKeyshortcut: helpers.ks('createClippingMask'),
      action: 'createClippingMask',
      disabled: helpers.dis('createClippingMask'),
    },
    {
      label: 'Release Clipping Mask',
      shortcut: helpers.fmt('releaseClippingMask'),
      ariaKeyshortcut: helpers.ks('releaseClippingMask'),
      action: 'releaseClippingMask',
      disabled: helpers.dis('releaseClippingMask'),
    },
    { label: '---' },
    {
      label: 'Remove Background...',
      action: 'batchBgRemove',
      disabled: helpers.dis('batchBgRemove'),
    },
    {
      label: 'Crop Image',
      shortcut: helpers.fmt('toolCrop'),
      ariaKeyshortcut: helpers.ks('toolCrop'),
      action: 'toolCrop',
      disabled: helpers.dis('toolCrop'),
    },
    {
      label: 'Extract Palette',
      action: 'extractPalette',
      disabled: helpers.dis('extractPalette'),
    },
    { label: '---' },
    { label: 'Add Alpha Mask', action: 'addAlphaMask', disabled: helpers.dis('addAlphaMask') },
    { label: 'Add Clip Mask', action: 'addClipMask', disabled: helpers.dis('addClipMask') },
    {
      label: 'Add Luminance Mask',
      action: 'addLuminanceMask',
      disabled: helpers.dis('addLuminanceMask'),
    },
    { label: 'Remove Mask', action: 'removeMask', disabled: helpers.dis('removeMask') },
    { label: 'Toggle Mask', action: 'toggleMask', disabled: helpers.dis('toggleMask') },
    { label: 'Invert Mask', action: 'invertMask', disabled: helpers.dis('invertMask') },
    { label: '---' },
    {
      label: 'Flatten Selection',
      shortcut: helpers.fmt('flattenSelection'),
      ariaKeyshortcut: helpers.ks('flattenSelection'),
      action: 'flattenSelection',
      disabled: helpers.dis('flattenSelection'),
    },
    {
      label: 'Rasterize',
      action: 'rasterizeSelection',
      disabled: helpers.dis('rasterizeSelection'),
    },
    {
      label: 'Merge Selected Layers',
      action: 'mergeSelected',
      disabled: helpers.dis('mergeSelected'),
    },
    { label: '---' },
    {
      label: 'Union',
      shortcut: helpers.fmt('booleanUnion'),
      ariaKeyshortcut: helpers.ks('booleanUnion'),
      action: 'booleanUnion',
      disabled: helpers.dis('booleanUnion'),
    },
    {
      label: 'Subtract',
      shortcut: helpers.fmt('booleanSubtract'),
      ariaKeyshortcut: helpers.ks('booleanSubtract'),
      action: 'booleanSubtract',
      disabled: helpers.dis('booleanSubtract'),
    },
    {
      label: 'Intersect',
      shortcut: helpers.fmt('booleanIntersect'),
      ariaKeyshortcut: helpers.ks('booleanIntersect'),
      action: 'booleanIntersect',
      disabled: helpers.dis('booleanIntersect'),
    },
    {
      label: 'Exclude',
      shortcut: helpers.fmt('booleanExclude'),
      ariaKeyshortcut: helpers.ks('booleanExclude'),
      action: 'booleanExclude',
      disabled: helpers.dis('booleanExclude'),
    },
    { label: '---' },
    { label: 'Audit', action: 'runAudit', disabled: helpers.dis('runAudit') },
    { label: 'Scan for Debt', action: 'scanDebt', disabled: helpers.dis('scanDebt') },
    { label: 'Suggest Names', action: 'suggestNames', disabled: helpers.dis('suggestNames') },
    {
      label: 'Detect Duplicates',
      action: 'detectDuplicates',
      disabled: helpers.dis('detectDuplicates'),
    },
  ];
}
