/**
 * Generates packages/ui/src/tokens/tokens.css from the audited TS source.
 *
 * Single source of truth: color.ts (audited) → this script → tokens.css.
 * Run: `tsx scripts/generate-token-css.ts` (re-run when color.ts changes).
 *
 * Emits:
 *   - :root                      → light defaults (the default theme)
 *   - [data-theme="dark"]        → dark overrides (explicit in-app choice wins)
 *   - [data-theme="high-contrast"]
 *   - @media prefers-color-scheme: dark  → dark when no explicit [data-theme]
 *   - @media prefers-reduced-motion      → durations collapse to 0
 *   - @media forced-colors: active       → high-contrast honoring system colors
 */
import { writeFileSync } from 'node:fs';
import { SEMANTIC, type THEMES } from '../src/tokens/color';
import { toHex } from '../src/tokens/contrast';

const kebab = (s: string) => s.replace(/_/g, '-');

function colorBlock(theme: string): string {
  const palette = SEMANTIC[theme as (typeof THEMES)[number]];
  const lines = Object.entries(palette).map(
    ([token, rgb]) => `  --color-${kebab(token)}: ${toHex(rgb)};`,
  );
  return lines.join('\n');
}

const NON_COLOR = `
  /* --- Typography --- */
  /* First pass uses offline-safe system stacks. Real font files (display + body)
     with font-display: swap + subset/unicode-range land in task 0.4/0.9. */
  --font-display: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --font-body: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --font-mono: ui-monospace, "SF Mono", "Cascadia Code", "JetBrains Mono", Consolas, monospace;
  --font-weight-regular: 400;
  --font-weight-medium: 500;
  --font-weight-semibold: 600;
  --font-weight-bold: 700;
  --font-line-tight: 1.15;
  --font-line-normal: 1.5;
  --font-line-relaxed: 1.65;
  /* Fluid modular scale (clamp). */
  --font-size-xs: clamp(0.72rem, 0.70rem + 0.10vw, 0.78rem);
  --font-size-sm: clamp(0.83rem, 0.80rem + 0.15vw, 0.92rem);
  --font-size-md: clamp(0.95rem, 0.91rem + 0.20vw, 1.06rem);
  --font-size-lg: clamp(1.08rem, 1.02rem + 0.30vw, 1.25rem);
  --font-size-xl: clamp(1.25rem, 1.15rem + 0.50vw, 1.55rem);
  --font-size-2xl: clamp(1.50rem, 1.35rem + 0.75vw, 2.00rem);
  --font-size-3xl: clamp(1.85rem, 1.60rem + 1.25vw, 2.65rem);

  /* --- Spacing (4-pt grid, fluid) --- */
  --space-0: 0;
  --space-1: clamp(0.15rem, 0.14rem + 0.05vw, 0.20rem);
  --space-2: clamp(0.30rem, 0.28rem + 0.10vw, 0.40rem);
  --space-3: clamp(0.50rem, 0.47rem + 0.15vw, 0.65rem);
  --space-4: clamp(0.70rem, 0.66rem + 0.20vw, 0.90rem);
  --space-5: clamp(1.00rem, 0.94rem + 0.30vw, 1.30rem);
  --space-6: clamp(1.40rem, 1.31rem + 0.45vw, 1.85rem);
  --space-7: clamp(2.00rem, 1.87rem + 0.65vw, 2.65rem);
  --space-8: clamp(2.80rem, 2.60rem + 1.00vw, 3.80rem);
  /* Component aliases. */
  --toolbar-height: clamp(2.5rem, 2.4rem + 0.5vw, 3rem);
  --topbar-height: clamp(2rem, 1.95rem + 0.25vw, 2.25rem);
  --statusbar-height: clamp(1.5rem, 1.45rem + 0.25vw, 1.75rem);
  --sidebar-width: clamp(14rem, 12rem + 8vw, 18rem);
  --inspector-width: clamp(15rem, 13rem + 8vw, 20rem);

  /* --- Radius --- */
  --radius-sm: 3px;
  --radius-md: 6px;
  --radius-lg: 10px;
  --radius-xl: 16px;
  --radius-pill: 9999px;

  /* --- Shadow --- */
  --shadow-sm: 0 1px 2px rgb(0 0 0 / 0.10);
  --shadow-md: 0 4px 12px rgb(0 0 0 / 0.14);
  --shadow-lg: 0 12px 32px rgb(0 0 0 / 0.20);

  /* --- Motion --- */
  --duration-instant: 60ms;
  --duration-quick: 120ms;
  --duration-base: 200ms;
  --duration-slow: 320ms;
  --ease-standard: cubic-bezier(0.2, 0, 0, 1);
  --ease-emphasized: cubic-bezier(0.3, 0, 0, 1);
  --ease-in-out: cubic-bezier(0.4, 0, 0.2, 1);

  /* --- z-index --- */
  --z-base: 0;
  --z-raised: 10;
  --z-sticky: 100;
  --z-overlay: 1000;
  --z-dialog: 1100;
  --z-toast: 1200;
  --z-tooltip: 1300;

  /* --- Breakpoints (reference values; used in @media, not as custom props) --- */
  --bp-sm: 640px;
  --bp-md: 768px;
  --bp-lg: 1024px;
  --bp-xl: 1280px;
  --bp-2xl: 1536px;
`;

const css = `/* AUTO-GENERATED by packages/ui/scripts/generate-token-css.ts.
 * Do not edit by hand — edit color.ts + this script, then re-run.
 * Strata design tokens (Strata plan §6). Source of truth: src/tokens/color.ts.
 */

:root {
${colorBlock('light')}
${NON_COLOR}
}

[data-theme="dark"] {
${colorBlock('dark')}
}

[data-theme="high-contrast"] {
${colorBlock('high-contrast')}
}

/* Dark via system preference ONLY when no explicit in-app [data-theme] choice. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${colorBlock('dark')}
  }
}

/* High-contrast honors the OS forced-colors mode. */
@media (forced-colors: active) {
  :root:not([data-theme="high-contrast"]) {
${colorBlock('high-contrast')}
  }
}

/* Reduced motion: collapse all motion durations to 0 (Strata plan §4.1). */
@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-instant: 0ms;
    --duration-quick: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
  }
}
`;

writeFileSync(new URL('../src/tokens/tokens.css', import.meta.url), css);
console.log(`tokens.css generated (${css.length} bytes).`);
