/**
 * Build-time HTML extraction for the website search index.
 *
 * The website is 100+ hand-authored Astro pages, so there is no Markdown
 * pipeline to hook into. This module reads the *built* HTML instead — the
 * real output users receive — and does two jobs in one pass over `<main>`:
 *
 *  1. injects stable `id`s on `h2`/`h3` headings so sections are linkable
 *     (the source pages mostly have none), and
 *  2. returns heading-delimited sections (heading + plain text) for the index.
 *
 * It is deliberately a small string processor rather than an HTML parser:
 * the corpus is generated by Astro with predictable structure, there is no
 * new dependency, and every rule here is covered by unit tests and by E2E
 * queries against the real built site.
 */

import type { SearchPage, SearchSection } from './types';

const MAIN_RE = /<main\b([^>]*)>([\s\S]*?)<\/main>/i;

interface HeadingRecord {
  level: number;
  id: string;
  text: string;
  /** Index of the opening `<hN` in the source main HTML. */
  start: number;
  /** Index just past the closing `</hN>` in the source main HTML. */
  end: number;
}

export interface ExtractedPage {
  page: SearchPage;
  /** Full document HTML with heading anchors injected. */
  html: string;
}

const ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
  copy: '\u00A9',
  reg: '\u00AE',
  trade: '\u2122',
  mdash: '\u2014',
  ndash: '\u2013',
  hellip: '\u2026',
  middot: '\u00B7',
  bull: '\u2022',
  lsquo: '\u2018',
  rsquo: '\u2019',
  ldquo: '\u201C',
  rdquo: '\u201D',
  laquo: '\u00AB',
  raquo: '\u00BB',
  rsaquo: '\u203A',
  lsaquo: '\u2039',
  larr: '\u2190',
  rarr: '\u2192',
  uarr: '\u2191',
  darr: '\u2193',
  harr: '\u2194',
  times: '\u00D7',
  divide: '\u00F7',
  minus: '\u2212',
  plusmn: '\u00B1',
  ne: '\u2260',
  le: '\u2264',
  ge: '\u2265',
  asymp: '\u2248',
  infin: '\u221E',
  deg: '\u00B0',
  eacute: '\u00E9',
  Delta: '\u0394',
  delta: '\u03B4',
  pi: '\u03C0',
  lcub: '{',
  rcub: '}',
  lsqb: '[',
  rsqb: ']',
};
// Case-sensitive names resolve exactly; everything else folds to lower case
// so `&AMP;` still decodes while `&Delta;` (U+0394) and `&delta;` (U+03B4)
// stay distinct.
const FOLDED_ENTITIES: Record<string, string> = Object.fromEntries(
  Object.entries(ENTITIES).map(([name, value]) => [name.toLowerCase(), value]),
);

export function decodeEntities(value: string): string {
  return value.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (entity, body: string) => {
    if (body.startsWith('#x') || body.startsWith('#X')) {
      const code = Number.parseInt(body.slice(2), 16);
      return Number.isFinite(code) ? String.fromCodePoint(code) : entity;
    }
    if (body.startsWith('#')) {
      const code = Number.parseInt(body.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : entity;
    }
    return ENTITIES[body] ?? FOLDED_ENTITIES[body.toLowerCase()] ?? entity;
  });
}

/** Named entities that survived decoding, for the build-time integrity report. */
export function findUndecodedEntities(text: string): string[] {
  const found = new Set<string>();
  for (const match of text.matchAll(/&[a-zA-Z][a-zA-Z0-9]*;/g)) found.add(match[0]);
  return [...found];
}

/**
 * Drop `aria-hidden="true"` subtrees.
 *
 * Components pair a screen-reader copy with a decorative copy (for example
 * StatusPill renders `<span class="sr-only">Available</span><span
 * aria-hidden="true">Available</span>`); indexing both duplicates the
 * visible text. The negative lookahead keeps the match inside one element
 * when tags of the same name nest, and a few passes unwind deeper nesting.
 */
function stripAriaHidden(html: string): string {
  let output = html;
  const tags = ['span', 'div', 'i', 'b', 'em', 'strong', 'p', 'small', 'sup', 'sub'];
  for (let pass = 0; pass < 3; pass += 1) {
    let changed = false;
    for (const tag of tags) {
      const pattern = new RegExp(
        `<${tag}\\b[^>]*\\baria-hidden\\s*=\\s*"true"[^>]*>(?:(?!<${tag}\\b)[\\s\\S])*?</${tag}\\s*>`,
        'gi',
      );
      const next = output.replace(pattern, ' ');
      if (next !== output) {
        output = next;
        changed = true;
      }
    }
    if (!changed) break;
  }
  return output;
}

/**
 * Convert a fragment of Astro-generated HTML to plain text.
 *
 * Navigation is dropped entirely: every docs page repeats a breadcrumb
 * inside `<main>`, and indexing it would let the word "docs" match every
 * page. Script/style/svg bodies are never text. Block-level closings become
 * spaces so words on either side of a tag boundary do not fuse.
 */
export function htmlToText(html: string): string {
  return decodeEntities(
    stripAriaHidden(html)
      .replace(/<(script|style|svg|template|nav)\b[^>]*>[\s\S]*?<\/\1\s*>/gi, ' ')
      .replace(/<br\s*\/?>/gi, ' ')
      .replace(
        /<\/(p|li|h[1-6]|tr|td|th|div|section|article|blockquote|pre|table|ul|ol|dl|dd|dt|figure|figcaption|summary|details)\s*>/gi,
        ' ',
      )
      .replace(/<[^>]*>/g, ' '),
  )
    .replace(/\s+/g, ' ')
    .trim();
}

function escapeAttribute(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

/** Heading text -> fragment id. Diacritics folded, punctuation collapsed. */
export function slugifyHeading(text: string): string {
  const base = text
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '');
  return base || 'section';
}

function uniqueSlug(base: string, used: ReadonlySet<string>): string {
  if (!used.has(base)) return base;
  let counter = 2;
  while (used.has(`${base}-${counter}`)) counter += 1;
  return `${base}-${counter}`;
}

/** Every id already present in the document, so generated anchors never collide. */
export function collectIds(html: string): Set<string> {
  const ids = new Set<string>();
  for (const match of html.matchAll(/\bid\s*=\s*"([^"]*)"/gi)) {
    if (match[1]) ids.add(match[1]);
  }
  return ids;
}

/**
 * Inject ids on `h2`/`h3` inside main and split the content into sections.
 *
 * Pre-existing heading ids are preserved verbatim (the docs use a few
 * hand-written anchors for cross-page links). A section is created for the
 * intro text and for every heading; `h4`+ content stays with its parent.
 */
export function extractSections(
  mainHtml: string,
  reservedIds: ReadonlySet<string> = new Set(),
): { html: string; sections: SearchSection[] } {
  const used = new Set(reservedIds);
  const headingRe = /<(h[23])([^>]*)>([\s\S]*?)<\/\1\s*>/gi;
  const parts: string[] = [];
  const headings: HeadingRecord[] = [];
  let cursor = 0;
  let match: RegExpExecArray | null = headingRe.exec(mainHtml);

  while (match !== null) {
    const full = match[0];
    const level = Number(match[1].slice(1));
    const attributes = match[2];
    const inner = match[3];
    const text = htmlToText(inner);
    const existing = /\bid\s*=\s*"([^"]*)"/i.exec(attributes);
    let id = existing?.[1]?.trim() ?? '';
    let attributesWithId = attributes;
    if (id) {
      used.add(id);
    } else {
      id = uniqueSlug(slugifyHeading(text), used);
      used.add(id);
      attributesWithId = `${attributes} id="${escapeAttribute(id)}"`;
    }
    parts.push(mainHtml.slice(cursor, match.index));
    parts.push(`<h${level}${attributesWithId}>`, inner, `</h${level}>`);
    cursor = match.index + full.length;
    headings.push({
      level,
      id,
      text,
      start: match.index,
      end: match.index + full.length,
    });
    match = headingRe.exec(mainHtml);
  }
  parts.push(mainHtml.slice(cursor));

  const sections: SearchSection[] = [];
  const introEnd = headings.length > 0 ? headings[0].start : mainHtml.length;
  const intro = htmlToText(mainHtml.slice(0, introEnd));
  if (intro) sections.push({ heading: '', anchor: '', text: intro });
  headings.forEach((heading, index) => {
    const bodyEnd = headings[index + 1]?.start ?? mainHtml.length;
    sections.push({
      heading: heading.text,
      anchor: heading.id,
      text: htmlToText(mainHtml.slice(heading.end, bodyEnd)),
    });
  });

  return { html: parts.join(''), sections };
}

/**
 * A page-level title for results.
 *
 * The homepage headline is rendered by an animated component that repeats
 * its text once per animation layer, so a repeated-sentence `h1` (or an
 * over-long one) is treated as unreliable and the `<title>` is preferred.
 */
const MAX_TITLE_LENGTH = 80;

function isUnreliableHeadline(text: string): boolean {
  if (text.length > MAX_TITLE_LENGTH) return true;
  const counts = new Map<string, number>();
  for (const sentence of text.split(/(?<=[.!?])\s+/)) {
    const key = sentence.trim().toLowerCase();
    if (!key) continue;
    const next = (counts.get(key) ?? 0) + 1;
    if (next >= 2) return true;
    counts.set(key, next);
  }
  return false;
}

function extractTitle(html: string, mainHtml: string): string {
  const h1 = /<h1\b[^>]*>([\s\S]*?)<\/h1\s*>/i.exec(mainHtml);
  const h1Text = h1 ? htmlToText(h1[1]) : '';
  if (h1Text && !isUnreliableHeadline(h1Text)) return h1Text;
  const title = /<title\b[^>]*>([\s\S]*?)<\/title\s*>/i.exec(html);
  const titleText = title
    ? decodeEntities(title[1])
        .replace(/\s*[—|]\s*Varve(\s+Docs)?\s*$/i, '')
        .trim()
    : '';
  if (titleText) return titleText;
  return h1Text.slice(0, MAX_TITLE_LENGTH).trim();
}

function extractDescription(html: string): string {
  const meta = /<meta\b[^>]*name\s*=\s*"description"[^>]*>/i.exec(html);
  if (!meta) return '';
  const content = /\bcontent\s*=\s*"([^"]*)"/i.exec(meta[0]);
  return content ? decodeEntities(content[1]).trim() : '';
}

/** Normalize a route for the index: no trailing slash, root stays `/`. */
export function normalizeRoute(url: string): string {
  if (!url || url === '/') return '/';
  return url.replace(/\/+$/, '');
}

/**
 * Extract one built page. Returns `null` for documents without `<main>`
 * (utility/endpoint output), which the indexer skips.
 */
export function extractPage(html: string, url: string): ExtractedPage | null {
  const main = MAIN_RE.exec(html);
  if (!main) return null;
  const mainHtml = main[2];
  const reserved = collectIds(html);
  const transformed = extractSections(mainHtml, reserved);
  const mainIndex = mainHtml.length > 0 ? main[0].indexOf(mainHtml) : -1;
  const rebuiltMain =
    mainIndex >= 0
      ? main[0].slice(0, mainIndex) + transformed.html + main[0].slice(mainIndex + mainHtml.length)
      : main[0];
  const page: SearchPage = {
    url: normalizeRoute(url),
    title: extractTitle(html, mainHtml),
    description: extractDescription(html),
    sections: transformed.sections,
  };
  return {
    page,
    html: html.slice(0, main.index) + rebuiltMain + html.slice(main.index + main[0].length),
  };
}
