/**
 * Shared types for the website's build-time search index.
 *
 * The index is generated by `scripts/search-index.mjs` in the
 * `astro:build:done` hook and fetched lazily by SearchDialog.astro. The
 * contract is versioned so a stale cached index can be rejected rather than
 * misread.
 */

export const SEARCH_INDEX_VERSION = 1 as const;

/** One heading-delimited region of a page. */
export interface SearchSection {
  /** Visible heading text (`''` for the intro before the first heading). */
  heading: string;
  /** Fragment id of the heading, without `#`; `''` when the section has none. */
  anchor: string;
  /** Plain text of the section body with markup removed. */
  text: string;
}

export interface SearchPage {
  /** Site-relative route, base path included, no trailing slash (except `/`). */
  url: string;
  /** Page title used in results. */
  title: string;
  /** Meta description, used as a weak relevance signal. */
  description: string;
  sections: SearchSection[];
}

export interface SearchIndex {
  version: typeof SEARCH_INDEX_VERSION;
  pages: SearchPage[];
}

export interface SearchResult {
  /** Route plus section fragment when the match lands in a section. */
  url: string;
  /** Page title. */
  title: string;
  /** Matching section heading (`''` for the page intro). */
  heading: string;
  /** Plain-text excerpt around the first match. */
  snippet: string;
  score: number;
}
