/**
 * @varve/ui/icons — typed `<Icon>` + curated icon maps.
 *
 * The `Icon` primitive is the only graphics path for UI affordances (Strata
 * plan §4.4: zero emoji, SVG via Lucide only). Curated maps group icons by
 * surface so toolbars/menus get a stable, reviewable name set.
 *
 * `SolidIcon` provides filled-style icons via Phosphor Icons for the design
 * system refresh, coexisting with the Lucide-based `<Icon>`.
 */

export type { IconName, IconProps } from './Icon';
export { Icon } from './Icon';
export type { SolidIconName, SolidIconProps } from './SolidIcon';
export { SolidIcon } from './SolidIcon';
/** Semantic icon registry — the canonical API for internal UI icons. */
export type {
  IconFamily,
  IconSizeToken,
  SemanticIconEntry,
  SemanticIconName,
  SemanticIconProps,
  SemanticIconViolation,
} from './semantic';
export {
  DIRECTIONAL_ICONS,
  ICON_SIZE_TOKENS,
  isDirectionalIcon,
  resolveSemanticIcon,
  SEMANTIC_ICONS,
  SemanticIcon,
  validateSemanticIconNames,
} from './semantic';
export type { VarveLogoProps } from './VarveLogo';
export { VarveLogo } from './VarveLogo';

import type { IconName } from './Icon';
import type { SolidIconName } from './SolidIcon';

/** Toolbar / tool set (Strata plan §5.3). */
export const TOOL_ICONS = {
  select: 'MousePointer2',
  frame: 'Frame',
  rect: 'Square',
  ellipse: 'Circle',
  polygon: 'Pentagon',
  star: 'Star',
  line: 'Minus',
  pen: 'Pen',
  pencil: 'Pencil',
  text: 'Type',
  image: 'Image',
  component: 'Component',
  group: 'Group',
  union: 'Combine',
  subtract: 'Diff',
  slice: 'Scissors',
  hand: 'Hand',
  zoomIn: 'ZoomIn',
  zoom: 'ZoomIn',
  arrow: 'ArrowRight',
  nodeEdit: 'Pointer',
  scale: 'Maximize2',
  eyedropper: 'Pipette',
  booleanUnion: 'Combine',
  booleanSubtract: 'Diff',
  booleanIntersect: 'Combine',
  booleanExclude: 'Diff',
  inspect: 'SearchCode',
  paint: 'Brush',
  eraser: 'Eraser',
  cloneStamp: 'Stamp',
  crop: 'Crop',
  healBrush: 'Bandage',
  spotHeal: 'Wand',
  patch: 'SquareStack',
  refineMask: 'Paintbrush',
  trimapEdit: 'Paintbrush',
  adjustment: 'SlidersHorizontal',
  smudge: 'Fingerprint',
  sam2Segment: 'Scan',
  lasso: 'LassoSelect',
  table: 'Table',
  warp: 'Grid3x3',
} as const satisfies Record<string, IconName>;

/** Filled-style tool icons (design system refresh — replaces outline TOOL_ICONS). */
export const SOLID_TOOL_ICONS = {
  select: 'Cursor',
  frame: 'FrameCorners',
  rect: 'Square',
  ellipse: 'Circle',
  polygon: 'Triangle',
  star: 'Star',
  line: 'Minus',
  pen: 'Pen',
  pencil: 'PencilSimple',
  text: 'TextT',
  image: 'Image',
  component: 'PuzzlePiece',
  group: 'Folder',
  union: 'ArrowsOut',
  subtract: 'CaretLeft',
  slice: 'Scissors',
  hand: 'Hand',
  zoomIn: 'MagnifyingGlassPlus',
  zoom: 'MagnifyingGlassPlus',
  arrow: 'ArrowUpRight',
  nodeEdit: 'Cursor',
  scale: 'ArrowsOut',
  eyedropper: 'Eyedropper',
  booleanUnion: 'ArrowsOut',
  booleanSubtract: 'Minus',
  booleanIntersect: 'ArrowsIn',
  booleanExclude: 'XCircle',
  inspect: 'MagnifyingGlass',
  paint: 'PaintBrush',
  eraser: 'Eraser',
  cloneStamp: 'Stamp',
  healBrush: 'PaintBrush',
  spotHeal: 'PaintBrush',
  patch: 'SelectionBackground',
  refineMask: 'Paintbrush',
  trimapEdit: 'Paintbrush',
  adjustment: 'Faders',
  smudge: 'Fingerprint',
  sam2Segment: 'MagnifyingGlass',
  lasso: 'SelectionForeground',
  table: 'Table',
  warp: 'GridFour',
} as const satisfies Record<string, SolidIconName>;

/** General chrome icons. */
export const CHROME_ICONS = {
  menu: 'Menu',
  close: 'X',
  chevronDown: 'ChevronDown',
  chevronUp: 'ChevronUp',
  chevronRight: 'ChevronRight',
  check: 'Check',
  visibility: 'Eye',
  visibilityOff: 'EyeOff',
  lock: 'Lock',
  unlock: 'LockOpen',
  search: 'Search',
  settings: 'Settings',
  plus: 'Plus',
  trash: 'Trash2',
  spinner: 'LoaderCircle',
  clock: 'Clock',
  history: 'History',
  pin: 'Pin',
  pinOff: 'PinOff',
  fileText: 'FileText',
  folder: 'Folder',
  folderOpen: 'FolderOpen',
  filter: 'Filter',
  layoutGrid: 'LayoutGrid',
  list: 'List',
  ellipsis: 'Ellipsis',
  rotateCcw: 'RotateCcw',
  upload: 'Upload',
  download: 'Download',
  star: 'Star',
  archive: 'Archive',
  copy: 'Copy',
  externalLink: 'ExternalLink',
  inspect: 'SearchCode',
  ruler: 'Ruler',
  code: 'Code',
  palette: 'Palette',
  maximize: 'Maximize',
  crosshair: 'Crosshair',
  gripVertical: 'GripVertical',
  undo: 'Undo2',
  redo: 'Redo2',
  home: 'House',
  collapseAll: 'ChevronsUpDown',
} as const satisfies Record<string, IconName>;

/** Filled-style chrome icons (design system refresh). */
export const SOLID_CHROME_ICONS = {
  menu: 'List',
  close: 'X',
  chevronDown: 'CaretDown',
  chevronUp: 'CaretUp',
  chevronRight: 'CaretRight',
  chevronLeft: 'CaretLeft',
  check: 'Check',
  checkCircle: 'CheckCircle',
  checkSquare: 'CheckSquare',
  visibility: 'Eye',
  visibilityOff: 'EyeSlash',
  lock: 'Lock',
  unlock: 'LockOpen',
  search: 'MagnifyingGlass',
  settings: 'Gear',
  plus: 'Plus',
  minus: 'Minus',
  trash: 'Trash',
  spinner: 'Spinner',
  clock: 'Clock',
  history: 'ClockCounterClockwise',
  pin: 'PushPin',
  pinOff: 'PushPinSlash',
  fileText: 'FileText',
  folder: 'Folder',
  folderOpen: 'FolderOpen',
  filter: 'Funnel',
  layoutGrid: 'SquaresFour',
  list: 'List',
  listDashes: 'ListDashes',
  listBullets: 'ListBullets',
  ellipsis: 'DotsThree',
  ellipsisVertical: 'DotsThreeVertical',
  rotateCcw: 'ArrowCounterClockwise',
  upload: 'Upload',
  download: 'Download',
  star: 'Star',
  archive: 'Archive',
  copy: 'Copy',
  externalLink: 'ArrowRight',
  inspect: 'Code',
  ruler: 'Ruler',
  code: 'Code',
  palette: 'Palette',
  maximize: 'ArrowsOut',
  crosshair: 'Crosshair',
  gripVertical: 'DotsSixVertical',
  undo: 'ArrowUUpLeft',
  redo: 'ArrowUUpRight',
  home: 'House',
  collapseAll: 'ArrowsVertical',
  expandAll: 'CornersOut',
  user: 'User',
  users: 'Users',
  bell: 'Bell',
  bellSlash: 'BellSlash',
  info: 'Info',
  warning: 'Warning',
  warningCircle: 'WarningCircle',
  calendar: 'Calendar',
  calendarBlank: 'CalendarBlank',
  file: 'File',
  fileImage: 'FileImage',
  fileAudio: 'FileAudio',
  fileVideo: 'FileVideo',
  fileCode: 'FileCode',
  filePdf: 'FilePdf',
  fileDoc: 'FileDoc',
  fileXls: 'FileXls',
  filePpt: 'FilePpt',
  fileCsv: 'FileCsv',
  fileJson: 'FileJson',
  fileXml: 'FileXml',
  fileHtml: 'FileHtml',
  fileCss: 'FileCss',
  fileJs: 'FileJs',
  fileTs: 'FileTs',
  fileZip: 'FileZip',
  fileDocker: 'FileDocker',
  fileVue: 'FileVue',
  fileReact: 'FileReact',
  fileAngular: 'FileAngular',
  fileSvelte: 'FileSvelte',
  fileSolid: 'FileSolid',
  fileNext: 'FileNext',
  fileNuxt: 'FileNuxt',
  fileRemix: 'FileRemix',
  fileGraphql: 'FileGraphql',
  fileApollo: 'FileApollo',
  filePrisma: 'FilePrisma',
  fileTailwind: 'FileTailwind',
  fileVite: 'FileVite',
  fileWebpack: 'FileWebpack',
  fileRollup: 'FileRollup',
  fileEsbuild: 'FileEsbuild',
  fileParcel: 'FileParcel',
  fileTurbo: 'FileTurbo',
  fileBun: 'FileBun',
  fileDeno: 'FileDeno',
  cursor: 'Cursor',
  pen: 'Pen',
  image: 'Image',
  square: 'Square',
  puzzlePiece: 'PuzzlePiece',
  sidebar: 'Sidebar',
  sidebarSimple: 'SidebarSimple',
  layout: 'Layout',
  rows: 'Rows',
  columns: 'Columns',
  textT: 'TextT',
  textAA: 'TextAA',
  textB: 'TextB',
  textI: 'TextI',
  textU: 'TextU',
  textStrikethrough: 'TextStrikethrough',
  alignLeft: 'AlignLeft',
  alignCenter: 'AlignCenter',
  alignRight: 'AlignRight',
  alignJustify: 'AlignJustify',
  listPlus: 'ListPlus',
  listMinus: 'ListMinus',
  bracketsAngle: 'BracketsAngle',
  bracketsCurly: 'BracketsCurly',
  bracketsRound: 'BracketsRound',
  bracketsSquare: 'BracketsSquare',
  hash: 'Hash',
  at: 'At',
  link: 'Link',
  linkBreak: 'LinkBreak',
  globe: 'Globe',
  translate: 'Translate',
  flag: 'Flag',
  flagBanner: 'FlagBanner',
  shield: 'Shield',
  shieldCheck: 'ShieldCheck',
  shieldWarning: 'ShieldWarning',
  key: 'Key',
  keyhole: 'Keyhole',
  fingerprint: 'Fingerprint',
  identificationCard: 'IdentificationCard',
  identificationBadge: 'IdentificationBadge',
  creditCard: 'CreditCard',
  bank: 'Bank',
  currencyDollar: 'CurrencyDollar',
  currencyEuro: 'CurrencyEuro',
  currencyPound: 'CurrencyPound',
  currencyYen: 'CurrencyYen',
  currencyBtc: 'CurrencyBtc',
  currencyEth: 'CurrencyEth',
  chartLineUp: 'ChartLineUp',
  chartBar: 'ChartBar',
  chartPie: 'ChartPie',
  chartDonut: 'ChartDonut',
  trendUp: 'TrendUp',
  trendDown: 'TrendDown',
  activity: 'Activity',
  pulse: 'Pulse',
  heart: 'Heart',
  heartFill: 'HeartFill',
  heartBreak: 'HeartBreak',
  fire: 'Fire',
  flame: 'Flame',
  sparkle: 'Sparkle',
  starFour: 'StarFour',
  starHalf: 'StarHalf',
  crown: 'Crown',
  crownSimple: 'CrownSimple',
  medal: 'Medal',
  trophy: 'Trophy',
  confetti: 'Confetti',
  gift: 'Gift',
  cake: 'Cake',
  lightning: 'Lightning',
  flask: 'Flask',
  beaker: 'Beaker',
  selectionBackground: 'SelectionBackground',
  selectionForeground: 'SelectionForeground',
  faders: 'Faders',
  funnel: 'Funnel',
  squareOffset: 'SquareOffset',
  arrowFatLineRight: 'ArrowFatLineRight',
  arrowFatLineLeft: 'ArrowFatLineLeft',
  arrowFatLineUp: 'ArrowFatLineUp',
  arrowFatLineDown: 'ArrowFatLineDown',
  dotsSixVertical: 'DotsSixVertical',
  xCircle: 'XCircle',
  circle: 'Circle',
  circleHalf: 'CircleHalf',
  spinnerGap: 'SpinnerGap',
  arrowUUpLeft: 'ArrowUUpLeft',
  arrowUUpRight: 'ArrowUUpRight',
  cornersOut: 'CornersOut',
  hand: 'Hand',
  zoomIn: 'MagnifyingGlassPlus',
  zoomOut: 'MagnifyingGlassMinus',
  rotateCw: 'RotateCw',
  chevronsUpDown: 'ChevronsUpDown',
  cloud: 'Cloud',
  cloudSun: 'CloudSun',
  cloudMoon: 'CloudMoon',
  cloudRain: 'CloudRain',
  cloudLightning: 'CloudLightning',
  cloudSnow: 'CloudSnow',
  cloudFog: 'CloudFog',
  snowflake: 'Snowflake',
  thermometer: 'Thermometer',
  thermometerCold: 'ThermometerCold',
  thermometerHot: 'ThermometerHot',
  wind: 'Wind',
  drop: 'Drop',
  waves: 'Waves',
  wavesThree: 'WavesThree',
  lightningSlash: 'LightningSlash',
  rainbow: 'Rainbow',
  eyedropper: 'Eyedropper',
  paintBrush: 'PaintBrush',
  paintBucket: 'PaintBucket',
  swatches: 'Swatches',
  eraser: 'Eraser',
  pencil: 'Pencil',
  pencilLine: 'PencilLine',
  pencilSimple: 'PencilSimple',
  penNib: 'PenNib',
  markerPen: 'MarkerPen',
  highlighter: 'Highlighter',
  stamp: 'Stamp',
  protractor: 'Protractor',
  compass: 'Compass',
  draftingCompass: 'DraftingCompass',
  scissors: 'Scissors',
  paperclip: 'Paperclip',
  tack: 'Tack',
  note: 'Note',
  notePencil: 'NotePencil',
  notebook: 'Notebook',
  notepad: 'Notepad',
  clipboard: 'Clipboard',
  clipboardText: 'ClipboardText',
  printer: 'Printer',
  play: 'Play',
  penTool: 'Pen',
} as const satisfies Record<string, SolidIconName>;
