/**
 * Strata `<SolidIcon>` — filled-icon primitive (design system refresh).
 *
 * Built on Phosphor Icons. Enforces the same accessible-name contract as `<Icon>`:
 *   - pass `label` for a meaningful icon -> role="img" + aria-label
 *   - omit `label` for a decorative icon next to visible text -> aria-hidden
 *
 * This coexists with the Lucide-based `<Icon>` for non-refreshed surfaces.
 */

import * as PhosphorIcons from '@phosphor-icons/react';
import { forwardRef, type SVGProps } from 'react';

/** Curated set of Phosphor icon names for Strata. */
export type SolidIconName =
  | 'SquaresFour'
  | 'Triangle'
  | 'Diamond'
  | 'Hexagon'
  | 'ArrowsOut'
  | 'ArrowsIn'
  | 'ArrowsVertical'
  | 'ArrowUpRight'
  | 'ArrowsDownUp'
  | 'FrameCorners'
  | 'MagnifyingGlassPlus'
  | 'MagnifyingGlassMinus'
  | 'List'
  | 'ListDashes'
  | 'ListBullets'
  | 'ArrowRight'
  | 'ArrowLeft'
  | 'ArrowUp'
  | 'ArrowDown'
  | 'CaretDown'
  | 'CaretUp'
  | 'CaretRight'
  | 'CaretLeft'
  | 'Plus'
  | 'Minus'
  | 'X'
  | 'Check'
  | 'CheckCircle'
  | 'CheckSquare'
  | 'MagnifyingGlass'
  | 'User'
  | 'Users'
  | 'Gear'
  | 'Trash'
  | 'TrashSimple'
  | 'Folder'
  | 'FolderOpen'
  | 'Upload'
  | 'Download'
  | 'Copy'
  | 'Star'
  | 'Archive'
  | 'Clock'
  | 'ClockCounterClockwise'
  | 'ArrowCounterClockwise'
  | 'Eye'
  | 'EyeSlash'
  | 'Lock'
  | 'LockOpen'
  | 'PushPin'
  | 'PushPinSlash'
  | 'FileText'
  | 'House'
  | 'GridFour'
  | 'DotsThree'
  | 'DotsThreeVertical'
  | 'DotsSixVertical'
  | 'Faders'
  | 'Cursor'
  | 'Pen'
  | 'Image'
  | 'Printer'
  | 'Play'
  | 'Square'
  | 'PuzzlePiece'
  | 'Palette'
  | 'Code'
  | 'XCircle'
  | 'Circle'
  | 'CircleHalf'
  | 'Spinner'
  | 'SpinnerGap'
  | 'ArrowUUpLeft'
  | 'ArrowUUpRight'
  | 'CornersOut'
  | 'Crosshair'
  | 'Hand'
  | 'RotateCcw'
  | 'RotateCw'
  | 'Undo'
  | 'Redo'
  | 'GripVertical'
  | 'ChevronDown'
  | 'ChevronUp'
  | 'ChevronRight'
  | 'ChevronLeft'
  | 'ChevronsUpDown'
  | 'Filter'
  | 'Funnel'
  | 'Calendar'
  | 'CalendarBlank'
  | 'Bell'
  | 'BellSlash'
  | 'Info'
  | 'Warning'
  | 'WarningCircle'
  | 'SquareOffset'
  | 'ArrowFatLineRight'
  | 'ArrowFatLineLeft'
  | 'ArrowFatLineUp'
  | 'ArrowFatLineDown'
  | 'Lightning'
  | 'Flask'
  | 'Beaker'
  | 'SelectionBackground'
  | 'SelectionForeground'
  | 'Sidebar'
  | 'SidebarSimple'
  | 'Layout'
  | 'Rows'
  | 'Columns'
  | 'TextT'
  | 'TextAA'
  | 'TextB'
  | 'TextI'
  | 'TextU'
  | 'TextStrikethrough'
  | 'AlignLeft'
  | 'AlignCenter'
  | 'AlignRight'
  | 'AlignJustify'
  | 'AlignCenterHorizontal'
  | 'AlignCenterVertical'
  | 'AlignTop'
  | 'AlignBottom'
  | 'TextAlignJustify'
  | 'TextItalic'
  | 'TextUnderline'
  | 'TextAa'
  | 'ArrowClockwise'
  | 'ArrowSquareOut'
  | 'Bookmark'
  | 'BookmarkSimple'
  | 'CornersIn'
  | 'Crop'
  | 'FloppyDisk'
  | 'Pause'
  | 'ListPlus'
  | 'ListMinus'
  | 'BracketsAngle'
  | 'BracketsCurly'
  | 'BracketsRound'
  | 'BracketsSquare'
  | 'Hash'
  | 'At'
  | 'Link'
  | 'LinkBreak'
  | 'Globe'
  | 'Translate'
  | 'Flag'
  | 'FlagBanner'
  | 'Shield'
  | 'ShieldCheck'
  | 'ShieldWarning'
  | 'Key'
  | 'Keyhole'
  | 'Fingerprint'
  | 'IdentificationCard'
  | 'IdentificationBadge'
  | 'CreditCard'
  | 'Bank'
  | 'CurrencyDollar'
  | 'CurrencyEuro'
  | 'CurrencyPound'
  | 'CurrencyYen'
  | 'CurrencyBtc'
  | 'CurrencyEth'
  | 'ChartLineUp'
  | 'ChartBar'
  | 'ChartPie'
  | 'ChartDonut'
  | 'TrendUp'
  | 'TrendDown'
  | 'Activity'
  | 'Pulse'
  | 'Heart'
  | 'HeartFill'
  | 'HeartBreak'
  | 'Fire'
  | 'Flame'
  | 'Sparkle'
  | 'StarFour'
  | 'StarHalf'
  | 'Crown'
  | 'CrownSimple'
  | 'Medal'
  | 'Trophy'
  | 'Confetti'
  | 'Gift'
  | 'Cake'
  | 'BeerBottle'
  | 'Wine'
  | 'Coffee'
  | 'Cup'
  | 'TeaBag'
  | 'Pizza'
  | 'Hamburger'
  | 'ForkKnife'
  | 'BowlFood'
  | 'Carrot'
  | 'Apple'
  | 'Grape'
  | 'Lemon'
  | 'Cherries'
  | 'Egg'
  | 'Fish'
  | 'Bird'
  | 'Dog'
  | 'Cat'
  | 'Horse'
  | 'Bug'
  | 'Butterfly'
  | 'BugBeetle'
  | 'Spider'
  | 'Snail'
  | 'Plant'
  | 'Flower'
  | 'FlowerLotus'
  | 'FlowerTulip'
  | 'Tree'
  | 'TreeEvergreen'
  | 'TreePalm'
  | 'Leaf'
  | 'Mountains'
  | 'Sun'
  | 'SunDim'
  | 'SunHorizon'
  | 'Moon'
  | 'MoonStars'
  | 'Cloud'
  | 'CloudSun'
  | 'CloudMoon'
  | 'CloudRain'
  | 'CloudLightning'
  | 'CloudSnow'
  | 'CloudFog'
  | 'Snowflake'
  | 'Thermometer'
  | 'ThermometerCold'
  | 'ThermometerHot'
  | 'Wind'
  | 'Drop'
  | 'Waves'
  | 'WavesThree'
  | 'LightningSlash'
  | 'Rainbow'
  | 'Eyedropper'
  | 'PaintBrush'
  | 'PaintBucket'
  | 'Swatches'
  | 'Eraser'
  | 'Pencil'
  | 'PencilLine'
  | 'PencilSimple'
  | 'PenNib'
  | 'MarkerPen'
  | 'Highlighter'
  | 'Stamp'
  | 'Ruler'
  | 'Protractor'
  | 'Compass'
  | 'DraftingCompass'
  | 'Scissors'
  | 'Paperclip'
  | 'Tack'
  | 'Note'
  | 'NotePencil'
  | 'Notebook'
  | 'Notepad'
  | 'Clipboard'
  | 'ClipboardText'
  | 'File'
  | 'FileImage'
  | 'FileAudio'
  | 'FileVideo'
  | 'FileCode'
  | 'FileZip'
  | 'FilePdf'
  | 'FileDoc'
  | 'FileXls'
  | 'FilePpt'
  | 'FileCsv'
  | 'FileJson'
  | 'FileXml'
  | 'FileHtml'
  | 'FileCss'
  | 'FileJs'
  | 'FileTs'
  | 'FileRs'
  | 'FileGo'
  | 'FilePy'
  | 'FileRust'
  | 'FileC'
  | 'FileCpp'
  | 'FileCSharp'
  | 'FileJava'
  | 'FileKotlin'
  | 'FileSwift'
  | 'FilePhp'
  | 'FileRuby'
  | 'FileSql'
  | 'FileSh'
  | 'FileBash'
  | 'FilePowershell'
  | 'FileDocker'
  | 'FileVue'
  | 'FileReact'
  | 'FileAngular'
  | 'FileSvelte'
  | 'FileSolid'
  | 'FileNext'
  | 'FileNuxt'
  | 'FileRemix'
  | 'FileGraphql'
  | 'FileApollo'
  | 'FilePrisma'
  | 'FileTailwind'
  | 'FileVite'
  | 'FileWebpack'
  | 'FileRollup'
  | 'FileEsbuild'
  | 'FileParcel'
  | 'FileTurbo'
  | 'FileBun'
  | 'FileDeno';

export interface SolidIconProps extends Omit<SVGProps<SVGSVGElement>, 'name'> {
  /** Phosphor icon name, e.g. "SquaresFour", "List", "ArrowRight". */
  name: SolidIconName;
  /**
   * Accessible name. If provided the icon is exposed as `role="img"` with an
   * `aria-label`. If omitted the icon is marked `aria-hidden` (decorative) and
   * MUST be accompanied by a visible text label in the surrounding UI.
   */
  label?: string;
  /** Pixel size; defaults to 1em (inherits font-size). */
  size?: number | string;
  /** Icon weight. Default is 'fill' for filled style. */
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
}

export const SolidIcon = forwardRef<SVGSVGElement, SolidIconProps>(function SolidIcon(
  { name, label, size = '1em', weight = 'fill', ...rest },
  ref,
) {
  const IconComponent = (PhosphorIcons as unknown as Record<string, React.ElementType | undefined>)[
    name
  ];
  if (!IconComponent) {
    // Graceful fallback: render a placeholder instead of crashing
    console.warn(`[SolidIcon] Unknown icon: "${name}"`);
    return (
      <span
        ref={ref as React.Ref<HTMLSpanElement>}
        role="img"
        aria-label={label}
        style={{
          display: 'inline-flex',
          width: size,
          height: size,
        }}
      />
    );
  }
  if (label) {
    return (
      <IconComponent
        ref={ref}
        role="img"
        aria-label={label}
        size={size}
        weight={weight}
        {...rest}
      />
    );
  }
  return (
    <IconComponent ref={ref} aria-hidden size={size} weight={weight} focusable={false} {...rest} />
  );
});
