/**
 * Built-in mockup templates.
 *
 * All templates are original vector artwork generated in this file — generic
 * devices, no device trade dress, no brand marks, no product photography.
 * The licence snapshot therefore carries verified permissions (see
 * docs/architecture/mockup-system.md for the licensing policy).
 *
 * Geometry contract:
 * - `surface.plate` for flat surfaces: template-output-absolute coordinates.
 * - `surface.plate` for quad surfaces: slot-local coordinates (0,0 is the
 *   slot top-left), warped together with the content; `platePadding`
 *   describes how far the plate extends beyond the slot.
 * - `template.plate`: full-bleed background shapes (output coordinates).
 */

import { hashMockupTemplate } from './ops';
import type { MockupTemplateAsset } from './types';

const BUILTIN_LICENCE = {
  title: 'FSL-1.1-MIT',
  spdx: 'FSL-1.1-MIT',
  creator: 'Varve contributors',
  attribution: 'Varve contributors',
  commercialUse: 'yes' as const,
  modification: 'yes' as const,
  redistribution: 'yes' as const,
};

const rawTemplates: Array<Omit<MockupTemplateAsset, 'contentHash'>> = [
  {
    id: 'builtin:phone-flat',
    schemaVersion: 2,
    name: 'Phone — Front',
    category: 'devices',
    source: 'builtin',
    orientation: 'portrait',
    outputWidth: 1000,
    outputHeight: 1600,
    backgroundColor: '#eef0f4',
    plate: [],
    surfaces: [
      {
        id: 'screen',
        name: 'Screen',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 300,
        y: 420,
        width: 400,
        height: 760,
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: 272, y: 368, width: 456, height: 864, rx: 64, fill: '#16181c' },
          { kind: 'ellipse', x: 470, y: 392, width: 60, height: 18, fill: '#0b0c0f' },
          { kind: 'rect', x: 256, y: 560, width: 16, height: 96, rx: 8, fill: '#16181c' },
          { kind: 'rect', x: 728, y: 560, width: 16, height: 96, rx: 8, fill: '#16181c' },
          { kind: 'rect', x: 460, y: 1192, width: 80, height: 6, rx: 3, fill: '#3a3f46' },
        ],
        shadow: { blur: 48, offsetY: 28, opacity: 0.28 },
        screenGlow: true,
        dark: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['phone', 'mobile', 'portrait', 'screen'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:phone-perspective',
    schemaVersion: 2,
    name: 'Phone — Angled',
    category: 'devices',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1200,
    backgroundColor: '#eef0f4',
    plate: [],
    surfaces: [
      {
        id: 'screen',
        name: 'Screen',
        kind: 'quad',
        sourceSlot: 'screen',
        x: 560,
        y: 300,
        width: 480,
        height: 640,
        quad: [
          { x: 560, y: 280 },
          { x: 1040, y: 310 },
          { x: 1000, y: 980 },
          { x: 600, y: 960 },
        ],
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: -64, y: -70, width: 608, height: 800, rx: 80, fill: '#16181c' },
          { kind: 'ellipse', x: 224, y: -30, width: 80, height: 24, fill: '#0b0c0f' },
        ],
        platePadding: { x: 64, y: 90 },
        shadow: { blur: 40, offsetY: 24, opacity: 0.3 },
        screenGlow: true,
        dark: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['phone', 'mobile', 'perspective', 'angled'],
    capabilities: ['quad'],
  },
  {
    id: 'builtin:tablet-flat',
    schemaVersion: 2,
    name: 'Tablet — Front',
    category: 'devices',
    source: 'builtin',
    orientation: 'portrait',
    outputWidth: 1400,
    outputHeight: 1600,
    backgroundColor: '#eef0f4',
    plate: [],
    surfaces: [
      {
        id: 'screen',
        name: 'Screen',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 350,
        y: 250,
        width: 700,
        height: 1100,
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: 320, y: 218, width: 760, height: 1164, rx: 56, fill: '#1a1d21' },
          { kind: 'ellipse', x: 670, y: 238, width: 48, height: 16, fill: '#0b0c0f' },
        ],
        shadow: { blur: 60, offsetY: 32, opacity: 0.28 },
        screenGlow: true,
        dark: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['tablet', 'mobile', 'screen'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:browser-flat',
    schemaVersion: 2,
    name: 'Browser Window',
    category: 'browser-desktop',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1100,
    backgroundColor: '#eef0f4',
    plate: [],
    surfaces: [
      {
        id: 'page',
        name: 'Page',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 140,
        y: 220,
        width: 1320,
        height: 760,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: 120, y: 160, width: 1360, height: 840, rx: 16, fill: '#ffffff' },
          { kind: 'rect', x: 120, y: 160, width: 1360, height: 60, fill: '#f2f3f5' },
          { kind: 'ellipse', x: 146, y: 186, width: 16, height: 16, fill: '#d8dbe0' },
          { kind: 'ellipse', x: 172, y: 186, width: 16, height: 16, fill: '#d8dbe0' },
          { kind: 'ellipse', x: 198, y: 186, width: 16, height: 16, fill: '#d8dbe0' },
          { kind: 'rect', x: 240, y: 178, width: 500, height: 24, rx: 12, fill: '#e8eaee' },
        ],
        shadow: { blur: 40, offsetY: 20, opacity: 0.25 },
        screenGlow: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['browser', 'website', 'web', 'window'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:monitor-flat',
    schemaVersion: 2,
    name: 'Desktop Monitor',
    category: 'browser-desktop',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1100,
    backgroundColor: '#eef0f4',
    plate: [],
    surfaces: [
      {
        id: 'screen',
        name: 'Screen',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 340,
        y: 170,
        width: 920,
        height: 580,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: 316, y: 146, width: 968, height: 628, rx: 12, fill: '#1a1d21' },
          { kind: 'rect', x: 780, y: 774, width: 40, height: 110, fill: '#2a2e33' },
          { kind: 'rect', x: 690, y: 884, width: 220, height: 28, rx: 14, fill: '#2a2e33' },
        ],
        shadow: { blur: 40, offsetY: 16, opacity: 0.25 },
        screenGlow: true,
        dark: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['monitor', 'desktop', 'screen'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:laptop-perspective',
    schemaVersion: 2,
    name: 'Laptop — Angled',
    category: 'browser-desktop',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1800,
    outputHeight: 1200,
    backgroundColor: '#eef0f4',
    plate: [
      { kind: 'rect', x: 330, y: 800, width: 1140, height: 60, rx: 26, fill: '#3a3f45' },
      { kind: 'rect', x: 360, y: 750, width: 1080, height: 100, rx: 16, fill: '#2e3238' },
    ],
    surfaces: [
      {
        id: 'screen',
        name: 'Screen',
        kind: 'quad',
        sourceSlot: 'screen',
        x: 430,
        y: 170,
        width: 940,
        height: 590,
        quad: [
          { x: 430, y: 170 },
          { x: 1370, y: 200 },
          { x: 1320, y: 790 },
          { x: 470, y: 780 },
        ],
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: -56, y: -52, width: 1052, height: 690, rx: 24, fill: '#23262b' },
          { kind: 'ellipse', x: 492, y: -28, width: 16, height: 12, fill: '#0b0c0f' },
        ],
        platePadding: { x: 56, y: 52 },
        shadow: { blur: 36, offsetY: 20, opacity: 0.3 },
        screenGlow: true,
        dark: true,
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['laptop', 'computer', 'perspective'],
    capabilities: ['quad'],
  },
  {
    id: 'builtin:poster-flat',
    schemaVersion: 2,
    name: 'Poster — Wall',
    category: 'print',
    source: 'builtin',
    orientation: 'portrait',
    outputWidth: 1200,
    outputHeight: 1700,
    backgroundColor: '#e6e1d8',
    plate: [{ kind: 'rect', x: 158, y: 128, width: 884, height: 1444, fill: '#fbfaf7' }],
    surfaces: [
      {
        id: 'poster',
        name: 'Poster',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 150,
        y: 120,
        width: 900,
        height: 1460,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 32, offsetY: 18, opacity: 0.3 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['poster', 'print', 'wall', 'portrait'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:business-card-flat',
    schemaVersion: 2,
    name: 'Business Card — Front & Back',
    category: 'stationery',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1400,
    outputHeight: 900,
    backgroundColor: '#eef0f4',
    plate: [
      { kind: 'rect', x: 150, y: 290, width: 520, height: 320, rx: 12, fill: '#ffffff' },
      { kind: 'rect', x: 730, y: 290, width: 520, height: 320, rx: 12, fill: '#ffffff' },
    ],
    surfaces: [
      {
        id: 'front',
        name: 'Front',
        kind: 'flat',
        sourceSlot: 'front',
        x: 170,
        y: 310,
        width: 480,
        height: 280,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 28, offsetY: 12, opacity: 0.25 },
      },
      {
        id: 'back',
        name: 'Back',
        kind: 'flat',
        sourceSlot: 'back',
        x: 750,
        y: 310,
        width: 480,
        height: 280,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 28, offsetY: 12, opacity: 0.25 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['business card', 'stationery', 'front', 'back'],
    capabilities: ['flat', 'multi-surface'],
  },
  {
    id: 'builtin:book-cover-perspective',
    schemaVersion: 2,
    name: 'Book Cover — Angled',
    category: 'print',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1400,
    backgroundColor: '#e8e4dc',
    plate: [{ kind: 'ellipse', x: 200, y: 1030, width: 1200, height: 160, fill: '#d6c6ae' }],
    surfaces: [
      {
        id: 'cover',
        name: 'Cover',
        kind: 'quad',
        sourceSlot: 'screen',
        x: 560,
        y: 180,
        width: 500,
        height: 760,
        quad: [
          { x: 560, y: 180 },
          { x: 1060, y: 210 },
          { x: 1020, y: 990 },
          { x: 590, y: 960 },
        ],
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: -70, y: -8, width: 70, height: 790, rx: 6, fill: '#2c2a26' },
          { kind: 'rect', x: -46, y: 4, width: 46, height: 778, fill: '#f2efe9' },
        ],
        platePadding: { x: 70, y: 8 },
        shadow: { blur: 40, offsetY: 24, opacity: 0.3 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['book', 'cover', 'print', 'perspective'],
    capabilities: ['quad'],
  },
  {
    id: 'builtin:packaging-box-perspective',
    schemaVersion: 2,
    name: 'Packaging Box — Front',
    category: 'packaging',
    source: 'builtin',
    orientation: 'square',
    outputWidth: 1600,
    outputHeight: 1600,
    backgroundColor: '#eef0f4',
    plate: [
      {
        kind: 'rect',
        x: 560,
        y: 300,
        width: 480,
        height: 260,
        rx: 8,
        rotation: -8,
        fill: '#d8dbe0',
      },
      {
        kind: 'rect',
        x: 1056,
        y: 592,
        width: 150,
        height: 500,
        rx: 8,
        rotation: -6,
        fill: '#c2c6cc',
      },
    ],
    surfaces: [
      {
        id: 'front',
        name: 'Front face',
        kind: 'quad',
        sourceSlot: 'front',
        x: 560,
        y: 560,
        width: 480,
        height: 520,
        quad: [
          { x: 560, y: 560 },
          { x: 1040, y: 580 },
          { x: 1000, y: 1100 },
          { x: 580, y: 1090 },
        ],
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 36, offsetY: 22, opacity: 0.3 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['packaging', 'box', 'product', 'perspective'],
    capabilities: ['quad'],
  },
  {
    id: 'builtin:social-board-flat',
    schemaVersion: 2,
    name: 'Social Post — Board',
    category: 'social-marketing',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1200,
    backgroundColor: '#eef0f4',
    plate: [
      { kind: 'rect', x: 220, y: 90, width: 1160, height: 680, rx: 24, fill: '#ffffff' },
      { kind: 'rect', x: 220, y: 770, width: 1160, height: 120, rx: 24, fill: '#f6f7f9' },
    ],
    surfaces: [
      {
        id: 'art',
        name: 'Artwork',
        kind: 'flat',
        sourceSlot: 'screen',
        x: 250,
        y: 120,
        width: 1100,
        height: 620,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 36, offsetY: 18, opacity: 0.25 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['social', 'marketing', 'post', 'board'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:logo-board-flat',
    schemaVersion: 2,
    name: 'Logo Presentation Board',
    category: 'logo',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1000,
    backgroundColor: '#f2f4f7',
    plate: [
      { kind: 'ellipse', x: 560, y: 180, width: 480, height: 480, fill: '#e7eaf0' },
      { kind: 'rect', x: 640, y: 700, width: 320, height: 24, rx: 12, fill: '#d8dce4' },
      { kind: 'rect', x: 680, y: 740, width: 240, height: 16, rx: 8, fill: '#e2e5ea' },
    ],
    surfaces: [
      {
        id: 'logo',
        name: 'Logo',
        kind: 'flat',
        sourceSlot: 'logo',
        x: 640,
        y: 260,
        width: 320,
        height: 320,
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 24, offsetY: 10, opacity: 0.2 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['logo', 'brand', 'presentation'],
    capabilities: ['flat'],
  },
  {
    id: 'builtin:tee-front-flat',
    schemaVersion: 2,
    name: 'T-Shirt — Front',
    category: 'apparel',
    source: 'builtin',
    orientation: 'portrait',
    outputWidth: 1400,
    outputHeight: 1600,
    backgroundColor: '#e9edf1',
    plate: [],
    surfaces: [
      {
        id: 'shirt-front',
        name: 'Front print',
        kind: 'flat',
        sourceSlot: 'front',
        x: 330,
        y: 390,
        width: 740,
        height: 820,
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: 270, y: 300, width: 860, height: 1080, rx: 160, fill: '#f7f8fa' },
          { kind: 'ellipse', x: 560, y: 270, width: 280, height: 150, fill: '#dfe3e8' },
          {
            kind: 'rect',
            x: 250,
            y: 390,
            width: 120,
            height: 540,
            rx: 54,
            rotation: -14,
            fill: '#eef1f4',
          },
          {
            kind: 'rect',
            x: 1030,
            y: 390,
            width: 120,
            height: 540,
            rx: 54,
            rotation: 14,
            fill: '#eef1f4',
          },
        ],
        shadow: { blur: 44, offsetY: 28, opacity: 0.28 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['t-shirt', 'tee', 'apparel', 'clothing', 'product', 'front'],
    capabilities: ['flat', 'apparel'],
  },
  {
    id: 'builtin:billboard-front-quad',
    schemaVersion: 2,
    name: 'Billboard — Front',
    category: 'signage',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1800,
    outputHeight: 1200,
    backgroundColor: '#dfe6ec',
    plate: [
      { kind: 'rect', x: 760, y: 760, width: 80, height: 320, fill: '#6b737c' },
      { kind: 'rect', x: 960, y: 760, width: 80, height: 320, fill: '#6b737c' },
      { kind: 'ellipse', x: 650, y: 1030, width: 500, height: 70, fill: '#b7c0c9' },
    ],
    surfaces: [
      {
        id: 'billboard-face',
        name: 'Billboard face',
        kind: 'quad',
        sourceSlot: 'front',
        x: 210,
        y: 220,
        width: 1380,
        height: 540,
        quad: [
          { x: 210, y: 220 },
          { x: 1590, y: 230 },
          { x: 1560, y: 760 },
          { x: 240, y: 750 },
        ],
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        plate: [
          { kind: 'rect', x: -24, y: -24, width: 1428, height: 588, rx: 18, fill: '#343a42' },
          { kind: 'rect', x: 0, y: 0, width: 1380, height: 540, fill: '#f4f5f6' },
        ],
        platePadding: { x: 24, y: 24 },
        shadow: { blur: 48, offsetY: 30, opacity: 0.3 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['billboard', 'signage', 'outdoor', 'advertising', 'poster', 'perspective'],
    capabilities: ['quad', 'signage'],
  },
  {
    id: 'builtin:label-cylinder-front',
    schemaVersion: 2,
    name: 'Product Label — Cylinder',
    category: 'packaging',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1600,
    outputHeight: 1100,
    backgroundColor: '#edf0f3',
    plate: [
      { kind: 'rect', x: 330, y: 250, width: 940, height: 610, rx: 44, fill: '#d6dbe1' },
      { kind: 'ellipse', x: 330, y: 250, width: 940, height: 160, fill: '#c2c9d1' },
      { kind: 'ellipse', x: 330, y: 760, width: 940, height: 160, fill: '#c0c7cf' },
    ],
    surfaces: [
      {
        id: 'label',
        name: 'Wrap label',
        kind: 'cylindrical',
        sourceSlot: 'label',
        x: 370,
        y: 350,
        width: 860,
        height: 410,
        fit: 'cover',
        alignment: { x: 'center', y: 'center' },
        cylindrical: { axis: 'vertical', wrapDegrees: 120, seam: 0, crop: 'slot' },
        shadow: { blur: 24, offsetY: 12, opacity: 0.2 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['cylinder', 'label', 'bottle', 'can', 'packaging', 'product', 'curved'],
    capabilities: ['cylindrical', 'bounded-2.5d'],
  },
  {
    id: 'builtin:envelope-front-flat',
    schemaVersion: 2,
    name: 'Envelope — Front',
    category: 'stationery',
    source: 'builtin',
    orientation: 'landscape',
    outputWidth: 1500,
    outputHeight: 1000,
    backgroundColor: '#e9e5dd',
    plate: [
      { kind: 'rect', x: 190, y: 250, width: 1120, height: 540, rx: 10, fill: '#fbfaf7' },
      { kind: 'rect', x: 190, y: 250, width: 1120, height: 270, fill: '#f2eee7' },
    ],
    surfaces: [
      {
        id: 'front',
        name: 'Front artwork',
        kind: 'flat',
        sourceSlot: 'front',
        x: 260,
        y: 330,
        width: 980,
        height: 380,
        fit: 'contain',
        alignment: { x: 'center', y: 'center' },
        shadow: { blur: 32, offsetY: 18, opacity: 0.24 },
      },
    ],
    overlays: [],
    licence: BUILTIN_LICENCE,
    tags: ['envelope', 'stationery', 'mail', 'paper', 'front'],
    capabilities: ['flat'],
  },
];

let cached: MockupTemplateAsset[] | null = null;

/** The built-in catalog with content hashes materialized. */
export function getBuiltinMockupTemplates(): MockupTemplateAsset[] {
  if (cached) return cached;
  cached = rawTemplates.map((t) => ({ ...t, contentHash: hashMockupTemplate(t) }));
  return cached;
}

export function getBuiltinMockupTemplate(id: string): MockupTemplateAsset | undefined {
  return getBuiltinMockupTemplates().find((t) => t.id === id);
}
