#!/usr/bin/env node

/**
 * History-sensitive checks for an outgoing push.
 *
 * The ordinary file plan is a net diff.  This companion scan walks every
 * outgoing commit so a secret (or an oversized binary) that was added and
 * subsequently removed cannot disappear from validation merely because the
 * final tree looks clean.
 */

import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { MAX_TEXT_BYTES, scanText, shouldSkip } from '../secret-scan.mjs';
import { PUSH_LIMITS } from './validation-policy.mjs';

const SHA = /^[0-9a-f]{40}$/;
const ZERO = '0'.repeat(40);

export function createGitAdapter(cwd = process.cwd()) {
  return {
    run(args, options = {}) {
      const result = spawnSync('git', args, {
        cwd,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
        shell: false,
        ...options,
      });
      return {
        status: result.status ?? (result.error ? 1 : 0),
        stdout: result.stdout ?? '',
        stderr: result.stderr ?? '',
        error: result.error,
      };
    },
  };
}

function text(git, args, { allowFailure = false } = {}) {
  const result = git.run(args);
  if (!allowFailure && result.status !== 0) {
    throw new Error(result.stderr.trim() || `git ${args.join(' ')} failed`);
  }
  return result.stdout;
}

function parseStatusToken(token) {
  const clean = token.replace(/\0/g, '');
  const tab = clean.indexOf('\t');
  if (tab >= 0) return { status: clean.slice(0, tab), inlinePath: clean.slice(tab + 1) };
  return { status: clean, inlinePath: null };
}

/** Parse `git ... --name-status -z` without ever splitting on whitespace. */
export function parseNameStatusZ(output) {
  const tokens = String(output)
    .split('\0')
    .filter((token, index, all) => token || index < all.length - 1);
  const records = [];
  let i = 0;
  while (i < tokens.length) {
    const raw = tokens[i++];
    if (!raw) continue;
    const { status, inlinePath } = parseStatusToken(raw);
    if (!/^[ACDMRTUXB][0-9]*$/.test(status)) continue;
    const paths = [];
    if (inlinePath !== null) paths.push(inlinePath);
    const pathCount = status.startsWith('R') || status.startsWith('C') ? 2 : 1;
    while (paths.length < pathCount && i < tokens.length) paths.push(tokens[i++]);
    records.push({
      status,
      path: paths.at(-1) ?? '',
      oldPath: paths.length > 1 ? paths[0] : null,
      paths,
    });
  }
  return records;
}

function blobSha(git, commit, path) {
  const result = git.run(['rev-parse', '--verify', `${commit}:${path}`]);
  if (result.status !== 0) return null;
  const sha = result.stdout.trim();
  return SHA.test(sha) ? sha : null;
}

function blobSize(git, sha) {
  const result = git.run(['cat-file', '-s', sha]);
  if (result.status !== 0) return null;
  const size = Number(result.stdout.trim());
  return Number.isSafeInteger(size) ? size : null;
}

function blobText(git, sha, maxBytes = MAX_TEXT_BYTES) {
  const size = blobSize(git, sha);
  if (size === null || size > maxBytes) return null;
  const result = git.run(['cat-file', 'blob', sha]);
  if (result.status !== 0) return null;
  return result.stdout;
}

const PROHIBITED_TRAILERS = [
  /^co-authored-by:.*(?:claude|anthropic|devin|cognition|copilot|codex|chatgpt|openai|gemini|cursor|windsurf|opencode|strata\.agent|cascade)/im,
  /(?:Generated with \[Devin\]|Generated by Claude|Generated with Claude|Created with Devin|Written with Copilot|Generated by Codex|AI-generated commit|AI-assisted commit)/i,
  /^co-authored-by:.*<<[A-Z_]+>>/im,
];

function messageFindings(git, commit) {
  const message = text(git, ['show', '-s', '--format=%B', commit]);
  return PROHIBITED_TRAILERS.filter((pattern) => pattern.test(message)).map((pattern) => ({
    kind: 'commit-message',
    rule: 'prohibited-commit-trailer',
    commit,
    message: pattern.toString(),
  }));
}

/**
 * Scan an explicit list of outgoing commit SHAs.  The result is deterministic
 * and contains no worktree paths, so it can be embedded in a push plan.
 */
export function scanOutgoingHistory(
  commits,
  {
    git = createGitAdapter(),
    maxBinaryBytes = PUSH_LIMITS.maxBinaryAdditionBytes,
    scanSecrets = true,
    scanMetadata = true,
  } = {},
) {
  const findings = [];
  const seenBlobs = new Set();
  for (const commit of [...new Set(commits)].sort()) {
    if (!SHA.test(commit) || commit === ZERO) continue;
    if (scanMetadata) findings.push(...messageFindings(git, commit));
    const records = parseNameStatusZ(
      text(git, ['diff-tree', '--root', '-r', '-M', '-C', '--name-status', '-z', commit]),
    );
    for (const record of records) {
      // The destination path is what exists in the commit.  Renames/copies
      // therefore scan the new content once, while deletions have no blob.
      if (record.status.startsWith('D')) continue;
      const sha = blobSha(git, commit, record.path);
      if (!sha || seenBlobs.has(sha)) continue;
      seenBlobs.add(sha);
      const size = blobSize(git, sha);
      if (
        (record.status.startsWith('A') || record.status.startsWith('C')) &&
        size > maxBinaryBytes
      ) {
        findings.push({
          kind: 'large-binary',
          rule: 'large-binary-addition',
          commit,
          path: record.path,
          bytes: size,
          limit: maxBinaryBytes,
        });
      }
      if (!scanSecrets || shouldSkip(record.path)) continue;
      const body = blobText(git, sha);
      if (body === null) continue;
      const secretFindings = [];
      scanText(body, record.path, secretFindings);
      for (const finding of secretFindings) {
        findings.push({ kind: 'secret', commit, ...finding });
      }
    }
  }
  return findings;
}

export function formatHistoryFindings(findings) {
  if (!findings.length) return 'clean';
  return findings
    .map((finding) => {
      const location = [finding.commit, finding.path].filter(Boolean).join(' ');
      return `${finding.rule} at ${location}${finding.bytes ? ` (${finding.bytes} bytes)` : ''}`;
    })
    .join('; ');
}

function main() {
  const args = new Set(process.argv.slice(2));
  const git = createGitAdapter();
  const base = process.env.VARVE_HISTORY_BASE;
  const head = process.env.VARVE_HISTORY_HEAD;
  const commitsText = process.env.VARVE_OUTGOING_COMMITS ?? '';
  const commits =
    base && head
      ? text(git, ['log', '--format=%H', '-z', `${base}..${head}`])
          .split('\0')
          .filter((sha) => SHA.test(sha))
      : commitsText.split(/[\s,]+/).filter(Boolean);
  const findings = scanOutgoingHistory(commits, {
    git,
    scanSecrets: args.has('--secrets') || !args.has('--metadata'),
    scanMetadata: args.has('--metadata') || !args.has('--secrets'),
  });
  if (findings.length) {
    console.error(`Outgoing history policy failed: ${formatHistoryFindings(findings)}`);
    process.exit(1);
  }
  console.log(`Outgoing history policy clean (${commits.length} commit(s)).`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();

export { PROHIBITED_TRAILERS };
