/**
 * Export capability contracts (Strata export rebuild, M3).
 *
 * Every format declares what the encoder can actually do. The UI is
 * capability-driven: it must not show controls the encoder ignores, and must
 * not advertise formats the encoder cannot produce. `supported: false` means
 * no encoder exists in this app — the UI must not offer it.
 *
 * These tables mirror the real backends:
 *  - raster PNG/JPEG/WebP: browser canvas toBlob/convertToBlob (sRGB, 8-bit)
 *  - GIF: TS encoder (packages/engine/src/gifExport.ts)
 *  - SVG: @strata/codegen scene→SVG with subtree raster fallback
 *  - PDF family: strata-print (Rust) with a strict vector subset; browser has
 *    a minimal raster-PDF fallback
 *  - codegen: @strata/codegen emitters (semantic, not pixel-exact)
 *
 * Platform differences are expressed via `browser`/`desktop` flags; use
 * {@link capabilitiesForFormat} to get the contract for an active platform.
 */

import type { ExportFormat } from './model';

export type VectorSupportLevel = 'native' | 'approximated' | 'rasterized' | 'blocked';

export type FeatureSupportLevel = 'native' | 'approximated' | 'rasterized' | 'flatten' | 'blocked';

export interface FormatColorCapability {
  rgb: boolean;
  cmyk: boolean;
  grayscale: boolean;
  spotColors: boolean;
}

export interface FormatCapability {
  format: ExportFormat;
  label: string;
  /** False when no encoder exists — UI must not advertise this format. */
  supported: boolean;
  /** Why unsupported (shown when the user somehow has such a configuration). */
  reasonUnsupported?: string;
  /** Available in the web (browser/WASM) runtime. */
  browser: boolean;
  /** Available in the Tauri desktop runtime. */
  desktop: boolean;
  transparency: boolean;
  vector: VectorSupportLevel;
  text: 'native' | 'outline' | 'rasterized' | 'blocked';
  embeddedFonts: boolean;
  outlinedFonts: boolean;
  linkedImages: boolean;
  embeddedImages: boolean;
  iccEmbedding: boolean;
  colorSpaces: FormatColorCapability;
  alpha: boolean;
  animation: boolean;
  multiPage: boolean;
  bleed: boolean;
  cropMarks: boolean;
  printerMarks: boolean;
  metadata: boolean;
  compression: boolean;
  lossless: boolean;
  highBitDepth: boolean;
  masks: FeatureSupportLevel;
  blendModes: FeatureSupportLevel;
  filters: FeatureSupportLevel;
  adjustmentLayers: 'native' | 'rasterize' | 'blocked';
  /** Hard cap on the longest output dimension in px (0 = no cap). */
  maxDimensions: number;
  maxPageCount: number;
  /** True when the IR engine is always required to render this format. */
  needsEngine: boolean;
  /** True when output is rasterized end-to-end regardless of content. */
  rasterizedByDefault: boolean;
  /** True when this is a code generator rather than an image/vector encoder. */
  codegen: boolean;
}

// Raster surface policy: 16 384 px/axis, 32 Mi pixels (engine/rasterSurface.ts).
export const RASTER_MAX_DIMENSION = 16_384;
export const RASTER_MAX_PIXELS = 33_554_432;

export const FORMAT_CAPABILITIES: Record<ExportFormat, FormatCapability> = {
  png: {
    format: 'png',
    label: 'PNG',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: RASTER_MAX_DIMENSION,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  jpeg: {
    format: 'jpeg',
    label: 'JPEG',
    supported: true,
    browser: true,
    desktop: true,
    transparency: false,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: false,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: false,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: RASTER_MAX_DIMENSION,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  webp: {
    format: 'webp',
    label: 'WebP',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: RASTER_MAX_DIMENSION,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  avif: {
    format: 'avif',
    label: 'AVIF',
    supported: false,
    reasonUnsupported:
      'No AVIF encoder is available in this runtime (canvas toBlob does not guarantee image/avif and no native encoder is wired).',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: RASTER_MAX_DIMENSION,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  gif: {
    format: 'gif',
    label: 'GIF',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: true,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: true,
    lossless: false,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: RASTER_MAX_DIMENSION,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  svg: {
    format: 'svg',
    label: 'SVG',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'native',
    blendModes: 'flatten',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  pdf: {
    format: 'pdf',
    label: 'PDF (screen)',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'approximated',
    text: 'native',
    embeddedFonts: true,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: true },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: true,
    cropMarks: true,
    printerMarks: true,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'blocked',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  'pdf-x1a': {
    format: 'pdf-x1a',
    label: 'PDF/X-1a',
    supported: true,
    reasonUnsupported: undefined,
    browser: false,
    desktop: true,
    transparency: false,
    vector: 'approximated',
    text: 'native',
    embeddedFonts: true,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: false, cmyk: true, grayscale: true, spotColors: true },
    alpha: false,
    animation: false,
    multiPage: false,
    bleed: true,
    cropMarks: true,
    printerMarks: true,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'blocked',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  'pdf-x3': {
    format: 'pdf-x3',
    label: 'PDF/X-3',
    supported: false,
    reasonUnsupported: 'PDF/X-3 is not implemented (PDF/X-4 covers the ICC-managed use case).',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'approximated',
    text: 'native',
    embeddedFonts: true,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: true, grayscale: true, spotColors: true },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: true,
    cropMarks: true,
    printerMarks: true,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'blocked',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  'pdf-x4': {
    format: 'pdf-x4',
    label: 'PDF/X-4',
    supported: true,
    reasonUnsupported: undefined,
    browser: false,
    desktop: true,
    transparency: true,
    vector: 'approximated',
    text: 'native',
    embeddedFonts: true,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: true },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: true,
    cropMarks: true,
    printerMarks: true,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'blocked',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  tiff: {
    format: 'tiff',
    label: 'TIFF',
    supported: false,
    reasonUnsupported: 'No TIFF encoder is implemented.',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: true, grayscale: true, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: true,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  bmp: {
    format: 'bmp',
    label: 'BMP',
    supported: false,
    reasonUnsupported: 'No BMP encoder is implemented.',
    browser: false,
    desktop: false,
    transparency: false,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: false,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  ico: {
    format: 'ico',
    label: 'ICO',
    supported: false,
    reasonUnsupported: 'No ICO encoder is implemented.',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'rasterized',
    text: 'rasterized',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: true,
    lossless: true,
    highBitDepth: false,
    masks: 'rasterized',
    blendModes: 'rasterized',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 256,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: true,
    codegen: false,
  },
  eps: {
    format: 'eps',
    label: 'EPS',
    supported: false,
    reasonUnsupported: 'No EPS encoder is implemented.',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'native',
    text: 'outline',
    embeddedFonts: true,
    outlinedFonts: true,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: true, grayscale: true, spotColors: true },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: true,
    cropMarks: true,
    printerMarks: true,
    metadata: true,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'flatten',
    filters: 'rasterized',
    adjustmentLayers: 'rasterize',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: false,
  },
  psd: {
    format: 'psd',
    label: 'PSD',
    supported: false,
    reasonUnsupported: 'No PSD encoder is implemented.',
    browser: false,
    desktop: false,
    transparency: true,
    vector: 'rasterized',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: true,
    iccEmbedding: true,
    colorSpaces: { rgb: true, cmyk: true, grayscale: true, spotColors: true },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: true,
    compression: true,
    lossless: true,
    highBitDepth: true,
    masks: 'native',
    blendModes: 'native',
    filters: 'native',
    adjustmentLayers: 'native',
    maxDimensions: 30_000,
    maxPageCount: 1,
    needsEngine: true,
    rasterizedByDefault: false,
    codegen: false,
  },
  json: {
    format: 'json',
    label: 'JSON',
    supported: false,
    reasonUnsupported: 'No standalone JSON export format is implemented (use package export).',
    browser: false,
    desktop: false,
    transparency: false,
    vector: 'blocked',
    text: 'blocked',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: false,
    embeddedImages: false,
    iccEmbedding: false,
    colorSpaces: { rgb: false, cmyk: false, grayscale: false, spotColors: false },
    alpha: false,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'blocked',
    blendModes: 'blocked',
    filters: 'blocked',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 0,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
  css: {
    format: 'css',
    label: 'CSS',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: true,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'native',
    filters: 'approximated',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
  html: {
    format: 'html',
    label: 'HTML',
    supported: false,
    reasonUnsupported: 'No standalone HTML export format is implemented.',
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: true,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'native',
    filters: 'approximated',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
  react: {
    format: 'react',
    label: 'React',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: true,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'native',
    filters: 'approximated',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
  flutter: {
    format: 'flutter',
    label: 'Flutter',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: true,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'native',
    filters: 'approximated',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
  swiftui: {
    format: 'swiftui',
    label: 'SwiftUI',
    supported: true,
    browser: true,
    desktop: true,
    transparency: true,
    vector: 'native',
    text: 'native',
    embeddedFonts: false,
    outlinedFonts: false,
    linkedImages: true,
    embeddedImages: true,
    iccEmbedding: false,
    colorSpaces: { rgb: true, cmyk: false, grayscale: false, spotColors: false },
    alpha: true,
    animation: false,
    multiPage: false,
    bleed: false,
    cropMarks: false,
    printerMarks: false,
    metadata: false,
    compression: false,
    lossless: true,
    highBitDepth: false,
    masks: 'flatten',
    blendModes: 'native',
    filters: 'approximated',
    adjustmentLayers: 'blocked',
    maxDimensions: 0,
    maxPageCount: 1,
    needsEngine: false,
    rasterizedByDefault: false,
    codegen: true,
  },
};

export type PlatformKind = 'web' | 'tauri' | 'memory';

/**
 * The capability contract for a format on an active platform. Returns the
 * platform-clipped capability (a desktop-only format reports `browser: false`
 * when the active platform is web — callers should treat that as unavailable).
 */
export function capabilitiesForFormat(
  format: ExportFormat,
  platform: PlatformKind = 'web',
): FormatCapability {
  const base = FORMAT_CAPABILITIES[format];
  if (!base) {
    throw new Error(`No capability contract for format: ${String(format)}`);
  }
  if (platform === 'web') {
    return { ...base, browser: base.browser, desktop: base.desktop };
  }
  return base;
}

export function formatSupportedOnPlatform(
  format: ExportFormat,
  platform: PlatformKind = 'web',
): boolean {
  const cap = FORMAT_CAPABILITIES[format];
  if (!cap.supported) return false;
  return platform === 'tauri' ? cap.desktop : cap.browser;
}

/** Formats the UI may present for the active platform (supported and reachable). */
export function supportedFormats(platform: PlatformKind = 'web'): ExportFormat[] {
  return (Object.keys(FORMAT_CAPABILITIES) as ExportFormat[]).filter((format) =>
    formatSupportedOnPlatform(format, platform),
  );
}
