/**
 * SAM2-driven selective recoloring — generates a mask via SAM2 prompts,
 * then applies color modification within that mask.
 *
 * This module bridges the SAM2 segmentation system with the colorization
 * pipeline, providing a complete "select subject → recolor" workflow.
 *
 * The mask is generated from user prompts (point clicks, box selection),
 * cached for iterative refinement, and then applied as a selective
 * recolor operation preserving highlights, shadows, and texture.
 *
 * Research basis:
 *   - SAM2 (Kirillov et al., 2023): Segment Anything Model 2 for
 *     interactive segmentation with point/box prompts.
 *   - Reinhard et al. (2001): LAB-space color transfer for luminance-
 *     preserving recolor within mask regions.
 */
import type { ColorizationResultContract } from './colorizationRequest';
import { selectiveRecolor } from './recolor';

// ---------------------------------------------------------------------------
// SAM2 mask generation result
// ---------------------------------------------------------------------------

export interface Sam2MaskResult {
  /** Binary mask (0 or 255 per pixel). */
  mask: Uint8Array;
  width: number;
  height: number;
  /** Model confidence (IoU estimate). */
  confidence: number;
  /** All mask candidates from the decoder. */
  candidates: Array<{
    mask: Uint8Array;
    width: number;
    height: number;
    iouScore: number;
  }>;
  /** Index of the selected (best) mask. */
  selectedIndex: number;
  /** Low-res mask logits for iterative refinement. */
  lowResMask?: { data: Float32Array; width: number; height: number };
}

// ---------------------------------------------------------------------------
// Recolor parameters
// ---------------------------------------------------------------------------

export interface SelectiveRecolorParams {
  /** Target hue rotation in degrees. */
  targetHue?: number;
  /** Saturation scale factor (1 = unchanged). */
  saturationScale?: number;
  /** Luminance preservation 0-1 (1 = fully preserve original luminance). */
  luminancePreservation?: number;
  /** Blend strength 0-1 (1 = full recolor, 0 = no change). */
  blendStrength?: number;
  /** Edge cleanup: feather radius in pixels. */
  edgeFeather?: number;
  /** Edge cleanup: expand/contract mask by N pixels. */
  edgeExpand?: number;
}

// ---------------------------------------------------------------------------
// SAM2 + Recolor combined operation
// ---------------------------------------------------------------------------

/**
 * Apply selective recoloring using a pre-generated SAM2 mask.
 *
 * This is the "apply" step of the SAM2 recolor workflow. The mask
 * should have been generated by the SAM2 encoder/decoder pipeline
 * (via useSam2Segmentation or the inference worker).
 *
 * @param sourceData - The original image pixels
 * @param mask - SAM2-generated mask (0-255 alpha per pixel)
 * @param maskWidth - Mask width (must match sourceData dimensions)
 * @param maskHeight - Mask height (must match sourceData dimensions)
 * @param params - Recolor parameters
 * @returns The recolored ImageData
 */
export function applySelectiveRecolor(
  sourceData: ImageData,
  mask: Uint8Array,
  maskWidth: number,
  maskHeight: number,
  params: SelectiveRecolorParams = {},
): ImageData {
  const {
    targetHue = 0,
    saturationScale = 1,
    luminancePreservation = 1,
    blendStrength = 1,
  } = params;

  // If blend is 0, return source unchanged
  if (blendStrength <= 0) return sourceData;

  // Apply recolor with full parameters
  const recolored = selectiveRecolor(
    sourceData,
    mask,
    maskWidth,
    maskHeight,
    targetHue,
    saturationScale,
    luminancePreservation,
  );

  // Blend with original based on strength
  if (blendStrength >= 1) return recolored;

  const { width, height, data } = sourceData;
  const out = new ImageData(width, height);
  const outData = out.data;
  const recData = recolored.data;
  const t = blendStrength;

  for (let i = 0; i < width * height; i++) {
    const idx = i * 4;
    outData[idx] = Math.round(data[idx]! * (1 - t) + recData[idx]! * t);
    outData[idx + 1] = Math.round(data[idx + 1]! * (1 - t) + recData[idx + 1]! * t);
    outData[idx + 2] = Math.round(data[idx + 2]! * (1 - t) + recData[idx + 2]! * t);
    outData[idx + 3] = data[idx + 3]!;
  }

  return out;
}

/**
 * Create a colorization result from a SAM2 mask + selective recolor.
 *
 * Combines mask generation and recolor into a single pipeline result
 * for the unified request/response contract.
 */
export function sam2RecolorResult(
  sourceData: ImageData,
  maskResult: Sam2MaskResult,
  params: SelectiveRecolorParams,
  requestId: string,
  sourceRevision: number,
  startTime: number,
): ColorizationResultContract {
  const recolored = applySelectiveRecolor(
    sourceData,
    maskResult.mask,
    maskResult.width,
    maskResult.height,
    params,
  );

  return {
    requestId,
    sourceRevision,
    dispatchedAt: startTime,
    imageData: recolored,
    workflow: 'selective-recolor',
    modelUsed: 'sam2-hiera-tiny',
    provider: 'sam2+classical',
    elapsedMs: performance.now() - startTime,
    maskCandidates: maskResult.candidates,
    selectedMaskIndex: maskResult.selectedIndex,
    confidence: maskResult.confidence,
    lowResMask: maskResult.lowResMask,
  };
}

// ---------------------------------------------------------------------------
// Mask refinement helpers
// ---------------------------------------------------------------------------

/**
 * Apply feathering to a mask (Gaussian blur approximation).
 * Smooths mask edges for more natural recolor boundaries.
 */
export function featherMask(
  mask: Uint8Array,
  width: number,
  height: number,
  radius: number,
): Uint8Array {
  if (radius <= 0) return mask;

  const result = new Uint8Array(mask.length);
  const kernelSize = Math.ceil(radius) * 2 + 1;
  const halfKernel = Math.floor(kernelSize / 2);

  // Simple box blur approximation for feathering
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let sum = 0;
      let count = 0;

      for (let ky = -halfKernel; ky <= halfKernel; ky++) {
        for (let kx = -halfKernel; kx <= halfKernel; kx++) {
          const sx = Math.min(Math.max(x + kx, 0), width - 1);
          const sy = Math.min(Math.max(y + ky, 0), height - 1);
          sum += mask[sy * width + sx]!;
          count++;
        }
      }

      result[y * width + x] = Math.round(sum / count);
    }
  }

  return result;
}

/**
 * Expand or contract a mask by N pixels using distance-field-like expansion.
 * Positive values expand (grow selection), negative values contract (shrink).
 */
export function expandContractMask(
  mask: Uint8Array,
  width: number,
  height: number,
  pixels: number,
): Uint8Array {
  if (pixels === 0) return mask;

  const threshold = 128;
  const result = new Uint8Array(mask.length);
  const absPixels = Math.abs(pixels);
  const expand = pixels > 0;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = y * width + x;
      const original = mask[idx]! >= threshold;

      // Check if any pixel within radius has the opposite value
      let found = false;
      for (let dy = -absPixels; dy <= absPixels && !found; dy++) {
        for (let dx = -absPixels; dx <= absPixels && !found; dx++) {
          if (dx * dx + dy * dy > absPixels * absPixels) continue;
          const sx = Math.min(Math.max(x + dx, 0), width - 1);
          const sy = Math.min(Math.max(y + dy, 0), height - 1);
          const neighbor = mask[sy * width + sx]! >= threshold;
          if (expand ? neighbor : !neighbor) {
            found = true;
          }
        }
      }

      result[idx] = found ? (expand ? 255 : 0) : original ? 255 : 0;
    }
  }

  return result;
}

/**
 * Invert a mask.
 */
export function invertMask(mask: Uint8Array): Uint8Array {
  const result = new Uint8Array(mask.length);
  for (let i = 0; i < mask.length; i++) {
    result[i] = 255 - mask[i]!;
  }
  return result;
}
