/**
 * Versioned design operation envelope and definitions (ADR-0017/0018/0045).
 *
 * An atomic operation is a typed, deterministic mutation of the document.
 * A transaction (history step) is an ordered list of atomic operations plus
 * step metadata — see ./transaction.ts.
 *
 * Timestamps are metadata only: they never participate in ordering or
 * hashing. Replay uses (snapshot, ordered operations) deterministically.
 */
import type { Document } from '../document';
import type { NodeId } from '../types';

/** Who authored the operation. */
export type OperationActorKind = 'local-user' | 'remote-user' | 'system' | 'migration' | 'import';

/** Where the operation entered the pipeline. */
export type OperationSource =
  | 'canvas'
  | 'inspector'
  | 'layers'
  | 'history'
  | 'import'
  | 'plugin'
  | 'merge'
  | 'recovery'
  | 'api';

export interface OperationActor {
  actorId: string;
  kind: OperationActorKind;
}

export interface OperationProvenance {
  /** Source transaction or tool label for diagnostics. */
  label?: string;
  /** Optional pointer to a prior operation this one corrects. */
  revertsOperationId?: string;
}

export interface DesignOperation<TPayload = unknown> {
  /** Registry schema version (ADR-0045). */
  schemaVersion: number;
  /** Globally unique operation id (generated by the coordinator). */
  operationId: string;
  /** Registered operation type, e.g. `node.set-opacity`. */
  operationType: string;
  documentId: string;
  transactionId: string;
  actor: OperationActor;
  source: OperationSource;
  /** Revision the payload's preconditions were validated against. */
  baseRevisionId: string;
  /** Document-scoped logical sequence number (order key, never timestamps). */
  logicalSequence: number;
  affectedEntityIds: NodeId[];
  payload: TPayload;
  provenance?: OperationProvenance;
  /** Metadata only — never used for deterministic ordering or hashing. */
  createdAt?: number;
}

export type ValidationResult<T> = { ok: true; value: T } | { ok: false; errors: string[] };

export interface SummaryContext {
  /** Cap on affected-entity ids included in the summary. */
  maxAffectedEntities?: number;
}

export interface SemanticSummary {
  label: string;
  affectedEntityIds: NodeId[];
  /** One of: 'create' | 'delete' | 'modify' | 'move' | 'reorder' | 'rename' | 'group' | 'ungroup' | 'import' | 'admin'. */
  kind: string;
  /** Optional human-readable detail appended to the label. */
  detail?: string;
}

export interface OperationDefinition<TPayload = unknown> {
  type: string;
  schemaVersion: number;

  validate(payload: unknown): ValidationResult<TPayload>;
  apply(document: Document, payload: TPayload): Document;
  summarize(payload: TPayload, context: SummaryContext): SemanticSummary;
  affectedEntities(payload: TPayload): NodeId[];

  /** Optional semantic inverse descriptor (used for revert transactions). */
  invert?(before: Document, after: Document, payload: TPayload): OperationInverseDescriptor | null;

  /** Payload migration (ADR-0045); identity when absent. */
  migrate?(payload: unknown, fromVersion: number): TPayload;

  /** Optional precondition check against the current document. */
  precondition?(document: Document, payload: TPayload): string | null;

  /** Human-readable payload size guard used by the dispatcher. */
  maxPayloadBytes?: number;
}

export interface OperationInverseDescriptor {
  type: string;
  payload: unknown;
  description: string;
}

/** Limits applied by the dispatcher (ADR-0030/0045 security limits). */
export interface DispatcherLimits {
  maxOperationsPerTransaction: number;
  maxPayloadBytesPerOperation: number;
  maxAffectedEntitiesPerOperation: number;
}

export const DEFAULT_DISPATCHER_LIMITS: DispatcherLimits = {
  maxOperationsPerTransaction: 100_000,
  maxPayloadBytesPerOperation: 1_000_000,
  maxAffectedEntitiesPerOperation: 10_000,
};
