[package]
name = "varve-layout"
description = "CSS-native flex/grid/container-query layout backed by Taffy."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
varve-core = { path = "../varve-core" }
taffy = { version = "0.13", features = [] }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
