#!/usr/bin/env bash
# Generate representative PDF fixtures for validation testing
# Output: tests/fixtures/pdfs/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXTURE_DIR="$SCRIPT_DIR/../tests/fixtures/pdfs"
mkdir -p "$FIXTURE_DIR"

echo "Generating PDF fixtures..."
echo "Fixture dir: $FIXTURE_DIR"
echo ""

# These are generated by the codebase itself
echo "To generate fixtures, run:"
echo "  cargo test --workspace -- varve_print_test   # auto-generates PDFs"
echo ""
echo "Then copy generated PDFs from:"
echo "  cargo test output directory to $FIXTURE_DIR"
echo ""
echo "Expected fixtures:"
echo "  1. simple_rect.pdf - Single rectangle"
echo "  2. multi_page.pdf - Multi-page document"  
echo "  3. with_bleed.pdf - Document with bleed"
echo "  4. with_icc.pdf - Document with ICC profiles"
echo "  5. with_fonts.pdf - Document with embedded fonts"
echo "  6. with_transparency.pdf - Document with transparency"
echo "  7. cmyk_only.pdf - CMYK-only document"
echo "  8. pdfx1a.pdf - PDF/X-1a export"
echo "  9. pdfx4.pdf - PDF/X-4 export"
