#!/usr/bin/env node
/** Video F — Design → React through the real codegen panel and generated file. */
import { strict as assert } from 'node:assert';
import { createRequire } from 'node:module';
import {
  beat,
  dragAt,
  fitContent,
  openCleanEditor,
  parkPointer,
  selectLayer,
  settle,
  useTool,
} from '../core/editor.mjs';
import { capture } from '../core/run.mjs';

const require = createRequire(import.meta.url);
let generatedSource = '';
let generatedPreview = null;

await capture({
  slug: 'export-react',
  workflow: 'Design → React',
  purpose: 'A pricing-plan widget is generated by Varve, compiled, rendered and visually checked independently.',
  duration: [18, 28],
  fixture: null,

  async sequence(ctx) {
    const { page, base, begin } = ctx;
    const assertions = [];
    await openCleanEditor(page, base);
    await settle(page);

    await useTool(page, 'f');
    await dragAt(page, [0.20, 0.18], [0.80, 0.78], { steps: 14, settleMs: 220 });
    await useTool(page, 'r');
    await dragAt(page, [0.25, 0.32], [0.75, 0.66], { steps: 12, settleMs: 220 });
    await useTool(page, 't');
    await dragAt(page, [0.30, 0.38], [0.70, 0.46], { steps: 12, settleMs: 120 });
    const editor = page.getByRole('textbox', { name: /editing text/i });
    await editor.fill('Pro plan — $29 / month');
    await editor.press('Escape');
    await useTool(page, 'v');
    await selectLayer(page, /frame/i);
    await fitContent(page);
    await parkPointer(page);
    await settle(page);

    begin();
    await beat(page, 1200);
    await page.keyboard.press('Control+Shift+9');
    const codePanel = page.locator('.code-panel');
    await codePanel.waitFor({ state: 'visible', timeout: 10000 });
    await codePanel.getByRole('tab', { name: 'React', exact: true }).click();
    await page.waitForTimeout(900);
    generatedSource = (await codePanel.locator('.code-panel__line-text').allTextContents()).join('\n');
    assert.match(generatedSource, /ExportedScene/);
    assert.match(generatedSource, /<svg/);
    assertions.push(`React source was generated by the real Codegen panel (${generatedSource.length} chars)`);
    await beat(page, 1200);

    const downloadPromise = page.waitForEvent('download', { timeout: 10000 });
    await codePanel.getByRole('button', { name: 'Download' }).click();
    const download = await downloadPromise;
    assert.match(download.suggestedFilename(), /\.tsx$/);
    assertions.push(`Download produced the generated ${download.suggestedFilename()} file`);
    await beat(page, 1000);

    const ts = require('typescript');
    const compiled = ts.transpileModule(generatedSource, {
      compilerOptions: {
        jsx: ts.JsxEmit.ReactJSX,
        module: ts.ModuleKind.CommonJS,
        target: ts.ScriptTarget.ES2022,
        esModuleInterop: true,
      },
      reportDiagnostics: true,
    });
    assert.equal(compiled.diagnostics?.length ?? 0, 0, 'generated TSX has syntax diagnostics');
    const module = { exports: {} };
    new Function('exports', 'require', 'module', compiled.outputText)(module.exports, require, module);
    assert.equal(typeof module.exports.ExportedScene, 'function');
    assertions.push('generated TSX transpiled without diagnostics and exported a React component');

    const React = require('react');
    const ReactDOMServer = require('react-dom/server');
    const html = ReactDOMServer.renderToStaticMarkup(React.createElement(module.exports.ExportedScene));
    assert.match(html, /<svg/);
    assert.match(html, /<rect/);
    const independent = await page.context().browser().newContext({ viewport: { width: 900, height: 650 }, deviceScaleFactor: 1 });
    const preview = await independent.newPage();
    await preview.setContent(`<!doctype html><style>html,body{margin:0;height:100%}svg{display:block;width:100%;height:100%}</style>${html}`);
    await preview.locator('svg').waitFor({ state: 'visible', timeout: 5000 });
    generatedPreview = await preview.screenshot({ type: 'png' });
    await independent.close();
    assertions.push('the generated React component rendered in a fresh browser context');
    await parkPointer(page);
    await settle(page);
    await beat(page, 11200);
    return assertions;
  },
  artifacts: () => [
    { name: 'artifacts/pricing-plan.generated.tsx', contents: generatedSource },
    ...(generatedPreview ? [{ name: 'artifacts/pricing-plan.react-render.png', contents: generatedPreview }] : []),
  ],
  metadata: { productTruth: 'CodePanel → exportNodeToReact → downloaded TSX → independent React render' },
});
