import type { HelpArticle } from './helpTypes';

export const FAQ: Record<string, HelpArticle> = {
  'faq:rectangle': {
    id: 'faq:rectangle',
    title: 'How do I create a rectangle?',
    summary: 'Quick steps to draw a rectangle on the canvas.',
    body: 'Press R to activate the Rectangle tool, or select it from the toolbar. Click and drag on the canvas to draw the rectangle. Release the mouse to set its size. Hold Shift while dragging to create a perfect square. Hold Alt to draw from the center point outward. Use the Inspector panel to adjust corner radius, fill color, and stroke after creation.',
    keywords: ['rectangle', 'square', 'create', 'draw', 'shape', 'how'],
    category: 'FAQ',
    related: ['tool:rect', 'faq:color', 'panel:inspector'],
  },
  'faq:color': {
    id: 'faq:color',
    title: "How do I change a shape's color?",
    summary: 'Apply and modify fill colors for any shape.',
    body: 'Select the shape on the canvas, then look at the Inspector panel on the right. Find the Fill section. Click the color swatch to open the color picker. Choose a color from the picker, or type a hex value directly. You can also use the eyedropper to pick a color from anywhere on the screen. Add multiple fills by clicking the plus button, and reorder them by dragging. Each fill can have its own blend mode and opacity.',
    keywords: ['color', 'fill', 'paint', 'change', 'shape', 'how'],
    category: 'FAQ',
    related: ['tool:select', 'panel:inspector', 'faq:rectangle'],
  },
  'faq:text': {
    id: 'faq:text',
    title: 'How do I add text?',
    summary: 'Steps to create and edit text on the canvas.',
    body: 'Press T to activate the Text tool. Click on the canvas to create a text box and start typing. To edit existing text, double-click the text object on the canvas, or select it and edit the text content field in the Inspector panel. Change font family, size, weight, alignment, line height, letter spacing, and color using the Typography section of the Inspector.',
    keywords: ['text', 'add', 'type', 'font', 'edit', 'how'],
    category: 'FAQ',
    related: ['tool:text', 'panel:inspector'],
  },
  'faq:group': {
    id: 'faq:group',
    title: 'How do I group objects?',
    summary: 'Combine multiple objects into a single group.',
    body: 'Select multiple objects by holding Shift and clicking each one, or drag a selection marquee around them. Press Ctrl+G to group them. Groups act as a single unit for moving, scaling, and transforming. Double-click a group to enter it and edit individual objects. Press Ctrl+Shift+G to ungroup. Ungrouping restores each object as an independent layer.',
    keywords: ['group', 'ungroup', 'combine', 'objects', 'selection', 'how'],
    category: 'FAQ',
    related: ['tool:select', 'panel:layers'],
  },
  'faq:export': {
    id: 'faq:export',
    title: 'How do I export my design?',
    summary: 'Export your design as PNG, SVG, PDF, or code.',
    body: 'Press Ctrl+E or go to File > Export to open the Export dialog. Choose your format: PNG for raster images with transparency, SVG for scalable vector graphics, PDF for print-ready documents, or code export for React, Flutter, or SwiftUI. Select whether to export the entire document or a specific frame. Configure format-specific options like scale, quality, and color profile. Click Export and choose a destination.',
    keywords: ['export', 'save', 'png', 'svg', 'pdf', 'code', 'how'],
    category: 'FAQ',
    related: ['export:overview', 'export:png', 'export:svg', 'export:code', 'export:pdf'],
  },
  'faq:undo': {
    id: 'faq:undo',
    title: 'How do I undo an action?',
    summary: 'Undo and redo changes in your document.',
    body: 'Press Ctrl+Z to undo the last action. Continue pressing to undo further back in your history. Press Ctrl+Shift+Z to redo an undone action. The undo history is maintained per document and persists during the editing session. Undo covers all operations including creation, deletion, modification, and rearrangement of objects.',
    keywords: ['undo', 'redo', 'history', 'revert', 'mistake', 'how'],
    category: 'FAQ',
    related: ['getting-started:keys'],
  },
  'faq:save': {
    id: 'faq:save',
    title: 'How do I save my work?',
    summary: 'Save your document manually or rely on auto-save.',
    body: "Varve auto-saves your work periodically as you design, creating recovery points without interrupting you. For manual saves, press Ctrl+S or go to File > Save. Save As (Ctrl+Shift+S) creates a copy with a new name. Documents are saved in Varve's native JSON format. The document name appears in the center of the menubar and can be edited by clicking on it.",
    keywords: ['save', 'auto-save', 'persist', 'file', 'how'],
    category: 'FAQ',
    related: ['getting-started:saving', 'faq:recover'],
  },
  'faq:recover': {
    id: 'faq:recover',
    title: 'How do I recover lost work?',
    summary: 'Restore your work after a crash or accidental close.',
    body: 'If Varve closes unexpectedly, recovery sessions are automatically created. When you reopen the editor, a Recovery dialog appears listing all recoverable sessions. Click Restore next to a session to recover it, or Restore All to recover everything. Recovery sessions are kept for 7 days before being automatically cleaned up. You can also discard individual sessions or all sessions at once.',
    keywords: ['recover', 'crash', 'restore', 'lost', 'session', 'how'],
    category: 'FAQ',
    related: ['faq:save', 'getting-started:saving'],
  },
  'faq:prototype': {
    id: 'faq:prototype',
    title: 'How do I create a prototype?',
    summary: 'Build interactive prototypes from your designs.',
    body: 'Switch to prototype mode by clicking the Prototype tab or pressing Ctrl+Shift+P. Select a frame (screen) and use the connection handle to drag a wire to another screen. Define the trigger (tap, drag, hover, timer) and transition effect (dissolve, slide, push). Press Ctrl+Shift+P again to preview your prototype in fullscreen. Navigate through screens by clicking interaction hotspots.',
    keywords: ['prototype', 'interactive', 'preview', 'flow', 'navigation', 'how'],
    category: 'FAQ',
    related: ['panel:prototype', 'panel:timeline'],
  },
  'faq:shortcuts': {
    id: 'faq:shortcuts',
    title: 'How do I use keyboard shortcuts?',
    summary: 'Find and customize keyboard shortcuts.',
    body: 'Press Ctrl+/ to open the Command Palette, which lists all available shortcuts and lets you search by name. Press F1 to open the full Help Browser and browse the Shortcuts category for a complete reference. Many shortcuts are shown next to their menu item in the menubar. Tool shortcuts show their key in the tooltip when hovering over toolbar buttons.',
    keywords: ['shortcuts', 'customize', 'hotkeys', 'palette', 'how'],
    category: 'FAQ',
    related: ['shortcuts', 'getting-started:keys'],
  },
};
