import type { HelpArticle } from './helpTypes';

export const GETTING_STARTED: Record<string, HelpArticle> = {
  'getting-started:overview': {
    id: 'getting-started:overview',
    title: 'What is Varve?',
    summary: 'An overview of the local-first, cross-platform design suite.',
    body: 'Varve is a local-first, cross-platform design suite for creating user interfaces, prototypes, illustrations, and print designs. Unlike cloud-only tools, Varve runs natively on your machine with a Rust-powered engine for high performance. Your data stays on your device — no mandatory cloud sync, no account required. Varve supports vector editing, raster image manipulation, typography, animation, prototyping, and print production in a single application. The editor provides a canvas-based workspace with layers, inspector panels, timeline animation, and prototype preview.',
    keywords: ['varve', 'overview', 'design', 'local-first', 'cross-platform', 'introduction'],
    category: 'Getting Started',
    related: ['getting-started:creating', 'getting-started:interface'],
  },
  'getting-started:creating': {
    id: 'getting-started:creating',
    title: 'Creating a Document',
    summary: 'How to create new documents and choose the right settings.',
    body: 'To create a new document, go to File > New or press Ctrl+N. The New File dialog gives you several options: Blank canvas creates an empty document where you can start designing immediately. Print documents (A4, A3, Letter) set up the canvas for print production with CMYK color mode and bleed guides. You can also choose from frame presets for phone, tablet, desktop, and social media sizes after creating a blank document. Set custom dimensions, units (px, mm, cm, in), and color mode before creating. New documents are automatically named "Untitled" and saved to your drafts.',
    keywords: ['new', 'document', 'create', 'file', 'canvas', 'blank'],
    category: 'Getting Started',
    related: ['getting-started:interface', 'getting-started:saving', 'faq:export'],
  },
  'getting-started:interface': {
    id: 'getting-started:interface',
    title: 'The Editor Interface',
    summary: 'Overview of the toolbar, canvas, panels, and menubar.',
    body: 'The Varve editor is organized into several areas: The Menubar at the top provides file operations, editing commands, view options, and help. The Toolbar (floating) contains drawing and selection tools. The Canvas is the main work area where you create and manipulate designs. The Layers Panel (left sidebar) shows the hierarchy of all objects in your document. The Inspector Panel (right sidebar) displays editable properties for the selected object. The Status Bar at the bottom shows zoom level, canvas mode, and toggle controls. Page navigation appears below the canvas for multi-page documents.',
    keywords: ['interface', 'layout', 'editor', 'canvas', 'toolbar', 'panels', 'menubar'],
    category: 'Getting Started',
    related: [
      'getting-started:overview',
      'getting-started:keys',
      'panel:layers',
      'panel:inspector',
    ],
  },
  'getting-started:saving': {
    id: 'getting-started:saving',
    title: 'Saving and Opening',
    summary: 'Auto-save, recovery, and file management.',
    body: 'Varve automatically saves your work as you design. Auto-save creates recovery points that can be restored if the application closes unexpectedly. To manually save, press Ctrl+S or go to File > Save. Use Save As (Ctrl+Shift+S) to create a copy with a different name or location. Varve saves documents in its native JSON format (.varve). Opening a file: press Ctrl+O or go to File > Open to load a saved document. The Home screen lists your recent documents for quick access. Recovery sessions appear automatically after a crash, offering to restore your work with a single click.',
    keywords: ['save', 'open', 'auto-save', 'recovery', 'file', 'load', 'persist'],
    category: 'Getting Started',
    related: ['getting-started:creating', 'faq:save', 'faq:recover'],
  },
  'getting-started:keys': {
    id: 'getting-started:keys',
    title: 'Keyboard Basics',
    summary: 'Essential shortcuts for beginners to speed up your workflow.',
    body: 'Master these essential shortcuts to work faster in Varve: Tool shortcuts: V (Select), R (Rectangle), E (Ellipse), L (Line), T (Text), F (Frame), P (Pen), Shift+P (Pencil), H (Hand), Z (Zoom). Edit shortcuts: Ctrl+Z (Undo), Ctrl+Shift+Z (Redo), Ctrl+C (Copy), Ctrl+X (Cut), Ctrl+V (Paste), Ctrl+D (Duplicate), Delete (Remove). File shortcuts: Ctrl+N (New), Ctrl+O (Open), Ctrl+S (Save). View shortcuts: Ctrl+0 (Zoom to 100%), Ctrl+= (Zoom In), Ctrl+- (Zoom Out), Ctrl+B (Toggle Layers Panel). Press F1 to open the full help browser with complete shortcut reference.',
    keywords: ['shortcuts', 'keys', 'beginner', 'basics', 'essential', 'quick'],
    category: 'Getting Started',
    related: ['shortcuts', 'getting-started:overview', 'faq:shortcuts'],
  },
  'getting-started:workspaces': {
    id: 'getting-started:workspaces',
    title: 'Workspaces and Customization',
    summary: 'Switch task-focused workspaces and customize what each one shows.',
    body: 'Varve organizes the editor into eight task-focused workspaces: Design, Print, Draw, Photo, Motion, Logo, Email, and Codegen. Switch with the workspace tabs in the menubar or with Ctrl+Shift+1 through Ctrl+Shift+7 and Ctrl+Shift+9. A workspace changes only the chrome — panels, toolbar composition, inspector tabs, status sections, canvas overlays, and the default tool. The document, selection, viewport, and undo history are shared across every workspace, and the active workspace is application-global rather than saved per document. To customize the current workspace, open View > Customize Workspace. Changes apply immediately and are remembered for that workspace: panel visibility, toolbar tools (including flyout members such as boolean operations), inspector tabs, status bar sections, editor chrome (floating toolbar, status bar, document tabs), and panel widths. Select, Hand, and Zoom cannot be hidden because they are the recovery and navigation tools. To recover an accidentally hidden layout, use View > Show All Panels. Reset Workspace to Default restores the current mode; Reset All Workspaces asks for confirmation first. The customize dialog also offers a reset confirmation and writes every change to durable storage, so customizations survive restarts even where browser storage is unreliable.',
    keywords: ['workspace', 'customize', 'panels', 'toolbar', 'reset', 'mode', 'layout'],
    category: 'Getting Started',
    related: ['getting-started:interface', 'getting-started:keys', 'getting-started:layouts'],
  },
  'getting-started:layouts': {
    id: 'getting-started:layouts',
    title: 'Saving and Recovering Layouts',
    summary: 'Save named arrangements, apply them later, and recover after a reset.',
    body: 'View > Manage Layouts opens the named-layout manager. A layout saves how the current workspace is arranged: panel visibility and widths, inspector tabs, status bar sections, toolbar tools, and editor chrome. Applying a layout replaces the active workspace arrangement; it never switches workspace, and it never changes the document, selection, or undo history. The manager includes three built-in templates. Default restores the mode built-in arrangement. Every panel reveals every panel, which is the fastest recovery when something is hidden. Focus canvas hides the panels, status bar, and document tabs while keeping the floating toolbar; the menubar and command palette stay reachable, so it is always reversible. You can also save the current arrangement under a name, update or rename a saved layout, duplicate it, copy it as portable JSON, or import a layout JSON document. Duplicate names are rejected instead of silently overwritten, imports are validated and can only reference registered panels and tools, and deleting a layout asks for confirmation. Resetting a workspace snapshots the arrangement first; Manage Layouts shows a Recovery section with Restore until the next reset, so reset is not a one-way door. Layouts contain no file paths or machine geometry and are never written into design documents.',
    keywords: [
      'layout',
      'save layout',
      'named layout',
      'manage layouts',
      'recovery',
      'import',
      'export',
      'focus canvas',
    ],
    category: 'Getting Started',
    related: ['getting-started:workspaces', 'getting-started:interface', 'faq:save'],
  },
};
