import type { HelpArticle } from './helpTypes';

export const SHORTCUTS_REFERENCE: HelpArticle = {
  id: 'shortcuts',
  title: 'Keyboard Shortcuts Reference',
  summary: 'Complete list of all keyboard shortcuts in Strata.',
  body: [
    'File Operations:',
    'Ctrl+N - New document',
    'Ctrl+O - Open file',
    'Ctrl+S - Save',
    'Ctrl+Shift+S - Save As',
    'Ctrl+E - Export',
    'Ctrl+Shift+E - Export SVG',
    'Ctrl+W - Close tab',
    'Ctrl+Shift+H - Go to Home',
    '',
    'Edit Operations:',
    'Ctrl+Z - Undo',
    'Ctrl+Shift+Z - Redo',
    'Ctrl+C - Copy',
    'Ctrl+X - Cut',
    'Ctrl+V - Paste',
    'Ctrl+D - Duplicate',
    'Delete/Backspace - Delete selected',
    'Ctrl+A - Select All',
    '',
    'View Operations:',
    'Ctrl+0 - Zoom to 100%',
    'Ctrl+= - Zoom In',
    'Ctrl+- - Zoom Out',
    'Shift+1 - Fit All',
    'Shift+2 - Fit Selection',
    '1-6 - Zoom presets (50%, 75%, 100%, 150%, 200%, 400%)',
    'Ctrl+B - Toggle Layers Panel',
    'Ctrl+Shift+B - Toggle Inspector Panel',
    ', (comma) - Toggle Snap',
    'Ctrl+/ - Command Palette',
    'Ctrl+; - Quick Actions',
    'Ctrl+Shift+O - Outline Mode',
    'Ctrl+Shift+R - Preview Mode',
    'Escape - Full Render Mode',
    'Ctrl+Shift+Y - Toggle Soft Proofing',
    '',
    'Tool Shortcuts:',
    'V - Select Tool',
    'R - Rectangle Tool',
    'E (or O) - Ellipse Tool',
    'L - Line Tool',
    'T - Text Tool',
    'F - Frame Tool',
    'P - Pen Tool',
    'N - Pencil Tool',
    'H - Hand Tool',
    'Z - Zoom Tool',
    'I - Inspect Tool',
    '',
    'Object Operations:',
    'Ctrl+G - Group',
    'Ctrl+Shift+G - Ungroup',
    'Ctrl+] - Bring Forward',
    'Ctrl+Shift+] - Bring to Front',
    'Ctrl+[ - Send Backward',
    'Ctrl+Shift+[ - Send to Back',
    'H - Flip Horizontal',
    'Shift+V - Flip Vertical',
    '= (equals) - Bind field to variable',
    'Arrow keys - Nudge 1px',
    'Shift+Arrow keys - Nudge 10px',
    '',
    'Boolean Operations:',
    'Ctrl+Alt+U - Union',
    'Ctrl+Alt+S - Subtract',
    'Ctrl+Alt+I - Intersect',
    'Ctrl+Alt+X - Exclude',
    '',
    'Alignment:',
    'Ctrl+Shift+ArrowLeft - Align Left',
    'Ctrl+Shift+ArrowRight - Align Right',
    'Ctrl+Shift+ArrowUp - Align Top',
    'Ctrl+Shift+ArrowDown - Align Bottom',
    'Ctrl+Shift+Home - Align Horizontal Center',
    'Ctrl+Shift+PageUp - Align Vertical Center',
    'Ctrl+Alt+H - Distribute Horizontally',
    'Ctrl+Alt+V - Distribute Vertically',
  ].join('\n'),
  keywords: [
    'shortcuts', 'keys', 'keyboard', 'hotkeys', 'reference',
    'ctrl', 'shift', 'alt', 'command', 'meta',
  ],
  category: 'Shortcuts',
  related: ['getting-started:keys', 'faq:shortcuts'],
};
