import type { HelpArticle } from './helpTypes';

export const SHORTCUTS_REFERENCE: HelpArticle = {
  id: 'shortcuts',
  title: 'Keyboard Shortcuts Reference',
  summary: 'Complete list of all keyboard shortcuts in Varve.',
  body: [
    'File Operations:',
    'Ctrl+N - New document',
    'Ctrl+O - Open file',
    'Ctrl+S - Save',
    'Ctrl+Shift+S - Save As',
    'Ctrl+E - Export',
    'Ctrl+Shift+E - Export SVG',
    'Ctrl+W - Close tab',
    'Ctrl+Shift+H - Go to Home',
    '',
    'Edit Operations:',
    'Ctrl+Z - Undo',
    'Ctrl+Shift+Z - Redo',
    'Ctrl+C - Copy',
    'Ctrl+X - Cut',
    'Ctrl+V - Paste',
    'Ctrl+D - Duplicate',
    'Delete/Backspace - Delete selected',
    'Ctrl+A - Select All',
    '',
    'View Operations:',
    'Ctrl+0 - Zoom to 100%',
    'Ctrl+= - Zoom In',
    'Ctrl+- - Zoom Out',
    'Shift+1 - Fit All',
    'Shift+2 - Fit Selection',
    '1-6 - Zoom presets (50%, 75%, 100%, 150%, 200%, 400%)',
    'Ctrl+B - Toggle Layers Panel',
    'Ctrl+Shift+B - Toggle Inspector Panel in the desktop app; browsers may reserve it for the bookmarks bar, so use the View menu in the browser',
    ', (comma) - Toggle Snap',
    'Ctrl+/ - Command Palette',
    'Ctrl+; - Quick Actions',
    'Ctrl+Shift+O - Outline Mode',
    'Ctrl+Shift+R - Preview Mode',
    'Escape - Full Render Mode',
    'Ctrl+Shift+Y - Toggle Soft Proofing',
    'Ctrl+Shift+M - Toggle Minimap in the desktop app; browsers may reserve it for profile switching, so use the View menu in the browser',
    'Workspace switcher order is Design, Print, Draw, Photo, Motion, Email; tabs are marked 1–6, and Ctrl+Shift+1…6 selects the matching workspace',
    'Ctrl+Shift+7 - Show Logo Tools in Design',
    'Ctrl+Alt+Shift+L - Toggle Logo Tools; opening from another workspace switches to Design',
    'Ctrl+Shift+8 - Show the shared Code panel in the current workspace',
    'Ctrl+Shift+J - Toggle the shared Code panel in the desktop app; browsers may reserve it for Developer Tools, so use Ctrl+Shift+8 or View > Panels > Code Panel in the browser',
    'The six workspaces use the ordered 1–6 sequence; Logo and Code are actions at 7 and 8, not additional workspace tabs',
    'On macOS, use Command+Shift with the workspace and Logo number shortcuts; use Command+Option+Shift+L for the Logo Tools toggle. Chrome may reserve Command+Shift+B/M for browser UI, and Command+Shift+J opens Downloads, so use the View menu for Inspector and Minimap and Command+Shift+8 or View > Panels > Code Panel for Code in the browser',
    '',
    'Tool Shortcuts:',
    'V - Select Tool',
    'R - Rectangle Tool',
    'E (or O) - Ellipse Tool',
    'L - Line Tool',
    'T - Text Tool',
    'F - Frame Tool',
    'P - Pen Tool',
    'Shift+P - Pencil Tool',
    'H - Hand Tool',
    'Z - Zoom Tool',
    'I - Inspect Tool',
    '',
    'Object Operations:',
    'Ctrl+G - Group',
    'Ctrl+Shift+G - Ungroup',
    'Ctrl+] - Bring Forward',
    'Ctrl+Shift+] - Bring to Front',
    'Ctrl+[ - Send Backward',
    'Ctrl+Shift+[ - Send to Back',
    'H - Flip Horizontal',
    'Shift+V - Flip Vertical',
    '= (equals) - Bind field to variable',
    'Arrow keys - Nudge 1px',
    'Shift+Arrow keys - Nudge 10px',
    '',
    'Boolean Operations:',
    'Ctrl+Alt+U - Union',
    'Ctrl+Alt+S - Subtract',
    'Ctrl+Alt+I - Intersect',
    'Ctrl+Alt+X - Exclude',
    '',
    'Alignment:',
    'Ctrl+Shift+ArrowLeft - Align Left',
    'Ctrl+Shift+ArrowRight - Align Right',
    'Ctrl+Shift+ArrowUp - Align Top',
    'Ctrl+Shift+ArrowDown - Align Bottom',
    'Ctrl+Shift+Home - Align Horizontal Center',
    'Ctrl+Shift+PageUp - Align Vertical Center',
    'Ctrl+Alt+H - Distribute Horizontally',
    'Ctrl+Alt+V - Distribute Vertically',
  ].join('\n'),
  keywords: [
    'shortcuts',
    'keys',
    'keyboard',
    'hotkeys',
    'reference',
    'ctrl',
    'shift',
    'alt',
    'command',
    'meta',
  ],
  category: 'Shortcuts',
  related: ['getting-started:keys', 'faq:shortcuts'],
};
