import type { HelpArticle } from './helpTypes';

export const TOOLS: Record<string, HelpArticle> = {
  'tool:select': {
    id: 'tool:select',
    title: 'Select Tool (V)',
    summary: 'Select, move, and resize objects on the canvas.',
    body: 'Click on any object to select it. Drag to move. Drag handles to resize. Hold Shift to add to selection or toggle selection of individual objects. Double-click a group or frame to enter it. Double-click a path to edit its nodes with the Node Edit tool.',
    keywords: ['select', 'move', 'drag', 'resize', 'transform', 'v'],
    category: 'Tools',
    related: ['tool:rect', 'panel:layers'],
  },
  'tool:rect': {
    id: 'tool:rect',
    title: 'Rectangle Tool (R)',
    summary: 'Draw rectangles and squares.',
    body: 'Click and drag on the canvas to draw a rectangle. Hold Shift to constrain to a square. Hold Alt/Option to draw from center. Change corner radius in the Inspector panel. Rectangles can have multiple fills, strokes, and effects applied.',
    keywords: ['rectangle', 'square', 'shape', 'draw', 'r'],
    category: 'Tools',
    related: ['tool:ellipse', 'tool:select'],
  },
  'tool:ellipse': {
    id: 'tool:ellipse',
    title: 'Ellipse Tool (E)',
    summary: 'Draw ellipses and circles.',
    body: 'Click and drag to draw an ellipse. Hold Shift for a perfect circle. Hold Alt/Option to draw from center. Ellipses support all fill types including solid colors, gradients, and image fills.',
    keywords: ['ellipse', 'circle', 'oval', 'shape', 'draw', 'e'],
    category: 'Tools',
    related: ['tool:rect', 'tool:select'],
  },
  'tool:line': {
    id: 'tool:line',
    title: 'Line Tool (L)',
    summary: 'Draw straight lines.',
    body: 'Click and drag to draw a line. Hold Shift to constrain to 45-degree angles. Change stroke weight, color, dash pattern, and end caps in the Inspector. Lines only have stroke properties, not fills.',
    keywords: ['line', 'stroke', 'draw', 'l'],
    category: 'Tools',
    related: ['tool:arrow', 'tool:pen'],
  },
  'tool:arrow': {
    id: 'tool:arrow',
    title: 'Arrow Tool',
    summary: 'Draw arrows with configurable arrowheads.',
    body: 'Click and drag to draw an arrow. Arrowheads are added automatically at the end point. Customize arrowhead style and size in the Inspector. Arrows are useful for annotations, diagrams, and flow charts.',
    keywords: ['arrow', 'line', 'pointer', 'connector'],
    category: 'Tools',
    related: ['tool:line', 'tool:pen'],
  },
  'tool:pen': {
    id: 'tool:pen',
    title: 'Pen Tool (P)',
    summary: 'Draw bezier curves and custom paths.',
    body: 'Click to create straight segments. Click and drag to create curved segments with bezier handles. Close a path by clicking the first point. Edit individual anchor points and bezier handles with the Node Edit tool (double-click a path with the Select tool).',
    keywords: ['pen', 'bezier', 'path', 'curve', 'vector', 'p'],
    category: 'Tools',
    related: ['tool:nodeEdit', 'tool:pencil'],
  },
  'tool:pencil': {
    id: 'tool:pencil',
    title: 'Pencil Tool (N)',
    summary: 'Freehand draw smooth paths.',
    body: 'Click and drag to draw freeform paths. The pencil automatically smooths your strokes using Ramer-Douglas-Peucker simplification. Edit the result with the Node Edit tool to refine bezier handles and anchor points.',
    keywords: ['pencil', 'freehand', 'draw', 'sketch', 'n'],
    category: 'Tools',
    related: ['tool:pen', 'tool:nodeEdit'],
  },
  'tool:text': {
    id: 'tool:text',
    title: 'Text Tool (T)',
    summary: 'Add and edit text on the canvas.',
    body: 'Click on the canvas to create a text box, then start typing. Edit font family, size, weight, alignment, color, line height, letter spacing, and more in the Inspector panel. Double-click any text object to edit it inline on the canvas. Text objects support OpenType features and variable font axes.',
    keywords: ['text', 'type', 'font', 'typography', 't'],
    category: 'Tools',
    related: ['panel:inspector', 'export:overview'],
  },
  'tool:frame': {
    id: 'tool:frame',
    title: 'Frame Tool (F)',
    summary: 'Create containers for organizing content.',
    body: 'Click and drag to draw a frame. Frames can contain other shapes and clip their contents. Use frames to create screens, artboards, and component containers. Frames support auto-layout for responsive designs. Apply frame presets for common device sizes.',
    keywords: ['frame', 'container', 'artboard', 'screen', 'f'],
    category: 'Tools',
    related: ['tool:rect', 'tool:select', 'panel:layers'],
  },
  'tool:hand': {
    id: 'tool:hand',
    title: 'Hand Tool (H)',
    summary: 'Pan the canvas view.',
    body: 'Click and drag to pan around the canvas. Hold the spacebar temporarily to access the Hand tool while using any other tool. Useful for navigating large documents or zoomed-in views.',
    keywords: ['hand', 'pan', 'scroll', 'navigate', 'h'],
    category: 'Tools',
    related: ['tool:zoom', 'tool:select'],
  },
  'tool:zoom': {
    id: 'tool:zoom',
    title: 'Zoom Tool (Z)',
    summary: 'Zoom in and out of the canvas.',
    body: 'Click to zoom in at the cursor position. Hold Alt and click to zoom out. Drag to create a marquee selection for zooming into a specific area. The zoom tool anchors zoom at the cursor point for precise control.',
    keywords: ['zoom', 'magnify', 'view', 'z'],
    category: 'Tools',
    related: ['tool:hand', 'getting-started:keys'],
  },
  'tool:nodeEdit': {
    id: 'tool:nodeEdit',
    title: 'Node Edit Tool',
    summary: 'Edit anchor points and bezier handles on paths.',
    body: 'Entered by double-clicking a path with the Select tool. Click an anchor point to select it. Drag to move. Click and drag bezier handles to adjust curves. Press Backspace to delete the selected anchor. Press C to toggle between corner and smooth handle types.',
    keywords: ['node', 'edit', 'anchor', 'bezier', 'handle', 'path', 'nodeedit'],
    category: 'Tools',
    related: ['tool:pen', 'tool:pencil', 'tool:select'],
  },
  'tool:inspect': {
    id: 'tool:inspect',
    title: 'Inspect Tool (I)',
    summary: 'Inspect object properties and measurements.',
    body: 'Click on any object to view its properties, dimensions, and position in a read-only overlay. The inspect tool shows measurement readouts and spec information. Useful for design handoff and quality assurance.',
    keywords: ['inspect', 'measure', 'properties', 'read-only', 'i'],
    category: 'Tools',
    related: ['tool:select', 'export:overview'],
  },
};
