export const SOURCE_SCENES = [
  {
    id: 'comic-lettering',
    file: 'comic-lettering-light.png',
    captureFile: 'comic-lettering-balloon-inspector.png',
    producer: 'tests/e2e/canvas/comic-lettering.spec.ts',
    alt: 'A speech balloon selected in Varve with editable dialogue and the Comic balloon inspector showing fit, line-shape, and tail controls',
    caption: 'Editable comic lettering with contour-aware wrapping and tail controls',
    feature: 'comic-lettering',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1280, height: 720 },
  },
  {
    id: 'patterns',
    file: 'patterns-document-alignment.png',
    captureFile: 'app-document-alignment.png',
    producer: 'tests/e2e/canvas/pattern-document-alignment.spec.ts',
    alt: 'A reusable dotted vector pattern applied to a selected shape, with repeat and document-alignment controls visible in the inspector',
    caption: 'A real pattern fill with its repeat settings and document-aligned placement',
    feature: 'patterns',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1280, height: 720 },
  },
  {
    id: 'performance-settings',
    file: 'performance-settings-dark.png',
    captureFile: 'performance-settings-dark.png',
    producer: 'tests/e2e/settings/performance-guidance.visual.spec.ts',
    alt: "Varve's Performance settings dialog in dark theme, with Automatic interactive preview selected and the local diagnostics panel below it",
    caption: 'Performance settings with opt-in local diagnostics',
    feature: 'performance',
    theme: 'dark',
    kind: 'detail',
  },
  {
    id: 'design-tokens-contrast',
    file: 'design-tokens-alias-bound-light.png',
    captureFile: 'curly-alias-bound.png',
    producer: 'tests/e2e/inspector/token-binding-runtime.spec.ts',
    alt: 'Varve showing a blue rectangle whose fill is linked to the semantic.brand.curlyAlias token, with the resolved colour painted on the canvas',
    caption:
      'A source alias bound through the Inspector, with its resolved colour painted on the canvas',
    feature: 'design-tokens',
    theme: 'light',
    kind: 'full',
  },
  // Reviewed captures promoted from the specs that own the surface. Their
  // published bytes are committed under public/screenshots; `producer` names
  // the spec the capture came from, and `viewport` is the measured frame, so
  // the geometry check holds for frames that are not the 1440x900 default.
  {
    id: 'effect-studio-desktop-light',
    file: 'effect-studio-desktop-light.png',
    captureFile: 'effect-studio-light-1440x900.png',
    producer: 'tests/e2e/workspace/effect-studio.spec.ts',
    alt: 'Effect Studio on a wide screen, with the treatment preview, gallery, and applied stack arranged side by side.',
    caption: 'Wide workspace with preview, treatments, and editable stack in view.',
    feature: 'effect-studio',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1440, height: 900 },
  },
  {
    id: 'effect-studio-mobile-light',
    file: 'effect-studio-mobile-light.png',
    captureFile: 'effect-studio-light-390x844.png',
    producer: 'tests/e2e/workspace/effect-studio.spec.ts',
    alt: 'Effect Studio on a phone-sized screen, reflowed into a single scrollable layout with touch-sized controls.',
    caption: 'Phone layout keeps the same order in one scrollable flow.',
    feature: 'effect-studio',
    theme: 'light',
    kind: 'full',
    viewport: { width: 390, height: 844 },
  },
  {
    id: 'illustration-linework-flats',
    file: 'illustration-linework-flats.png',
    captureFile: 'hybrid-linework-flats-filled.png',
    producer: 'tests/e2e/canvas/raster-magic-wand.spec.ts',
    alt: 'Varve showing a red apple flat beneath editable black linework on a separate Flats layer',
    caption:
      'Visible-artwork Magic Wand selects inside the ink while a separate Flats layer carries the colour.',
    feature: 'strokes',
    theme: 'light',
    kind: 'full',
    // Measured from the published capture. The page's own `width`/`height`
    // attributes said 1440x1000; the file is 1280x800 — one of the drifts the
    // manifest removes by becoming the single source for geometry.
    viewport: { width: 1280, height: 800 },
  },
  {
    id: 'illustration-clipped-shading',
    file: 'illustration-clipped-shading.png',
    captureFile: 'illustration-clipped-flats-shading.png',
    producer: 'tests/e2e/canvas/raster-magic-wand.spec.ts',
    alt: 'Varve Design workspace with red shading clipped inside a blue painted shape on a separate Shading layer',
    caption:
      'The separate Shading layer stays within the source raster alpha across undo, save/reopen, and transparent PNG export.',
    feature: 'strokes',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1440, height: 900 },
  },
  {
    id: 'illustration-vector-clipped-texture',
    file: 'illustration-vector-clipped-texture.png',
    captureFile: 'vector-contour-clipped-texture.png',
    producer: 'tests/e2e/paint/clipped-vector-texture.spec.ts',
    alt: 'Varve Design workspace showing a red raster shading stroke clipped inside a teal vector contour',
    caption:
      'A vector contour and raster shading share one editable document, exported as editable contour geometry with a bounded embedded texture.',
    feature: 'strokes',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1440, height: 900 },
  },
  {
    id: 'concept-art-reference-workflow',
    file: 'concept-art-reference-workflow.png',
    captureFile: 'concept-reference-light.png',
    producer: 'tests/e2e/canvas/concept-art-references.spec.ts',
    alt: 'Varve Design workspace with a forest photograph selected as a concept reference and separate sampling and export switches enabled',
    caption:
      'The imported forest photograph stays visible while sampling and export remain independently controlled.',
    feature: 'strokes',
    theme: 'light',
    kind: 'full',
    viewport: { width: 1440, height: 1000 },
  },
  {
    id: 'plugin-rename-preview',
    file: 'plugins-rename-preview-light.png',
    captureFile: 'plugin-rename-preview.png',
    producer: 'tests/e2e/plugins/local-manager.spec.ts',
    alt: 'Varve plugin manager showing a reviewed layer-name proposal before Apply',
    caption: 'Number Selected Layers proposes an undoable rename for review',
    feature: 'local-plugins',
    theme: 'light',
    kind: 'full',
  },
  {
    id: 'plugin-permission-review',
    file: 'plugins-permission-review-dark.png',
    captureFile: 'plugin-review-dark-1024.png',
    producer: 'tests/e2e/plugins/local-manager.spec.ts',
    alt: 'Varve plugin manager showing required selection read and optional document write access',
    caption: 'Required and optional permissions stay separate in a narrow window',
    feature: 'local-plugins',
    theme: 'dark',
    kind: 'full',
  },
  {
    id: 'plugin-inspector-analysis',
    file: 'plugins-inspector-analysis-light.png',
    captureFile: 'plugin-inspector.png',
    producer: 'tests/e2e/plugins/local-manager.spec.ts',
    alt: 'Selection Style Readiness analysis shown in the Varve Properties Inspector',
    caption: 'A local analysis plugin renders text in the host-owned Inspector',
    feature: 'local-plugins',
    theme: 'light',
    kind: 'full',
  },
  {
    id: 'plugin-manager-discovery',
    file: 'plugins-manager-discovery-light.png',
    captureFile: 'plugin-manager-pinned.png',
    producer: 'tests/e2e/plugins/local-manager.spec.ts',
    alt: "Varve's plugin manager showing accessible package artwork, searchable descriptions, pinned plugins, and alphabetical results",
    caption: 'Find familiar plugins by artwork, description, pin, or name',
    feature: 'local-plugins',
    theme: 'light',
    kind: 'full',
  },
  {
    id: 'tonal-curves',
    file: 'tonal-curves-light.png',
    captureFile: '01-curves-light.png',
    producer: 'tests/e2e/effects/tonal-workflows.spec.ts',
    alt: 'An imported photographic fixture with the Curves graph, retained channel selector and precise point controls in Varve',
    caption:
      'Precise point curves on an editable adjustment layer, with an upstream histogram and source preview.',
    feature: 'tonal-adjustments',
    theme: 'light',
    kind: 'full',
  },
  {
    id: 'tonal-split-tone',
    file: 'tonal-split-tone-light.png',
    captureFile: '04-split-tone-light.png',
    producer: 'tests/e2e/effects/tonal-workflows.spec.ts',
    alt: 'Split Toning shadow and highlight controls beside a synthetic neutral ramp and color reference in Varve',
    caption:
      'Editable shadow and highlight toning on a synthetic reference that makes color shifts easy to compare.',
    feature: 'tonal-adjustments',
    theme: 'light',
    kind: 'full',
  },
];
