/**
 * Canonical isometric / axonometric construction geometry.
 *
 * One mathematical definition consumed by the overlay renderer, the snapping
 * solver, plane-aware tools, fit-to-plane, and grid-artwork generation.
 *
 * ## Conventions (do not fork)
 *
 * - Document coordinates: `+X` right, `+Y` down (SVG initial user space).
 * - Axis `angle` is in **degrees** and denotes the direction of the line
 *   family *itself*: `direction = (cos θ, sin θ)`, `normal = (−sin θ, cos θ)`.
 *   With `+Y` down a positive angle therefore runs clockwise on screen.
 * - Affine/basis math is radians-free: a `Basis` is the linear part
 *   `[a, b, c, d]` in the same column convention as `Affine`
 *   (`x' = a·u + c·v`, `y' = b·u + d·v`).
 * - `spacing` is the **projected length of one lattice step along each axis**
 *   (the lattice constant `s`). It is deliberately *not* the perpendicular
 *   distance between lines of a family; those follow from the basis, and
 *   keeping one authored number prevents three families from drifting apart.
 *
 * A lattice generated by `b1 = s·(cos θ1, sin θ1)` and
 * `b2 = s·(cos θ2, sin θ2)` has perpendicular family spacings
 * `s·|sin Δ|` (family parallel to `b1` or `b2`) and `s·|sin Δ|` for the third
 * family when it is parallel to `b1 + b2` (the true-isometric vertical case).
 * Every family is emitted as `origin·n + k·p`, so all three families meet at
 * the same lattice points by construction.
 */

/** A linear 2×2 map in the shared column convention `[a, b, c, d]`. */
export type Basis = readonly [number, number, number, number];

/** Immutable 2-vector. */
export type Vec2 = readonly [number, number];

/** Basis whose columns are `u` and `v`. World-space by convention. */
export interface PlaneBasis {
  /** Direction of the `u` axis (column 0). */
  u: Vec2;
  /** Direction of the `v` axis (column 1). */
  v: Vec2;
}

/** Named construction planes for a Varve isometric grid. */
export type IsometricPlaneId = 'top' | 'front' | 'side';

export interface IsometricPlaneInfo {
  id: IsometricPlaneId;
  /** UI label. Stable, localised by the presentation layer if needed. */
  label: string;
  /** Axis labels this plane spans, in `u, v` order. */
  axes: readonly [string, string];
  /** Short copy used in tooltips and status text. */
  description: string;
}

/**
 * Varve plane mapping (product decision D3):
 * - `top`   spans Right (30°) and Left (150°): the ground plane.
 * - `front` spans Right (30°) and Vertical (90°): faces the lower-right.
 * - `side`  spans Left (150°) and Vertical (90°): faces the lower-left.
 *
 * Affinity also calls these Top/Front/Side, but their left/right assignment
 * can differ per document orientation, so Varve publishes its own mapping
 * instead of claiming parity.
 */
export const ISOMETRIC_PLANES: readonly IsometricPlaneInfo[] = [
  {
    id: 'top',
    label: 'Top',
    axes: ['Right', 'Left'],
    description: 'Ground plane: spans the two down-sloping axes.',
  },
  {
    id: 'front',
    label: 'Front',
    axes: ['Right', 'Vertical'],
    description: 'Faces lower-right: spans the right axis and vertical.',
  },
  {
    id: 'side',
    label: 'Side',
    axes: ['Left', 'Vertical'],
    description: 'Faces lower-left: spans the left axis and vertical.',
  },
] as const;

export function isometricPlaneInfo(id: IsometricPlaneId): IsometricPlaneInfo {
  return ISOMETRIC_PLANES.find((plane) => plane.id === id) ?? ISOMETRIC_PLANES[0]!;
}

/** Exact 2:1 game-art angle: `atan2(1, 2)` in degrees. */
export const DIMETRIC_2_1_ANGLE_DEG = (Math.atan2(1, 2) * 180) / Math.PI;

/** Direction of the canonical true-isometric families, in degrees. */
export const TRUE_ISOMETRIC_ANGLES: readonly [number, number, number] = [30, 150, 90];

/** Direction of the exact 2:1 dimetric families, in degrees. */
export const DIMETRIC_2_1_ANGLES: readonly [number, number, number] = [
  DIMETRIC_2_1_ANGLE_DEG,
  180 - DIMETRIC_2_1_ANGLE_DEG,
  90,
];

/** Convert a rhombus/rhomb ratio (`height:width`) into its axis angle, degrees. */
export function ratioToAxisAngleDegrees(height: number, width: number): number {
  if (!Number.isFinite(height) || !Number.isFinite(width) || height <= 0 || width <= 0) {
    return DIMETRIC_2_1_ANGLE_DEG;
  }
  return (Math.atan2(height, width) * 180) / Math.PI;
}

/** Convert an axis angle in degrees into the closest simple ratio, if exact. */
export function axisAngleToRatio(
  angleDeg: number,
  maxDenominator = 64,
): { height: number; width: number } | null {
  if (!Number.isFinite(angleDeg)) return null;
  const radians = (normaliseAngle(angleDeg) * Math.PI) / 180;
  let best: { height: number; width: number; error: number } | null = null;
  for (let width = 1; width <= maxDenominator; width++) {
    const idealHeight = Math.tan(radians) * width;
    for (const height of [Math.floor(idealHeight), Math.ceil(idealHeight)]) {
      if (height <= 0) continue;
      const candidate = ratioToAxisAngleDegrees(height, width);
      const error = Math.abs(candidate - normaliseAngle(angleDeg));
      if (error < 0.01 && (!best || error < best.error)) {
        const divisor = gcd(height, width);
        best = { height: height / divisor, width: width / divisor, error };
      }
    }
  }
  return best ? { height: best.height, width: best.width } : null;
}

function gcd(a: number, b: number): number {
  let x = Math.abs(a);
  let y = Math.abs(b);
  while (y > 1e-9) {
    const t = x % y;
    x = y;
    y = t;
  }
  return Math.max(1, x);
}

function normaliseAngle(angle: number): number {
  if (!Number.isFinite(angle)) return 0;
  return ((angle % 360) + 360) % 360;
}

/** Smallest undirected separation between two line directions, in degrees. */
export function axisSeparationDegrees(a: number, b: number): number {
  const diff = Math.abs(normaliseAngle(a) - normaliseAngle(b)) % 180;
  return Math.min(diff, 180 - diff);
}

export function basisFromColumns(u: Vec2, v: Vec2): Basis {
  return [u[0], u[1], v[0], v[1]];
}

export function basisColumns(basis: Basis): PlaneBasis {
  return { u: [basis[0], basis[1]], v: [basis[2], basis[3]] };
}

export function applyBasis(basis: Basis, p: Vec2): Vec2 {
  return [basis[0] * p[0] + basis[2] * p[1], basis[1] * p[0] + basis[3] * p[1]];
}

export function determinant(basis: Basis): number {
  return basis[0] * basis[3] - basis[1] * basis[2];
}

/** Inverse of a linear basis, or `null` when singular (|det| below epsilon). */
export function invertBasis(basis: Basis, epsilon = 1e-12): Basis | null {
  const det = determinant(basis);
  if (!Number.isFinite(det) || Math.abs(det) < epsilon) return null;
  const inv = 1 / det;
  return [basis[3] * inv, -basis[1] * inv, -basis[2] * inv, basis[0] * inv];
}

/**
 * Conditioning of a basis: `|det| / (|u|·|v|) = |sin θ|` where θ is the angle
 * between the columns. `0` is degenerate, `1` is orthogonal. Near-parallel
 * axes are rejected with this measure instead of a raw angle-equality check.
 */
export function basisConditioning(basis: Basis): number {
  const lenU = Math.hypot(basis[0], basis[1]);
  const lenV = Math.hypot(basis[2], basis[3]);
  if (!(lenU > 0) || !(lenV > 0)) return 0;
  return Math.abs(determinant(basis)) / (lenU * lenV);
}

/** Multiply two linear bases: `a · b` (apply `b` first). */
export function multiplyBasis(a: Basis, b: Basis): Basis {
  return [
    a[0] * b[0] + a[2] * b[1],
    a[1] * b[0] + a[3] * b[1],
    a[0] * b[2] + a[2] * b[3],
    a[1] * b[2] + a[3] * b[3],
  ];
}

/** The linear (rotation-free) part of a rotation by `degrees`. */
export function rotationBasis(degrees: number): Basis {
  const radians = (degrees * Math.PI) / 180;
  const cos = Math.cos(radians);
  const sin = Math.sin(radians);
  return [cos, sin, -sin, cos];
}

/**
 * Lattice basis from a lattice constant and two axis directions. Columns are
 * `s·(cos θ, sin θ)`; the result is a valid basis whenever the directions are
 * not near-parallel.
 */
export function latticeBasisFromAngles(
  spacing: number,
  firstAngleDeg: number,
  secondAngleDeg: number,
): Basis {
  const a1 = (firstAngleDeg * Math.PI) / 180;
  const a2 = (secondAngleDeg * Math.PI) / 180;
  return [
    spacing * Math.cos(a1),
    spacing * Math.sin(a1),
    spacing * Math.cos(a2),
    spacing * Math.sin(a2),
  ];
}

/** Rotate a basis about the document origin by `degrees`. */
export function rotateBasis(basis: Basis, degrees: number): Basis {
  return multiplyBasis(rotationBasis(degrees), basis);
}

/** Distance from `p` to `q`, or `Infinity` when either is non-finite. */
function distance(p: Vec2, q: Vec2): number {
  if (!isFiniteVec(p) || !isFiniteVec(q)) return Infinity;
  return Math.hypot(p[0] - q[0], p[1] - q[1]);
}

function isFiniteVec(p: Vec2): boolean {
  return Number.isFinite(p[0]) && Number.isFinite(p[1]);
}

/** A single resolved line family: direction, normal, and offset step. */
export interface AxisFamily {
  /** Direction angle after grid rotation, degrees. */
  angleDeg: number;
  /** Column vector of the family direction (`s`-length only for basis families). */
  direction: Vec2;
  normal: Vec2;
  /**
   * Signed step between adjacent lines, measured along `normal` from the
   * grid origin. Derived so that every family passes through lattice points.
   */
  offsetStep: number;
  /**
   * `lattice` when the family is generated by the basis (lines contain all
   * lattice points); `guide` when a custom third direction cannot be part of
   * the lattice and is drawn as a directional construction guide.
   */
  role: 'lattice' | 'guide';
  /** Stable index within the authored axis list. */
  index: number;
  visible: boolean;
  label?: string;
  color?: string;
  opacity?: number;
}

/** Resolved canonical grid geometry. Everything else is derived from this. */
export interface IsometricGridGeometry {
  origin: Vec2;
  /** Lattice constant: projected length of one step along each basis axis. */
  spacing: number;
  /** Grid rotation about the origin, degrees. */
  rotationDeg: number;
  /** Lattice basis in document space (already rotated). */
  basis: Basis;
  /** Axis families in authored order, with only visible families listed. */
  families: AxisFamily[];
  /** Major line interval, as a multiple of the per-family offset step. */
  majorEvery: number;
  /** True when every visible family belongs to the lattice. */
  latticeValid: boolean;
  /** Smallest |sin θ| between basis columns, for UI diagnostics. */
  conditioning: number;
}

export interface AxisInput {
  angle: number;
  visible?: boolean;
  label?: string;
  color?: string;
  opacity?: number;
}

export interface IsometricGeometryInput {
  originX: number;
  originY: number;
  spacing: number;
  rotation: number;
  axes: readonly AxisInput[];
  /** Axis indices (into `axes`) used to form the lattice basis. */
  basisAxisIndices?: readonly [number, number];
}

/** Minimum |sin θ| accepted for a snapping-capable lattice (≈5.7°). */
export const MIN_LATTICE_CONDITIONING = 0.1;
/** |sin θ| below this is reported as a warning (≈14.5°). */
export const WARN_LATTICE_CONDITIONING = 0.25;

export interface IsometricValidation {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Validate authored isometric configuration. This is numerical conditioning,
 * not just duplicate-angle equality: two axes 0.5° apart are distinct but
 * useless as a plane basis.
 */
export function validateIsometricConfiguration(input: IsometricGeometryInput): IsometricValidation {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!Number.isFinite(input.spacing) || input.spacing <= 0) {
    errors.push('Spacing must be a positive finite number.');
  }
  if (!Number.isFinite(input.originX) || !Number.isFinite(input.originY)) {
    errors.push('Grid origin must be finite.');
  }
  if (!Number.isFinite(input.rotation)) {
    errors.push('Grid rotation must be finite.');
  }
  const visible = input.axes.filter((axis) => axis.visible !== false);
  if (visible.length < 2) {
    errors.push('A construction grid needs at least two visible axes.');
  }
  for (const axis of input.axes) {
    if (!Number.isFinite(axis.angle)) {
      errors.push('Axis angles must be finite.');
      break;
    }
    if (
      axis.opacity !== undefined &&
      (!Number.isFinite(axis.opacity) || axis.opacity < 0 || axis.opacity > 1)
    ) {
      errors.push('Axis opacity must be within 0–1.');
      break;
    }
  }

  const distinct = new Set(visible.map((axis) => normaliseAngle(axis.angle).toFixed(3)));
  if (visible.length >= 2 && distinct.size < visible.length) {
    errors.push('Two axes share the same direction.');
  }

  const indices = input.basisAxisIndices;
  if (indices) {
    const first = input.axes[indices[0]];
    const second = input.axes[indices[1]];
    if (!first || !second) {
      errors.push('Basis axes must reference existing axes.');
    } else if (Number.isFinite(first.angle) && Number.isFinite(second.angle)) {
      const separation = axisSeparationDegrees(first.angle, second.angle);
      if (separation < (Math.asin(MIN_LATTICE_CONDITIONING) * 180) / Math.PI) {
        errors.push(
          `Axes are ${separation.toFixed(2)}° apart; at least ` +
            `${((Math.asin(MIN_LATTICE_CONDITIONING) * 180) / Math.PI).toFixed(1)}° is required for a stable lattice.`,
        );
      } else if (separation < (Math.asin(WARN_LATTICE_CONDITIONING) * 180) / Math.PI) {
        warnings.push(`Axes are only ${separation.toFixed(2)}° apart; snapping may be imprecise.`);
      }
    }
  } else if (visible.length >= 2) {
    let bestSin = 0;
    for (let i = 0; i < visible.length; i++) {
      for (let j = i + 1; j < visible.length; j++) {
        bestSin = Math.max(
          bestSin,
          Math.abs(
            Math.sin((axisSeparationDegrees(visible[i]!.angle, visible[j]!.angle) * Math.PI) / 180),
          ),
        );
      }
    }
    if (bestSin < MIN_LATTICE_CONDITIONING) {
      errors.push('No pair of axes forms a stable lattice basis.');
    } else if (bestSin < WARN_LATTICE_CONDITIONING) {
      warnings.push('Axis separation is small; snapping may be imprecise.');
    }
  }

  return { valid: errors.length === 0, errors, warnings };
}

function chooseBasisAxes(
  axes: readonly AxisInput[],
  basisAxisIndices?: readonly [number, number],
): [number, number] {
  if (basisAxisIndices) return [basisAxisIndices[0], basisAxisIndices[1]];
  // Authored order decides the plane basis: the first two visible axes are
  // the construction plane and any later axis is derived from them. Picking
  // the "best-conditioned pair" instead would silently re-assign the ground
  // plane whenever a steeper custom axis happens to be better conditioned.
  const visibleIndices = axes
    .map((axis, index) => ({ axis, index }))
    .filter((entry) => entry.axis.visible !== false)
    .map((entry) => entry.index);
  if (visibleIndices.length >= 2) return [visibleIndices[0]!, visibleIndices[1]!];
  // Fewer than two visible axes: fall back to the first two authored entries
  // so a hidden-axis configuration still resolves instead of throwing.
  return [0, Math.min(1, Math.max(0, axes.length - 1))];
}

/**
 * Resolve authored configuration into canonical geometry. Returns `null` when
 * the configuration cannot form a basis at all (non-finite or degenerate).
 * Callers keep their last valid geometry rather than destroying state.
 */
export function resolveIsometricGeometry(
  input: IsometricGeometryInput,
): IsometricGridGeometry | null {
  if (!Number.isFinite(input.spacing) || input.spacing <= 0) return null;
  if (!Number.isFinite(input.originX) || !Number.isFinite(input.originY)) return null;
  const [firstIndex, secondIndex] = chooseBasisAxes(input.axes, input.basisAxisIndices);
  const first = input.axes[firstIndex];
  const second = input.axes[secondIndex];
  if (!first || !second) return null;
  if (!Number.isFinite(first.angle) || !Number.isFinite(second.angle)) return null;

  const rotationDeg = Number.isFinite(input.rotation) ? input.rotation : 0;
  const basis = latticeBasisFromAngles(
    input.spacing,
    first.angle + rotationDeg,
    second.angle + rotationDeg,
  );
  const conditioning = basisConditioning(basis);
  if (!(conditioning > 0)) return null;

  const families: AxisFamily[] = [];
  const thirdCandidates = input.axes
    .map((axis, index) => ({ axis, index }))
    .filter(
      (entry) =>
        entry.index !== firstIndex && entry.index !== secondIndex && entry.axis.visible !== false,
    );

  const addFamily = (
    index: number,
    axis: AxisInput,
    direction: Vec2,
    role: 'lattice' | 'guide',
    offsetStep: number,
  ): void => {
    if (axis.visible === false) return;
    const length = Math.hypot(direction[0], direction[1]);
    if (!(length > 0)) return;
    const unit: Vec2 = [direction[0] / length, direction[1] / length];
    const normal: Vec2 = [-unit[1], unit[0]];
    families.push({
      angleDeg: normaliseAngle((Math.atan2(unit[1], unit[0]) * 180) / Math.PI),
      direction: unit,
      normal,
      offsetStep,
      role,
      index,
      visible: true,
      label: axis.label,
      color: axis.color,
      opacity: axis.opacity,
    });
  };

  // First two families: generated by the basis, offset step = |other column · normal|.
  const basisFamilyStep = (normal: Vec2, otherColumn: Vec2): number =>
    Math.abs(normal[0] * otherColumn[0] + normal[1] * otherColumn[1]);

  const firstDirection: Vec2 = [basis[0], basis[1]];
  const secondDirection: Vec2 = [basis[2], basis[3]];
  const firstUnit = normaliseVec(firstDirection);
  const secondUnit = normaliseVec(secondDirection);
  const firstNormal: Vec2 = [-firstUnit[1], firstUnit[0]];
  const secondNormal: Vec2 = [-secondUnit[1], secondUnit[0]];
  addFamily(
    firstIndex,
    first,
    firstDirection,
    'lattice',
    basisFamilyStep(firstNormal, secondDirection),
  );
  addFamily(
    secondIndex,
    second,
    secondDirection,
    'lattice',
    basisFamilyStep(secondNormal, firstDirection),
  );

  // Third family, if authored: accept it as lattice when it is (anti)parallel
  // to u+v or u−v within tolerance; otherwise keep it as a directional guide.
  // This is the honest treatment the mission requires for custom angle sets.
  const toleranceDeg = 0.5;
  for (const third of thirdCandidates) {
    const angle = third.axis.angle + rotationDeg;
    const direction: Vec2 = [Math.cos((angle * Math.PI) / 180), Math.sin((angle * Math.PI) / 180)];
    const candidates: Vec2[] = [
      [basis[0] + basis[2], basis[1] + basis[3]],
      [basis[0] - basis[2], basis[1] - basis[3]],
    ];
    let role: 'lattice' | 'guide' = 'guide';
    let offsetStep = input.spacing;
    for (const candidate of candidates) {
      const candidateAngle = (Math.atan2(candidate[1], candidate[0]) * 180) / Math.PI;
      if (axisSeparationDegrees(candidateAngle, angle) <= toleranceDeg) {
        // Parallel to `b1 ± b2`, so both basis columns project onto the
        // family normal with equal magnitude `|b1·n|`: that is the offset
        // step that puts every line through lattice points.
        role = 'lattice';
        const radians = (angle * Math.PI) / 180;
        const normal: Vec2 = [-Math.sin(radians), Math.cos(radians)];
        offsetStep = Math.abs(normal[0] * basis[0] + normal[1] * basis[1]);
        break;
      }
    }
    addFamily(third.index, third.axis, direction, role, offsetStep);
  }

  return {
    origin: [input.originX, input.originY],
    spacing: input.spacing,
    rotationDeg,
    basis,
    families,
    majorEvery: 1,
    latticeValid: families.every((family) => family.role === 'lattice'),
    conditioning,
  };
}

function normaliseVec(v: Vec2): Vec2 {
  const length = Math.hypot(v[0], v[1]);
  if (!(length > 0)) return [1, 0];
  return [v[0] / length, v[1] / length];
}

/** Axis families that span a named plane, in `u, v` order. */
export function familiesForPlane(
  geometry: IsometricGridGeometry,
  planeId: IsometricPlaneId,
): readonly [AxisFamily, AxisFamily] | null {
  const findFamily = (targetAngle: number): AxisFamily | undefined =>
    geometry.families.find((family) => axisSeparationDegrees(family.angleDeg, targetAngle) < 15);
  let uFamily: AxisFamily | undefined;
  let vFamily: AxisFamily | undefined;
  switch (planeId) {
    case 'top':
      uFamily = findFamily(30);
      vFamily = findFamily(150);
      break;
    case 'front':
      uFamily = findFamily(30);
      vFamily = findFamily(90);
      break;
    case 'side':
      uFamily = findFamily(150);
      vFamily = findFamily(90);
      break;
  }
  return uFamily && vFamily ? [uFamily, vFamily] : null;
}

/** Build a plane from resolved geometry. `origin` defaults to the grid origin. */
export function constructionPlaneFromGeometry(
  geometry: IsometricGridGeometry,
  planeId: IsometricPlaneId,
  origin?: Vec2,
): ConstructionPlane | null {
  const info = isometricPlaneInfo(planeId);
  const pair = familiesForPlane(geometry, planeId);
  if (!pair) return null;
  const [uFamily, vFamily] = pair;
  // Unit-scale basis: one plane unit is one document unit along the axis
  // direction. Grid spacing scales lattice *indices*, not the projection, so
  // fitting artwork must not resize it by the spacing.
  const basis = basisFromColumns(uFamily.direction, vFamily.direction);
  if (!(basisConditioning(basis) > 0)) return null;
  return {
    id: planeId,
    label: info.label,
    origin: origin ?? geometry.origin,
    basis,
    uAxisLabel: info.axes[0],
    vAxisLabel: info.axes[1],
  };
}

export interface ConstructionPlane {
  id: IsometricPlaneId;
  label: string;
  origin: Vec2;
  basis: Basis;
  uAxisLabel: string;
  vAxisLabel: string;
}

/** Plane coordinates of a document-space point. `null` when the basis is singular. */
export function worldToPlane(plane: ConstructionPlane, point: Vec2): Vec2 | null {
  const inverse = invertBasis(plane.basis);
  if (!inverse || !isFiniteVec(point)) return null;
  const local: Vec2 = [point[0] - plane.origin[0], point[1] - plane.origin[1]];
  return applyBasis(inverse, local);
}

/** Document-space point of plane coordinates. */
export function planeToWorld(plane: ConstructionPlane, uv: Vec2): Vec2 {
  const local = applyBasis(plane.basis, uv);
  return [plane.origin[0] + local[0], plane.origin[1] + local[1]];
}

// ── Nearest lattice point (exact 2-D closest-vector search) ───────────────────

interface ReducedLattice {
  b1: Vec2;
  b2: Vec2;
  relevant: Vec2[];
}

/**
 * Lagrange–Gauss reduce a 2-D lattice basis under the Euclidean metric.
 * Produces `|b1| ≤ |b2|` with `|b1·b2| ≤ |b1|²/2`, which makes the
 * Voronoi-relevant-vector correction below terminate in a bounded number of
 * steps.
 */
function gaussReduce(columns: readonly [Vec2, Vec2]): ReducedLattice {
  let b1: Vec2 = columns[0];
  let b2: Vec2 = columns[1];
  for (let guard = 0; guard < 64; guard++) {
    const len1 = b1[0] * b1[0] + b1[1] * b1[1];
    const len2 = b2[0] * b2[0] + b2[1] * b2[1];
    if (len1 === 0 && len2 === 0) break;
    if (len1 > len2) {
      const swap = b1;
      b1 = b2;
      b2 = swap;
      continue;
    }
    if (len1 === 0) break;
    const mu = Math.round((b1[0] * b2[0] + b1[1] * b2[1]) / len1);
    if (mu === 0) break;
    b2 = [b2[0] - mu * b1[0], b2[1] - mu * b1[1]];
  }
  const relevant: Vec2[] = [
    b1,
    [-b1[0], -b1[1]],
    b2,
    [-b2[0], -b2[1]],
    [b1[0] - b2[0], b1[1] - b2[1]],
    [b2[0] - b1[0], b2[1] - b1[1]],
    [b1[0] + b2[0], b1[1] + b2[1]],
    [-b1[0] - b2[0], -b1[1] - b2[1]],
  ];
  return { b1, b2, relevant };
}

export interface LatticeHit {
  /** Closest lattice point in document space. */
  point: Vec2;
  /** Integer lattice indices in the original basis. */
  index: readonly [number, number];
  /** Distance in the query metric (document units by default). */
  distance: number;
}

export interface LatticeQueryOptions {
  /** Lattice anchor in document space; defaults to the document origin. */
  origin?: Vec2;
  /**
   * Optional linear screen transform. When provided, the search minimises
   * screen distance (`|S·(p − q)|`), which is the metric the user perceives
   * under zoom, camera rotation, and non-uniform scope transforms.
   */
  metric?: Basis;
}

/**
 * Exact nearest lattice point.
 *
 * Rounding the basis coordinates independently is *not* correct for an
 * oblique lattice — the classic counterexample is reproduced in
 * `isometricGeometry.test.ts`. This uses the standard 2-D Voronoi
 * (Conway–Sloane) correction: reduce the basis, start from the rounded
 * coordinates, and move the candidate across each Voronoi-relevant vector
 * while the query lies beyond that vector's bisector. Each accepted move
 * strictly decreases the metric distance, so the loop terminates; the guard
 * is defensive only.
 *
 * The candidate set is the whole lattice, so the result is exact for any
 * well-conditioned basis; no arbitrary "3×3 neighborhood" heuristic is used.
 */
export function nearestLatticePoint(
  point: Vec2,
  basis: Basis,
  options: LatticeQueryOptions = {},
): LatticeHit | null {
  if (!isFiniteVec(point)) return null;
  const origin: Vec2 = options.origin && isFiniteVec(options.origin) ? options.origin : [0, 0];
  const metric = options.metric;
  const effective = metric ? multiplyBasis(metric, basis) : basis;
  if (!(basisConditioning(effective) > 0)) return null;
  const inverse = invertBasis(effective);
  if (!inverse) return null;

  const local = (p: Vec2): Vec2 => [p[0] - origin[0], p[1] - origin[1]];
  const query: Vec2 = metric ? applyBasis(metric, local(point)) : local(point);
  const rounded = applyBasis(inverse, query);
  let k: [number, number] = [Math.round(rounded[0]), Math.round(rounded[1])];

  const reduced = gaussReduce([applyBasis(effective, [1, 0]), applyBasis(effective, [0, 1])]);
  const metricSquared = (v: Vec2): number => v[0] * v[0] + v[1] * v[1];

  for (let guard = 0; guard < 64; guard++) {
    const candidate: Vec2 = applyBasis(effective, k);
    const delta: Vec2 = [query[0] - candidate[0], query[1] - candidate[1]];
    let moved = false;
    for (const vector of reduced.relevant) {
      const lengthSq = metricSquared(vector);
      if (!(lengthSq > 0)) continue;
      const projection = delta[0] * vector[0] + delta[1] * vector[1];
      if (projection > lengthSq / 2) {
        const step = inverseStepForVector(vector, effective);
        if (!step) continue;
        k = [k[0] + step[0], k[1] + step[1]];
        moved = true;
        break;
      }
    }
    if (!moved) break;
  }

  const localPoint = applyBasis(basis, k);
  const worldPoint: Vec2 = [origin[0] + localPoint[0], origin[1] + localPoint[1]];
  const delta: Vec2 = [point[0] - worldPoint[0], point[1] - worldPoint[1]];
  return {
    point: worldPoint,
    index: k,
    distance: metric ? Math.hypot(...applyBasis(metric, delta)) : Math.hypot(delta[0], delta[1]),
  };
}

/**
 * Express a Voronoi-relevant vector (in effective/screen space) as integer
 * steps in the original basis coordinates.
 */
function inverseStepForVector(vector: Vec2, effective: Basis): [number, number] | null {
  const inverse = invertBasis(effective);
  if (!inverse) return null;
  const step = applyBasis(inverse, vector);
  const rounded: [number, number] = [Math.round(step[0]), Math.round(step[1])];
  if (Math.abs(step[0] - rounded[0]) > 1e-6 || Math.abs(step[1] - rounded[1]) > 1e-6) return null;
  return rounded;
}

export interface LatticeLineHit {
  /** Point on the nearest line. */
  point: Vec2;
  /** Family that produced the line. */
  family: AxisFamily;
  /** Signed line offset from the grid origin along the family normal. */
  offset: number;
  distance: number;
}

/**
 * Nearest line of one or more families, measured perpendicular to the family
 * in the query metric. Line snapping is distinct from intersection snapping:
 * the returned point is the orthogonal projection, not a lattice vertex.
 */
export function nearestLatticeLine(
  point: Vec2,
  origin: Vec2,
  family: AxisFamily,
  metric?: Basis,
): LatticeLineHit | null {
  if (!isFiniteVec(point) || !Number.isFinite(family.offsetStep) || family.offsetStep === 0) {
    return null;
  }
  // Work in a space where the line family is horizontal and evenly spaced.
  const direction = family.direction;
  const normal: Vec2 = [family.normal[0], family.normal[1]];
  const toLocal = (p: Vec2): Vec2 => {
    const dx = p[0] - origin[0];
    const dy = p[1] - origin[1];
    return [dx * direction[0] + dy * direction[1], dx * normal[0] + dy * normal[1]];
  };
  const local = toLocal(point);
  const step = family.offsetStep;
  const offsetIndex = Math.round(local[1] / step);
  const snappedLocal: Vec2 = [local[0], offsetIndex * step];
  const world: Vec2 = [
    origin[0] + direction[0] * snappedLocal[0] + normal[0] * snappedLocal[1],
    origin[1] + direction[1] * snappedLocal[0] + normal[1] * snappedLocal[1],
  ];
  const effective = metric ?? ([1, 0, 0, 1] as Basis);
  return {
    point: world,
    family,
    offset: offsetIndex * step,
    distance: distance(applyBasis(effective, world), applyBasis(effective, point)),
  };
}

// ── Viewport line generation ──────────────────────────────────────────────────

export interface GridLineSegment {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  familyIndex: number;
  /** Index along the family normal, in units of the family offset step. */
  offsetIndex: number;
  major: boolean;
  role: 'lattice' | 'guide';
}

export interface ViewportLineOptions {
  /** Viewport corners in document space (4 points, any winding). */
  corners: readonly Vec2[];
  /** Display multiplier from the nested LOD ladder (1, 2, 4, …). */
  displayStep?: number;
  /** Offset-index multiples that render as major lines. */
  majorEvery?: number;
  /** Hard bound on emitted segments per family (defensive). */
  maxLinesPerFamily?: number;
  /** Optional viewport/scope clip in document space; defaults to the corners' box. */
  clip?: { x: number; y: number; w: number; h: number };
}

export const DEFAULT_MAX_LINES_PER_FAMILY = 8192;

/**
 * Generate only the visible portion of each line family. Work scales with
 * visible lines, not with the pasteboard or object count, and every line is
 * anchored to `origin + k·step` so changing display density or viewport never
 * shifts the phase.
 */
export function gridLinesForViewport(
  geometry: IsometricGridGeometry,
  options: ViewportLineOptions,
): GridLineSegment[] {
  const displayStep = options.displayStep && options.displayStep > 0 ? options.displayStep : 1;
  const maxLines = options.maxLinesPerFamily ?? DEFAULT_MAX_LINES_PER_FAMILY;
  const majorEvery = Math.max(1, Math.round(options.majorEvery ?? geometry.majorEvery ?? 1));
  const corners = options.corners.filter(isFiniteVec);
  if (corners.length < 3 || !(displayStep >= 1)) return [];
  const clip = options.clip ?? cornersBoundingBox(corners);
  if (!clip || !(clip.w > 0) || !(clip.h > 0)) return [];

  const segments: GridLineSegment[] = [];

  for (const family of geometry.families) {
    if (!family.visible) continue;
    const step = family.offsetStep * displayStep;
    if (!Number.isFinite(step) || Math.abs(step) < 1e-9) continue;
    const normal = family.normal;
    const direction = family.direction;

    const projections = corners.map(
      (corner) =>
        (corner[0] - geometry.origin[0]) * normal[0] + (corner[1] - geometry.origin[1]) * normal[1],
    );
    const minProjection = Math.min(...projections);
    const maxProjection = Math.max(...projections);
    const startIndex = Math.floor(minProjection / step) - 1;
    const endIndex = Math.ceil(maxProjection / step) + 1;
    const count = endIndex - startIndex + 1;
    if (count > maxLines) continue;

    for (let index = startIndex; index <= endIndex; index++) {
      const offset = index * step;
      const anchor: Vec2 = [
        geometry.origin[0] + normal[0] * offset,
        geometry.origin[1] + normal[1] * offset,
      ];
      const clipped = clipLineToBox(anchor, direction, clip);
      if (!clipped) continue;
      segments.push({
        x1: clipped[0][0],
        y1: clipped[0][1],
        x2: clipped[1][0],
        y2: clipped[1][1],
        familyIndex: family.index,
        offsetIndex: index * displayStep,
        major: (((index * displayStep) % majorEvery) + majorEvery) % majorEvery === 0,
        role: family.role,
      });
    }
  }

  return segments;
}

function cornersBoundingBox(
  corners: readonly Vec2[],
): { x: number; y: number; w: number; h: number } | null {
  if (corners.length === 0) return null;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const [x, y] of corners) {
    if (!Number.isFinite(x) || !Number.isFinite(y)) continue;
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
  }
  if (!Number.isFinite(minX) || !Number.isFinite(minY)) return null;
  return { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
}

/** Liang–Barsky clip of an infinite line (anchor + direction) to an AABB. */
function clipLineToBox(
  anchor: Vec2,
  direction: Vec2,
  box: { x: number; y: number; w: number; h: number },
): [Vec2, Vec2] | null {
  const [dx, dy] = direction;
  const xMin = box.x;
  const xMax = box.x + box.w;
  const yMin = box.y;
  const yMax = box.y + box.h;
  let t0 = -Infinity;
  let t1 = Infinity;
  const clipAxis = (p: number, q: number): boolean => {
    if (Math.abs(p) < 1e-12) return q >= 0;
    const r = q / p;
    if (p < 0) {
      if (r > t1) return false;
      if (r > t0) t0 = r;
    } else {
      if (r < t0) return false;
      if (r < t1) t1 = r;
    }
    return true;
  };
  if (!clipAxis(-dx, anchor[0] - xMin)) return null;
  if (!clipAxis(dx, xMax - anchor[0])) return null;
  if (!clipAxis(-dy, anchor[1] - yMin)) return null;
  if (!clipAxis(dy, yMax - anchor[1])) return null;
  if (!(t0 <= t1)) return null;
  return [
    [anchor[0] + t0 * dx, anchor[1] + t0 * dy],
    [anchor[0] + t1 * dx, anchor[1] + t1 * dy],
  ];
}

// ── Display density (LOD) ─────────────────────────────────────────────────────

/**
 * Nested display multipliers. Only powers of two are used so major lines keep
 * their identity while intermediate lines disappear, and so the phase never
 * changes between levels.
 */
export const DISPLAY_STEP_LADDER: readonly number[] = [1, 2, 4, 8, 16, 32, 64, 128];

export interface DisplayDensityInput {
  /** Smallest authored family step in document units. */
  minStep: number;
  /** Current camera scale (screen px per document unit). */
  zoom: number;
  /** Minimum comfortable screen spacing between drawn lines. */
  minScreenPx: number;
  /** Previously selected multiplier, for hysteresis. */
  previous?: number;
}

/**
 * Choose the next nested display multiplier. Hysteresis prevents flicker at
 * the threshold: the state is retained until the screen step crosses with a
 * 25% margin. Authored spacing is never modified.
 */
export function selectDisplayStep(input: DisplayDensityInput): number {
  const previous = input.previous && input.previous > 0 ? input.previous : 1;
  if (
    !Number.isFinite(input.minStep) ||
    input.minStep <= 0 ||
    !Number.isFinite(input.zoom) ||
    input.zoom <= 0
  ) {
    return previous;
  }
  const screenStep = input.minStep * input.zoom;
  if (!Number.isFinite(screenStep) || screenStep <= 0) return previous;
  const ideal = Math.max(1, Math.ceil(input.minScreenPx / screenStep));
  let ladderIndex = 0;
  while (
    ladderIndex < DISPLAY_STEP_LADDER.length - 1 &&
    DISPLAY_STEP_LADDER[ladderIndex]! < ideal
  ) {
    ladderIndex++;
  }
  const candidate = DISPLAY_STEP_LADDER[ladderIndex]!;

  if (candidate === previous) return previous;
  if (candidate > previous) {
    // Coarsen only after the current level is genuinely too dense. Together
    // with the densify margin below this yields a dead band (0.8–1.25 of the
    // density threshold) in which the level is retained, so threshold jitter
    // cannot flicker the grid.
    return input.minStep * previous * input.zoom >= input.minScreenPx * 0.8 ? previous : candidate;
  }
  // Densify only once the finer level is comfortably readable.
  return input.minStep * candidate * input.zoom >= input.minScreenPx * 1.25 ? candidate : previous;
}

/** Screen-space affine for a camera (scale + rotation, no translation). */
export function cameraMetric(zoom: number, rotationRadians: number): Basis {
  const cos = Math.cos(rotationRadians);
  const sin = Math.sin(rotationRadians);
  return [zoom * cos, zoom * sin, -zoom * sin, zoom * cos];
}

/** Scale a basis by a scalar. */
export function scaleBasis(basis: Basis, scalar: number): Basis {
  return [basis[0] * scalar, basis[1] * scalar, basis[2] * scalar, basis[3] * scalar];
}
