/**
 * Logo package export — a deterministic, production-ready deliverable set
 * for a logo project.
 *
 * Builds a ZIP (or folder set on desktop) containing:
 * - One subfolder per included concept/variant, each with transparent PNG
 *   (1x/2x) and transparent SVG files.
 * - Palette/brand-palette.json (project palette or document swatches).
 * - README.md with brand, concept, variant, clear-space, and license notes.
 * - manifest.json (deterministic content manifest).
 *
 * Everything is derived from the live document at export time; the source
 * artwork is never modified. File naming is deterministic and sanitized for
 * Windows/macOS/Linux (see @strata/scene export naming helpers).
 */

import type { Platform } from '@strata/platform';
import type { Document, NodeId } from '@strata/scene';
import { sanitizeSegment } from '@strata/scene/export';

export interface LogoPackageEntry {
  fileName: string;
  bytes: Uint8Array;
  mimeType: string;
}

export interface LogoPackageOptions {
  /** Brand name used for the package folder and README. */
  brandName: string;
  /** Concept ids to include (defaults to all concepts with artboards). */
  conceptIds?: string[];
  /** Also export registered variants (default true). */
  includeVariants?: boolean;
  /** Raster scale factors (default [1, 2]). */
  scales?: number[];
  /** Include the document's palette (default true). */
  includePalette?: boolean;
  /** Include the source document (default true). */
  includeSource?: boolean;
  /** Document JSON for Source/project.strata. */
  sourceJson?: string;
}

export interface LogoPackageResult {
  fileName: string;
  entries: string[];
  bytes: Uint8Array;
}

const PNG_MIME = 'image/png';
const SVG_MIME = 'image/svg+xml';

/** Render a node to a transparent PNG blob at the given scale. */
async function renderPng(
  node: import('@strata/scene').SceneNode,
  doc: Document,
  scale: number,
): Promise<Uint8Array> {
  const { exportNodeAsRaster } = await import('../components/SpecPanel/export');
  const { createEngine } = await import('@strata/engine');
  const engine = await createEngine('auto');
  const result = await exportNodeAsRaster(node, doc, engine, {
    format: 'image/png',
    scale,
    transparency: true,
  });
  return new Uint8Array(await result.blob.arrayBuffer());
}

/** Render a node to a transparent SVG string. */
async function renderSvg(node: import('@strata/scene').SceneNode, doc: Document): Promise<string> {
  const { exportNodeToSvg } = await import('@strata/codegen');
  return exportNodeToSvg(node, doc, {
    background: 'transparent',
    minify: false,
  });
}

export function collectPalette(doc: Document): Record<string, string> {
  const project = doc.logoProject;
  const out: Record<string, string> = {};
  const push = (name: string, color: string): void => {
    out[sanitizeSegment(name)] = color;
  };
  if (project?.palette) {
    for (const c of project.palette.colors) {
      push(c.name ?? `color-${c.id.slice(0, 6)}`, managedColorToHex(c.color));
    }
  }
  for (const swatch of doc.swatches ?? []) {
    const name = swatch.name ?? 'swatch';
    if (!(name in out)) push(name, managedColorToHex(swatch.color));
  }
  return out;
}

export function managedColorToHex(color: import('@strata/scene').ManagedColor): string {
  if (color.space === 'rgb') {
    const to255 = (v: number): number => Math.round(Math.min(1, Math.max(0, v)) * 255);
    const a = to255(color.a);
    const hex =
      '#' + [color.r, color.g, color.b].map((v) => to255(v).toString(16).padStart(2, '0')).join('');
    return a < 255 ? `${hex}${a.toString(16).padStart(2, '0')}` : hex;
  }
  if (color.space === 'cmyk') {
    const c = Math.min(1, Math.max(0, color.c));
    const m = Math.min(1, Math.max(0, color.m));
    const y = Math.min(1, Math.max(0, color.y));
    const k = Math.min(1, Math.max(0, color.k));
    const r = Math.round(255 * (1 - c) * (1 - k));
    const g = Math.round(255 * (1 - m) * (1 - k));
    const b = Math.round(255 * (1 - y) * (1 - k));
    return '#' + [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('');
  }
  const gray = Math.round(255 * Math.min(1, Math.max(0, color.space === 'gray' ? color.v : 0.5)));
  return '#' + [gray, gray, gray].map((v) => v.toString(16).padStart(2, '0')).join('');
}

export function buildReadme(
  brandName: string,
  concepts: { name: string; folders: string[] }[],
  variants: { name: string; kind: string; folders: string[] }[],
  paletteCount: number,
): string {
  const conceptLines = concepts.map((c) => `- ${c.name}: ${c.folders.join(', ')}`).join('\n');
  const variantLines =
    variants.length > 0
      ? variants.map((v) => `- ${v.name} (${v.kind}): ${v.folders.join(', ')}`).join('\n')
      : '- None yet.';
  return [
    `# ${brandName} — Logo Package`,
    '',
    'Generated by Strata. This package contains production-ready logo assets.',
    '',
    '## Contents',
    '',
    '- `Primary/` and per-concept folders: transparent PNG (1x/2x) and SVG.',
    `- \`Palette/\`: ${paletteCount} brand color(s) as JSON (hex).`,
    '- `Source/`: the editable Strata document.',
    '',
    '## Concepts',
    '',
    conceptLines || '- None.',
    '',
    '## Variants',
    '',
    variantLines,
    '',
    '## Usage notes',
    '',
    '- Logos are delivered on a transparent background; place them on your',
    '  brand surfaces, never on an opaque box.',
    '- Keep the clear space around the logo free of other elements.',
    '- For one-color reproduction (fax, engraving, stamps), use the',
    '  monochrome or reversed variant when provided.',
    '',
    '## Licensing',
    '',
    'Review the licensing status of fonts, images, and templates used in',
    'this logo before commercial adoption. Strata records what it can but',
    'does not grant or assert trademark rights.',
    '',
  ].join('\n');
}

/** Build the deterministic logo package ZIP. */
export async function buildLogoPackage(
  doc: Document,
  options: LogoPackageOptions,
): Promise<LogoPackageResult> {
  const project = doc.logoProject;
  const brandName = options.brandName || project?.name || doc.name || 'Brand';
  const scales = options.scales ?? [1, 2];
  const entries: LogoPackageEntry[] = [];
  const folder = sanitizeSegment(brandName);

  const concepts = project?.concepts ?? [];
  const selectedConcepts = options.conceptIds
    ? concepts.filter((c) => options.conceptIds!.includes(c.id))
    : concepts.filter((c) => c.status !== 'rejected');
  const conceptFolders: { name: string; folders: string[] }[] = [];

  for (const concept of selectedConcepts) {
    const artboardId: NodeId | null = concept.artboardId;
    if (!artboardId) continue;
    const node = doc.nodes[artboardId];
    if (!node) continue;
    const conceptFolder = `${folder}/${sanitizeSegment(concept.name)}`;
    const files: string[] = [];
    for (const scale of scales) {
      const suffix = scale === 1 ? '' : `@${scale}x`;
      const png = await renderPng(node, doc, scale);
      const fileName = `${sanitizeSegment(concept.name)}${suffix}.png`;
      entries.push({ fileName: `${conceptFolder}/${fileName}`, bytes: png, mimeType: PNG_MIME });
      files.push(fileName);
    }
    const svg = await renderSvg(node, doc);
    const svgName = `${sanitizeSegment(concept.name)}.svg`;
    entries.push({
      fileName: `${conceptFolder}/${svgName}`,
      bytes: new TextEncoder().encode(svg),
      mimeType: SVG_MIME,
    });
    files.push(svgName);
    conceptFolders.push({ name: concept.name, folders: files });
  }

  const variantFolders: { name: string; kind: string; folders: string[] }[] = [];
  if (options.includeVariants ?? true) {
    for (const variant of project?.variants ?? []) {
      if (!variant.artboardId) continue;
      const node = doc.nodes[variant.artboardId];
      if (!node) continue;
      const variantFolder = `${folder}/${sanitizeSegment(variant.name)}`;
      const files: string[] = [];
      for (const scale of scales) {
        const suffix = scale === 1 ? '' : `@${scale}x`;
        const png = await renderPng(node, doc, scale);
        const fileName = `${sanitizeSegment(variant.name)}${suffix}.png`;
        entries.push({ fileName: `${variantFolder}/${fileName}`, bytes: png, mimeType: PNG_MIME });
        files.push(fileName);
      }
      const svg = await renderSvg(node, doc);
      const svgName = `${sanitizeSegment(variant.name)}.svg`;
      entries.push({
        fileName: `${variantFolder}/${svgName}`,
        bytes: new TextEncoder().encode(svg),
        mimeType: SVG_MIME,
      });
      files.push(svgName);
      variantFolders.push({ name: variant.name, kind: variant.kind, folders: files });
    }
  }

  const palette: Record<string, string> =
    (options.includePalette ?? true) ? collectPalette(doc) : {};
  const paletteJson = JSON.stringify({ name: brandName, colors: palette }, null, 2);
  entries.push({
    fileName: `${folder}/Palette/brand-palette.json`,
    bytes: new TextEncoder().encode(paletteJson),
    mimeType: 'application/json',
  });

  const readme = buildReadme(
    brandName,
    conceptFolders,
    variantFolders,
    Object.keys(palette).length,
  );
  entries.push({
    fileName: `${folder}/README.md`,
    bytes: new TextEncoder().encode(readme),
    mimeType: 'text/markdown',
  });

  if (options.includeSource ?? true) {
    const sourceJson = options.sourceJson ?? JSON.stringify(doc, null, 2);
    entries.push({
      fileName: `${folder}/Source/project.strata`,
      bytes: new TextEncoder().encode(sourceJson),
      mimeType: 'application/json',
    });
  }

  const manifest = {
    name: brandName,
    generatedBy: 'strata-logo-package',
    version: 1,
    generatedAt: new Date().toISOString(),
    concepts: conceptFolders.map((c) => c.name),
    variants: variantFolders.map((v) => v.name),
    scales,
    formats: ['png', 'svg'],
    palette: Object.keys(palette),
  };
  entries.push({
    fileName: `${folder}/manifest.json`,
    bytes: new TextEncoder().encode(JSON.stringify(manifest, null, 2)),
    mimeType: 'application/json',
  });

  // Deterministic zip: sort entries by path, then compress.
  const sorted = [...entries].sort((a, b) => (a.fileName < b.fileName ? -1 : 1));
  const files: Record<string, Uint8Array> = {};
  for (const entry of sorted) files[entry.fileName] = entry.bytes;

  const { zipSync } = await import('fflate');
  const zipped = zipSync(files, { level: 6 });

  return {
    fileName: `${folder}-Logo-Package.zip`,
    entries: sorted.map((e) => e.fileName),
    bytes: zipped,
  };
}

/** Save a built logo package through the platform facade. */
export async function saveLogoPackage(
  platform: Platform | undefined,
  result: LogoPackageResult,
): Promise<boolean> {
  if (!platform) return false;
  try {
    await platform.saveBinaryFile(result.fileName, result.bytes, 'application/zip', 'zip');
    return true;
  } catch {
    return false;
  }
}
