/**
 * Presets for the live effects family.
 *
 * Presets are plain parameter objects — they populate ordinary effect
 * parameters and never create separate renderer branches. Each preset maps to
 * one effect kind; the UI uses them to fill `makeAdjustment(id, kind, params)`.
 */

import type { AdjustmentKind } from '../filters';

export interface LiveEffectPreset {
  id: string;
  kind: AdjustmentKind;
  name: string;
  /** Params excluding the AdjustmentBase fields (id/kind/visible/opacity/blendMode). */
  params: Record<string, unknown>;
}

export const LIVE_EFFECT_PRESETS: LiveEffectPreset[] = [
  // ── Dither ──────────────────────────────────────────────────────────────
  {
    id: 'dither-1bit',
    kind: 'dither',
    name: '1-bit',
    params: {
      algorithm: 'floyd-steinberg',
      paletteMode: 'levels',
      levels: 1,
      serpentine: true,
      strength: 1,
      bayerSize: 8,
      cellSize: 1,
      seed: 0,
    },
  },
  {
    id: 'dither-gameboy',
    kind: 'dither',
    name: 'Game Boy-like',
    params: {
      algorithm: 'floyd-steinberg',
      paletteMode: 'custom',
      colors: [
        [15, 56, 15],
        [48, 98, 48],
        [139, 172, 15],
        [155, 188, 15],
      ],
      metric: 'oklab',
      serpentine: true,
      strength: 1,
      bayerSize: 8,
      cellSize: 1,
      seed: 0,
    },
  },
  {
    id: 'dither-newspaper',
    kind: 'dither',
    name: 'Newspaper',
    params: {
      algorithm: 'atkinson',
      paletteMode: 'levels',
      levels: 2,
      serpentine: true,
      strength: 0.9,
      bayerSize: 8,
      cellSize: 1,
      seed: 0,
    },
  },
  {
    id: 'dither-ordered',
    kind: 'dither',
    name: 'Ordered pixel',
    params: {
      algorithm: 'bayer',
      paletteMode: 'levels',
      levels: 3,
      serpentine: false,
      strength: 1,
      bayerSize: 8,
      cellSize: 1,
      seed: 0,
    },
  },
  {
    id: 'dither-16color',
    kind: 'dither',
    name: 'Limited 16-color',
    params: {
      algorithm: 'floyd-steinberg',
      paletteMode: 'levels',
      levels: 4,
      serpentine: true,
      strength: 1,
      bayerSize: 8,
      cellSize: 1,
      seed: 0,
    },
  },
  {
    id: 'dither-blue-noise',
    kind: 'dither',
    name: 'Blue noise',
    params: {
      algorithm: 'blue-noise',
      paletteMode: 'levels',
      levels: 4,
      serpentine: false,
      strength: 1,
      bayerSize: 8,
      cellSize: 1,
      seed: 7,
    },
  },

  // ── Palette Snap ────────────────────────────────────────────────────────
  {
    id: 'palette-snap-vga',
    kind: 'paletteSnap',
    name: '16-color VGA',
    params: {
      colors: [
        [0, 0, 0],
        [128, 128, 128],
        [192, 192, 192],
        [255, 255, 255],
        [255, 0, 0],
        [128, 0, 0],
        [255, 255, 0],
        [128, 128, 0],
        [0, 255, 0],
        [0, 128, 0],
        [0, 255, 255],
        [0, 128, 128],
        [0, 0, 255],
        [0, 0, 128],
        [255, 0, 255],
        [128, 0, 128],
      ],
      metric: 'oklab',
      amount: 1,
      dither: false,
      ditherAlgorithm: 'floyd-steinberg',
      ditherStrength: 0.5,
      seed: 0,
    },
  },
  {
    id: 'palette-snap-amiga',
    kind: 'paletteSnap',
    name: 'Amiga 32-color',
    params: {
      colors: [
        [0, 0, 0],
        [255, 255, 255],
        [255, 0, 0],
        [0, 255, 0],
        [0, 0, 255],
        [255, 255, 0],
        [0, 255, 255],
        [255, 0, 255],
        [64, 64, 64],
        [192, 192, 192],
        [255, 128, 0],
        [0, 255, 128],
        [128, 0, 255],
        [255, 0, 128],
        [128, 255, 0],
        [0, 128, 255],
      ],
      metric: 'oklab',
      amount: 1,
      dither: true,
      ditherAlgorithm: 'floyd-steinberg',
      ditherStrength: 0.6,
      seed: 0,
    },
  },
  {
    id: 'palette-snap-ink',
    kind: 'paletteSnap',
    name: 'Ink and paper',
    params: {
      colors: [
        [0, 0, 0],
        [255, 255, 255],
      ],
      metric: 'oklab',
      amount: 1,
      dither: true,
      ditherAlgorithm: 'floyd-steinberg',
      ditherStrength: 1,
      seed: 0,
    },
  },

  // ── Bloom ───────────────────────────────────────────────────────────────
  {
    id: 'bloom-soft-diffusion',
    kind: 'bloom',
    name: 'Soft diffusion',
    params: {
      threshold: 0.55,
      softKnee: 0.3,
      intensity: 0.6,
      radius: 32,
      diffusion: 0.6,
      composite: 'screen',
      streakEnabled: false,
      streakAngle: 0,
      streakLength: 64,
      streakIntensity: 0,
      streakAspect: 2,
    },
  },
  {
    id: 'bloom-dreamy',
    kind: 'bloom',
    name: 'Dreamy highlights',
    params: {
      threshold: 0.45,
      softKnee: 0.25,
      intensity: 0.9,
      radius: 48,
      diffusion: 0.7,
      tint: [255, 240, 220],
      tintAmount: 0.4,
      composite: 'screen',
      streakEnabled: false,
      streakAngle: 0,
      streakLength: 64,
      streakIntensity: 0,
      streakAspect: 2,
    },
  },
  {
    id: 'bloom-anamorphic',
    kind: 'bloom',
    name: 'Anamorphic streak',
    params: {
      threshold: 0.5,
      softKnee: 0.2,
      intensity: 1.2,
      radius: 24,
      diffusion: 0.4,
      composite: 'screen',
      streakEnabled: true,
      streakAngle: 0,
      streakLength: 220,
      streakIntensity: 0.7,
      streakAspect: 3.5,
    },
  },
  {
    id: 'bloom-neon',
    kind: 'bloom',
    name: 'Neon glow',
    params: {
      threshold: 0.7,
      softKnee: 0.15,
      intensity: 1.6,
      radius: 16,
      diffusion: 0.3,
      composite: 'add',
      streakEnabled: false,
      streakAngle: 0,
      streakLength: 64,
      streakIntensity: 0,
      streakAspect: 2,
    },
  },

  // ── RGB Split ───────────────────────────────────────────────────────────
  {
    id: 'rgb-split-chromatic',
    kind: 'rgbSplit',
    name: 'Chromatic split',
    params: {
      mode: 'offset',
      redX: 4,
      redY: 0,
      greenX: 0,
      greenY: 0,
      blueX: -4,
      blueY: 0,
      amount: 4,
      centerX: 0.5,
      centerY: 0.5,
      falloff: 1,
      fringeAngle: 0,
      borderMode: 'transparent',
      intensity: 1,
    },
  },
  {
    id: 'rgb-split-lens',
    kind: 'rgbSplit',
    name: 'Lens fringe',
    params: {
      mode: 'radial',
      redX: 0,
      redY: 0,
      greenX: 0,
      greenY: 0,
      blueX: 0,
      blueY: 0,
      amount: 3,
      centerX: 0.5,
      centerY: 0.5,
      falloff: 1.6,
      fringeAngle: 0,
      borderMode: 'transparent',
      intensity: 1,
    },
  },
  {
    id: 'rgb-split-anaglyph',
    kind: 'rgbSplit',
    name: 'Anaglyph depth',
    params: {
      mode: 'offset',
      redX: 8,
      redY: 0,
      greenX: -4,
      greenY: 0,
      blueX: -4,
      blueY: 0,
      amount: 8,
      centerX: 0.5,
      centerY: 0.5,
      falloff: 1,
      fringeAngle: 0,
      borderMode: 'clamp',
      intensity: 0.8,
    },
  },

  // ── CRT ─────────────────────────────────────────────────────────────────
  {
    id: 'crt-aperture-grille',
    kind: 'crt',
    name: 'Aperture grille',
    params: {
      curvature: 0.12,
      cornerRadius: 0.3,
      scanlinePeriod: 3,
      scanlineStrength: 0.5,
      scanlineSoftness: 0.5,
      phosphorMask: 'aperture-grille',
      phosphorPitch: 4,
      phosphorIntensity: 0.55,
      glow: 0.35,
      vignette: 0.35,
      vignetteRadius: 0.5,
      convergenceX: 0.6,
      convergenceY: 0,
      brightness: 0.02,
      contrast: 1.08,
    },
  },
  {
    id: 'crt-consumer',
    kind: 'crt',
    name: 'Consumer CRT',
    params: {
      curvature: 0.3,
      cornerRadius: 0.55,
      scanlinePeriod: 3,
      scanlineStrength: 0.65,
      scanlineSoftness: 0.4,
      phosphorMask: 'rgb-stripe',
      phosphorPitch: 5,
      phosphorIntensity: 0.45,
      glow: 0.45,
      vignette: 0.55,
      vignetteRadius: 0.55,
      convergenceX: 1.2,
      convergenceY: 0.4,
      brightness: 0.05,
      contrast: 1.15,
    },
  },
  {
    id: 'crt-mono',
    kind: 'crt',
    name: 'Monochrome',
    params: {
      curvature: 0.1,
      cornerRadius: 0.3,
      scanlinePeriod: 2.5,
      scanlineStrength: 0.55,
      scanlineSoftness: 0.5,
      phosphorMask: 'shadow-mask',
      phosphorPitch: 4,
      phosphorIntensity: 0.5,
      glow: 0.5,
      vignette: 0.4,
      vignetteRadius: 0.5,
      convergenceX: 0,
      convergenceY: 0,
      brightness: 0,
      contrast: 1.1,
    },
  },
  {
    id: 'crt-arcade',
    kind: 'crt',
    name: 'Arcade',
    params: {
      curvature: 0.05,
      cornerRadius: 0.15,
      scanlinePeriod: 2,
      scanlineStrength: 0.75,
      scanlineSoftness: 0.25,
      phosphorMask: 'rgb-stripe',
      phosphorPitch: 3,
      phosphorIntensity: 0.7,
      glow: 0.5,
      vignette: 0.25,
      vignetteRadius: 0.5,
      convergenceX: 0.3,
      convergenceY: 0,
      brightness: 0,
      contrast: 1.2,
    },
  },
  {
    id: 'crt-soft-tv',
    kind: 'crt',
    name: 'Soft TV',
    params: {
      curvature: 0.08,
      cornerRadius: 0.25,
      scanlinePeriod: 4,
      scanlineStrength: 0.3,
      scanlineSoftness: 0.7,
      phosphorMask: 'none',
      phosphorPitch: 4,
      phosphorIntensity: 0,
      glow: 0.3,
      vignette: 0.3,
      vignetteRadius: 0.5,
      convergenceX: 0.5,
      convergenceY: 0,
      brightness: 0.02,
      contrast: 1.05,
    },
  },

  // ── VHS ─────────────────────────────────────────────────────────────────
  {
    id: 'vhs-clean',
    kind: 'vhs',
    name: 'Clean tape',
    params: {
      lumaNoise: 0.15,
      chromaNoise: 0.1,
      chromaBleed: 0.2,
      jitter: 0.15,
      tracking: 0.1,
      dropouts: 0.05,
      headSwitching: 0.2,
      tearing: 0.05,
      signalBlur: 0.1,
      timeInstability: 0.1,
      seed: 1,
      time: 0,
      frameRate: 24,
    },
  },
  {
    id: 'vhs-worn',
    kind: 'vhs',
    name: 'Worn tape',
    params: {
      lumaNoise: 0.35,
      chromaNoise: 0.3,
      chromaBleed: 0.45,
      jitter: 0.4,
      tracking: 0.35,
      dropouts: 0.2,
      headSwitching: 0.5,
      tearing: 0.25,
      signalBlur: 0.25,
      timeInstability: 0.3,
      seed: 1,
      time: 0,
      frameRate: 24,
    },
  },
  {
    id: 'vhs-heavy-tracking',
    kind: 'vhs',
    name: 'Heavy tracking',
    params: {
      lumaNoise: 0.5,
      chromaNoise: 0.45,
      chromaBleed: 0.6,
      jitter: 0.7,
      tracking: 0.8,
      dropouts: 0.35,
      headSwitching: 0.7,
      tearing: 0.5,
      signalBlur: 0.35,
      timeInstability: 0.5,
      seed: 3,
      time: 0,
      frameRate: 24,
    },
  },

  // ── Light Shafts ────────────────────────────────────────────────────────
  {
    id: 'shafts-god-rays',
    kind: 'lightShafts',
    name: 'God rays',
    params: {
      lightX: 0.5,
      lightY: 0.05,
      lightType: 'point',
      direction: 0,
      intensity: 1.2,
      exposure: 0,
      decay: 0.85,
      density: 0.2,
      weight: 0.9,
      sampleCount: 24,
      scattering: 0.3,
      occlusionSource: 'luminance',
      tint: null,
    },
  },
  {
    id: 'shafts-window',
    kind: 'lightShafts',
    name: 'Window light',
    params: {
      lightX: 0.5,
      lightY: -0.2,
      lightType: 'directional',
      direction: -20,
      intensity: 0.9,
      exposure: 0,
      decay: 0.9,
      density: 0.12,
      weight: 0.8,
      sampleCount: 24,
      scattering: 0.5,
      occlusionSource: 'luminance',
      tint: [255, 244, 214],
    },
  },

  // ── Lens Flare ──────────────────────────────────────────────────────────
  {
    id: 'flare-soft',
    kind: 'lensFlare',
    name: 'Soft flare',
    params: {
      sourceX: 0.5,
      sourceY: 0.3,
      brightness: 0.7,
      scale: 0.8,
      ghostCount: 3,
      ghostSpacing: 0.7,
      halo: 0.5,
      apertureBlades: 0,
      apertureRotation: 0,
      streakIntensity: 0.2,
      anamorphicRatio: 0.2,
      chromaticDispersion: 0.4,
      seed: 0,
    },
  },
  {
    id: 'flare-anamorphic',
    kind: 'lensFlare',
    name: 'Anamorphic flare',
    params: {
      sourceX: 0.5,
      sourceY: 0.4,
      brightness: 1.1,
      scale: 1.1,
      ghostCount: 5,
      ghostSpacing: 0.9,
      halo: 0.6,
      apertureBlades: 0,
      apertureRotation: 0,
      streakIntensity: 0.8,
      anamorphicRatio: 0.9,
      chromaticDispersion: 0.5,
      seed: 2,
    },
  },
  {
    id: 'flare-aperture',
    kind: 'lensFlare',
    name: 'Aperture star',
    params: {
      sourceX: 0.5,
      sourceY: 0.35,
      brightness: 1.3,
      scale: 1,
      ghostCount: 4,
      ghostSpacing: 0.8,
      halo: 0.4,
      apertureBlades: 8,
      apertureRotation: 22,
      streakIntensity: 0.5,
      anamorphicRatio: 0.1,
      chromaticDispersion: 0.3,
      seed: 5,
    },
  },

  // ── Light Leak ──────────────────────────────────────────────────────────
  {
    id: 'leak-sunset',
    kind: 'lightLeak',
    name: 'Sunset leak',
    params: {
      seed: 4,
      x: 0.15,
      y: 0.4,
      angle: 20,
      size: 1.1,
      softness: 0.7,
      hue: 25,
      saturation: 0.85,
      lightness: 0.6,
      intensity: 0.7,
      noiseScale: 0.5,
    },
  },
  {
    id: 'leak-cyan',
    kind: 'lightLeak',
    name: 'Cyan leak',
    params: {
      seed: 9,
      x: 0.85,
      y: 0.6,
      angle: -15,
      size: 0.9,
      softness: 0.6,
      hue: 190,
      saturation: 0.8,
      lightness: 0.55,
      intensity: 0.6,
      noiseScale: 0.6,
    },
  },
  {
    id: 'leak-magenta',
    kind: 'lightLeak',
    name: 'Magenta leak',
    params: {
      seed: 12,
      x: 0.5,
      y: 0.1,
      angle: 90,
      size: 0.8,
      softness: 0.8,
      hue: 315,
      saturation: 0.7,
      lightness: 0.6,
      intensity: 0.5,
      noiseScale: 0.4,
    },
  },

  // ── Caustics ────────────────────────────────────────────────────────────
  {
    id: 'caustics-shallow',
    kind: 'caustics',
    name: 'Shallow pool',
    params: {
      scale: 28,
      depth: 0.45,
      waveCount: 4,
      complexity: 0.2,
      refractionAmount: 0.4,
      sharpness: 0.5,
      lightAngle: 60,
      brightness: 1,
      contrast: 1.1,
      dispersion: 0.1,
      distortionAmount: 0.8,
      output: 'combined',
      waterTint: null,
      surfaceTint: null,
      seed: 3,
      time: 0,
      animationSpeed: 0.5,
      tileable: false,
    },
  },
  {
    id: 'caustics-deep',
    kind: 'caustics',
    name: 'Deep water',
    params: {
      scale: 48,
      depth: 0.7,
      waveCount: 6,
      complexity: 0.4,
      refractionAmount: 0.6,
      sharpness: 0.65,
      lightAngle: 75,
      brightness: 1.2,
      contrast: 1.3,
      dispersion: 0.2,
      distortionAmount: 1,
      output: 'combined',
      waterTint: [30, 90, 160],
      surfaceTint: null,
      seed: 8,
      time: 0,
      animationSpeed: 0.4,
      tileable: false,
    },
  },
  {
    id: 'caustics-stylized',
    kind: 'caustics',
    name: 'Stylized caustics',
    params: {
      scale: 22,
      depth: 0.55,
      waveCount: 3,
      complexity: 0.6,
      refractionAmount: 0.3,
      sharpness: 0.8,
      lightAngle: 45,
      brightness: 1.4,
      contrast: 1.6,
      dispersion: 0.3,
      distortionAmount: 0.7,
      output: 'lighting',
      waterTint: [190, 230, 255],
      surfaceTint: null,
      seed: 15,
      time: 0,
      animationSpeed: 0.8,
      tileable: true,
    },
  },
];

/** Presets for a given effect kind. */
export function presetsForKind(kind: AdjustmentKind): LiveEffectPreset[] {
  return LIVE_EFFECT_PRESETS.filter((p) => p.kind === kind);
}
