/**
 * Validates the stored binary `.grd` fixtures in `./__fixtures__`.
 *
 * Provenance: every fixture was generated by `testFixtures.ts` (clean-room
 * writer mirroring the documented `.grd` layouts). See `__fixtures__/PROVENANCE.md`.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';
import { parsePhotoshopGrd } from '../photoshopGrd';

const fixturesDir = dirname(fileURLToPath(import.meta.url));
const read = (name: string) => new Uint8Array(readFileSync(join(fixturesDir, name)));

describe('stored .grd fixtures', () => {
  it('two-stop.grd parses', () => {
    const { gradients, warnings } = parsePhotoshopGrd(read('two-stop.grd'));
    expect(gradients).toHaveLength(1);
    expect(gradients[0]!.name).toBe('Black to White');
    expect(gradients[0]!.colorStops[0]!.color).toEqual([0, 0, 0, 255]);
    expect(gradients[0]!.colorStops[1]!.color).toEqual([255, 255, 255, 255]);
    expect(warnings).toEqual([]);
  });

  it('multi-gradient.grd has 4 gradients incl. opacity stops + smoothness', () => {
    const { gradients } = parsePhotoshopGrd(read('multi-gradient.grd'));
    expect(gradients).toHaveLength(4);
    const sunset = gradients[1]!;
    expect(sunset.colorStops).toHaveLength(3);
    expect(sunset.colorStops[1]!.midpoint).toBeCloseTo(0.3, 3);
    expect(sunset.opacityStops).toHaveLength(3);
    expect(sunset.opacityStops[1]!.opacity).toBeCloseTo(0.25, 3);
    expect(sunset.smoothness).toBeCloseTo(0.75, 3);
  });

  it('mixed-color-models.grd converts HSBC/CMYC/Grsc', () => {
    const { gradients } = parsePhotoshopGrd(read('mixed-color-models.grd'));
    const stops = gradients[0]!.colorStops;
    expect(stops.map((s) => s.colorModel)).toEqual(['RGBC', 'HSBC', 'CMYC', 'Grsc']);
  });

  it('noise-gradient.grd is read-only', () => {
    const { gradients, warnings } = parsePhotoshopGrd(read('noise-gradient.grd'));
    expect(gradients[0]!.isNoise).toBe(true);
    expect(warnings.length).toBeGreaterThan(0);
  });

  it('unicode-names.grd keeps unicode and empty names', () => {
    const { gradients } = parsePhotoshopGrd(read('unicode-names.grd'));
    expect(gradients[0]!.name).toBe('Ünïcödé 名称');
    expect(gradients[1]!.name).toBe('');
  });

  it('legacy-v1.grd and legacy-v2.grd parse', () => {
    const v1 = parsePhotoshopGrd(read('legacy-v1.grd'));
    expect(v1.gradients).toHaveLength(2);
    const v2 = parsePhotoshopGrd(read('legacy-v2.grd'));
    expect(v2.gradients[0]!.smoothness).toBeCloseTo(0.5, 2);
  });

  it('truncated.grd fails in a controlled way', () => {
    expect(() => parsePhotoshopGrd(read('truncated.grd'))).toThrow();
  });

  it('empty.grd is rejected as unsupported', () => {
    expect(() => parsePhotoshopGrd(read('empty.grd'))).toThrow();
  });
});
